/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Adds a rule that reads a transaction description and fills in a category, a set of tags, or both. The new rule goes last, so it only decides rows no earlier rule claimed; move it with the reorder operation. A rule never changes anything on its own: it suggests a category in the import preview, and it writes to the ledger only when you ask for a run.
 * @summary Create a categorization rule
 */
export const createCategorizationRuleBodyNameMin = 0;
export const createCategorizationRuleBodyNameMax = 50;

export const createCategorizationRuleBodyPatternMin = 0;
export const createCategorizationRuleBodyPatternMax = 200;

export const createCategorizationRuleBodyMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createCategorizationRuleBodyMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateCategorizationRuleBody = zod.object({
  name: zod
    .string()
    .min(createCategorizationRuleBodyNameMin)
    .max(createCategorizationRuleBodyNameMax)
    .describe("What the rule is called on the rules screen and in a run's result."),
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod
    .string()
    .min(createCategorizationRuleBodyPatternMin)
    .max(createCategorizationRuleBodyPatternMax)
    .describe(
      "The text the description is compared with. Per cent and underscore are literal characters, not wildcards.",
    ),
  tagIds: zod
    .array(zod.uuid())
    .min(1)
    .describe(
      "The tags the rule adds, at most ten; an empty list adds none. A run adds them and never removes tags the row already carries.",
    ),
  accountId: zod
    .uuid()
    .nullish()
    .describe(
      "Narrows the rule to one account; leave it out to let the rule see every account you can.",
    ),
  minAmount: zod
    .stringFormat("decimal", createCategorizationRuleBodyMinAmountRegExp)
    .nullish()
    .describe("Lowest transaction amount the rule accepts, in the transaction's own currency."),
  maxAmount: zod
    .stringFormat("decimal", createCategorizationRuleBodyMaxAmountRegExp)
    .nullish()
    .describe("Highest transaction amount the rule accepts, in the transaction's own currency."),
  categoryId: zod
    .uuid()
    .nullish()
    .describe(
      "The category the rule sets. Its flow type also narrows the rule: an expense category never matches income.",
    ),
});

export const createCategorizationRuleResponseMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createCategorizationRuleResponseMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateCategorizationRuleResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  position: zod.int(),
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod.string(),
  accountId: zod.uuid().nullable(),
  minAmount: zod
    .stringFormat("decimal", createCategorizationRuleResponseMinAmountRegExp)
    .nullable(),
  maxAmount: zod
    .stringFormat("decimal", createCategorizationRuleResponseMaxAmountRegExp)
    .nullable(),
  categoryId: zod.uuid().nullable(),
  tagIds: zod.array(zod.uuid()),
});

/**
 * Returns your own rules in the order they are evaluated, lowest position first. Rules are personal: nobody else sees them, not even a member of a household you share an account with. The first rule whose condition matches a description decides what the row gets, so the order is the rule, not a detail of the list.
 * @summary List categorization rules
 */
export const categorizationRulesResponseMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const categorizationRulesResponseMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CategorizationRulesResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  position: zod.int(),
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod.string(),
  accountId: zod.uuid().nullable(),
  minAmount: zod.stringFormat("decimal", categorizationRulesResponseMinAmountRegExp).nullable(),
  maxAmount: zod.stringFormat("decimal", categorizationRulesResponseMaxAmountRegExp).nullable(),
  categoryId: zod.uuid().nullable(),
  tagIds: zod.array(zod.uuid()),
});
export const CategorizationRulesResponse = zod.array(CategorizationRulesResponseItem);

/**
 * Applies the rules to the transactions the preview counted, in one database transaction: the first rule that claims a row sets its category and adds its tags, and no later rule touches that row again. Tags are added, never removed, so a tag somebody put on a row by hand survives. With recategorize false, the default, a row that already carries a category is not offered to any rule; with true, a matching row's category is replaced. Split transactions are never touched.
 * @summary Run the rules over the ledger
 */
export const runCategorizationRulesBodyRecategorizeDefault = false;

export const RunCategorizationRulesBody = zod.object({
  accountId: zod
    .uuid()
    .nullish()
    .describe("Narrows the run to one account; leave it out for every account you can see."),
  recategorize: zod
    .boolean()
    .default(runCategorizationRulesBodyRecategorizeDefault)
    .describe(
      "false, the default, leaves every row that already carries a category alone. true also offers those rows to the rules and replaces the category on the ones that match.",
    ),
});

export const RunCategorizationRulesResponse = zod.object({
  rules: zod.array(
    zod.object({
      ruleId: zod.uuid(),
      name: zod.string(),
      rowCount: zod.int(),
    }),
  ),
  total: zod.int(),
  recategorize: zod.boolean(),
});

/**
 * Reads the ledger and answers how many rows each rule would fill in, without writing anything. The count is the one the run will use: rules are evaluated in order and a row belongs to the first rule that claims it, so the numbers never double-count a row. By default only rows with no category at all are considered; split transactions are left out, because their categories live on their lines. The matching happens in PostgreSQL, so the size of the ledger does not decide how much the server loads.
 * @summary Count what a run of the rules would touch
 */
export const previewCategorizationRunBodyRecategorizeDefault = false;

export const PreviewCategorizationRunBody = zod.object({
  accountId: zod
    .uuid()
    .nullish()
    .describe("Narrows the run to one account; leave it out for every account you can see."),
  recategorize: zod
    .boolean()
    .default(previewCategorizationRunBodyRecategorizeDefault)
    .describe(
      "false, the default, leaves every row that already carries a category alone. true also offers those rows to the rules and replaces the category on the ones that match.",
    ),
});

export const PreviewCategorizationRunResponse = zod.object({
  rules: zod.array(
    zod.object({
      ruleId: zod.uuid(),
      name: zod.string(),
      rowCount: zod.int(),
    }),
  ),
  total: zod.int(),
  recategorize: zod.boolean(),
});

/**
 * Answers whether a condition that has not been saved yet would match a sample description, and whether a sample amount falls inside the range. Nothing is read from the ledger and nothing is written, so the form can ask this on every keystroke. The answer separates the two halves of the condition, so a rule that fails only on the amount can say so. The action the rule would take is already in the form, which is why this call does not repeat it.
 * @summary Try a rule against a sample description
 */
export const testCategorizationRuleBodyPatternMin = 0;
export const testCategorizationRuleBodyPatternMax = 200;

export const testCategorizationRuleBodyDescriptionMin = 0;
export const testCategorizationRuleBodyDescriptionMax = 500;

export const testCategorizationRuleBodyAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const testCategorizationRuleBodyMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const testCategorizationRuleBodyMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const TestCategorizationRuleBody = zod.object({
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod
    .string()
    .min(testCategorizationRuleBodyPatternMin)
    .max(testCategorizationRuleBodyPatternMax)
    .describe("The text the draft rule compares with."),
  description: zod
    .string()
    .min(testCategorizationRuleBodyDescriptionMin)
    .max(testCategorizationRuleBodyDescriptionMax)
    .describe("The sample description typed into the form."),
  amount: zod
    .stringFormat("decimal", testCategorizationRuleBodyAmountRegExp)
    .nullish()
    .describe("An optional sample amount; leave it out to test the description alone."),
  minAmount: zod
    .stringFormat("decimal", testCategorizationRuleBodyMinAmountRegExp)
    .nullish()
    .describe("The draft rule's lowest amount."),
  maxAmount: zod
    .stringFormat("decimal", testCategorizationRuleBodyMaxAmountRegExp)
    .nullish()
    .describe("The draft rule's highest amount."),
});

export const TestCategorizationRuleResponse = zod.object({
  matches: zod.boolean(),
  descriptionMatches: zod.boolean(),
  amountMatches: zod.boolean(),
});

/**
 * Removes the rule and the tags it would have added. The transactions it filled in earlier keep their category and their tags, because a rule writes once and owns nothing afterwards. The rules below it close the gap, so the positions stay 0, 1, 2 without a hole.
 * @summary Delete a categorization rule
 */
export const DeleteCategorizationRuleResponse = zod.void();

/**
 * Replaces the condition, the narrowing and the action of a rule. The tag list is replaced whole, so an empty list clears the tags the rule would add. The position is not part of this body; reorder with the move operation. Transactions the rule already filled keep what they got: a rule is applied when it runs, never afterwards.
 * @summary Update a categorization rule
 */
export const updateCategorizationRuleBodyNameMin = 0;
export const updateCategorizationRuleBodyNameMax = 50;

export const updateCategorizationRuleBodyPatternMin = 0;
export const updateCategorizationRuleBodyPatternMax = 200;

export const updateCategorizationRuleBodyMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateCategorizationRuleBodyMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateCategorizationRuleBody = zod.object({
  name: zod
    .string()
    .min(updateCategorizationRuleBodyNameMin)
    .max(updateCategorizationRuleBodyNameMax),
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod
    .string()
    .min(updateCategorizationRuleBodyPatternMin)
    .max(updateCategorizationRuleBodyPatternMax),
  tagIds: zod.array(zod.uuid()).min(1),
  accountId: zod.uuid().nullish(),
  minAmount: zod.stringFormat("decimal", updateCategorizationRuleBodyMinAmountRegExp).nullish(),
  maxAmount: zod.stringFormat("decimal", updateCategorizationRuleBodyMaxAmountRegExp).nullish(),
  categoryId: zod.uuid().nullish(),
});

export const updateCategorizationRuleResponseMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateCategorizationRuleResponseMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateCategorizationRuleResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  position: zod.int(),
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod.string(),
  accountId: zod.uuid().nullable(),
  minAmount: zod
    .stringFormat("decimal", updateCategorizationRuleResponseMinAmountRegExp)
    .nullable(),
  maxAmount: zod
    .stringFormat("decimal", updateCategorizationRuleResponseMaxAmountRegExp)
    .nullable(),
  categoryId: zod.uuid().nullable(),
  tagIds: zod.array(zod.uuid()),
});

/**
 * Swaps the rule with its neighbour and answers the whole list in its new order, so a client never has to guess what the positions became. Moving the first rule up or the last rule down changes nothing and still answers the list. Positions stay dense: every move renumbers them 0, 1, 2 in the order the list comes back.
 * @summary Move a rule one place up or down
 */
export const MoveCategorizationRuleBody = zod.object({
  direction: zod.enum(["up", "down"]).describe("up moves the rule earlier, down moves it later."),
});

export const moveCategorizationRuleResponseMinAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const moveCategorizationRuleResponseMaxAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const MoveCategorizationRuleResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  position: zod.int(),
  match: zod.enum(["contains", "startsWith", "exact"]),
  pattern: zod.string(),
  accountId: zod.uuid().nullable(),
  minAmount: zod.stringFormat("decimal", moveCategorizationRuleResponseMinAmountRegExp).nullable(),
  maxAmount: zod.stringFormat("decimal", moveCategorizationRuleResponseMaxAmountRegExp).nullable(),
  categoryId: zod.uuid().nullable(),
  tagIds: zod.array(zod.uuid()),
});
export const MoveCategorizationRuleResponse = zod.array(MoveCategorizationRuleResponseItem);
