/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Every signed-in user can read the settings, because they decide which pages, currencies and defaults the client offers. Only administrators can change them.
 * @summary Read installation settings
 */
export const SettingsResponse = zod.object({
  instanceName: zod.string().nullable(),
  features: zod.object({
    budgets: zod.boolean(),
    goals: zod.boolean(),
    recurringBills: zod.boolean(),
    netWorth: zod.boolean(),
    reports: zod.boolean(),
    import: zod.boolean(),
    households: zod.boolean(),
    multiCurrency: zod.boolean(),
    investments: zod.boolean(),
    categorizationRules: zod.boolean(),
  }),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  enabledCurrencies: zod.array(
    zod.enum([
      "eur",
      "usd",
      "gbp",
      "chf",
      "pln",
      "sek",
      "nok",
      "dkk",
      "czk",
      "huf",
      "ron",
      "isk",
      "try",
      "jpy",
      "cny",
      "hkd",
      "sgd",
      "krw",
      "inr",
      "idr",
      "myr",
      "php",
      "thb",
      "aud",
      "nzd",
      "cad",
      "mxn",
      "brl",
      "ils",
      "zar",
    ]),
  ),
  exchangeRateSyncEnabled: zod.boolean(),
  ratesAsOf: zod.union([zod.null(), zod.iso.date()]),
  defaultLanguage: zod.string(),
  timeZone: zod.string(),
  firstDayOfWeek: zod.enum(["monday", "sunday"]),
  defaultAccountId: zod.uuid().nullable(),
  defaultPageSize: zod.int(),
});

/**
 * Administrators only. Replaces every installation-wide setting. A feature that is turned off answers 404 with code feature.disabled on its routes and its background work stops; its data is kept. Changing the reporting currency revalues every stored transaction at the exchange rate for its own date and fails without saving anything if a rate is missing. Budgets, goals, assets, debts, bills and net worth history keep their numbers.
 * @summary Update installation settings
 */
export const updateSettingsBodyInstanceNameMin = 0;
export const updateSettingsBodyInstanceNameMax = 40;

export const UpdateSettingsBody = zod.object({
  instanceName: zod
    .string()
    .min(updateSettingsBodyInstanceNameMin)
    .max(updateSettingsBodyInstanceNameMax)
    .nullable()
    .describe("Shown beside the logo and in the browser tab. Null uses the product name."),
  features: zod.object({
    budgets: zod.boolean(),
    goals: zod.boolean(),
    recurringBills: zod.boolean(),
    netWorth: zod.boolean(),
    reports: zod.boolean(),
    import: zod.boolean(),
    households: zod.boolean(),
    multiCurrency: zod.boolean(),
    investments: zod.boolean(),
    categorizationRules: zod.boolean(),
  }),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  enabledCurrencies: zod
    .array(
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    )
    .describe("Currencies offered when entering data. The reporting currency is always included."),
  exchangeRateSyncEnabled: zod.boolean(),
  defaultLanguage: zod.string(),
  timeZone: zod.string().describe("IANA time zone id that decides what today and this month mean."),
  firstDayOfWeek: zod.enum(["monday", "sunday"]),
  defaultAccountId: zod
    .uuid()
    .nullable()
    .describe("Account preselected when adding a transaction, if the user can see it."),
  defaultPageSize: zod.int(),
});

export const UpdateSettingsResponse = zod.object({
  instanceName: zod.string().nullable(),
  features: zod.object({
    budgets: zod.boolean(),
    goals: zod.boolean(),
    recurringBills: zod.boolean(),
    netWorth: zod.boolean(),
    reports: zod.boolean(),
    import: zod.boolean(),
    households: zod.boolean(),
    multiCurrency: zod.boolean(),
    investments: zod.boolean(),
    categorizationRules: zod.boolean(),
  }),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  enabledCurrencies: zod.array(
    zod.enum([
      "eur",
      "usd",
      "gbp",
      "chf",
      "pln",
      "sek",
      "nok",
      "dkk",
      "czk",
      "huf",
      "ron",
      "isk",
      "try",
      "jpy",
      "cny",
      "hkd",
      "sgd",
      "krw",
      "inr",
      "idr",
      "myr",
      "php",
      "thb",
      "aud",
      "nzd",
      "cad",
      "mxn",
      "brl",
      "ils",
      "zar",
    ]),
  ),
  exchangeRateSyncEnabled: zod.boolean(),
  ratesAsOf: zod.union([zod.null(), zod.iso.date()]),
  defaultLanguage: zod.string(),
  timeZone: zod.string(),
  firstDayOfWeek: zod.enum(["monday", "sunday"]),
  defaultAccountId: zod.uuid().nullable(),
  defaultPageSize: zod.int(),
});

/**
 * Administrators only. Fetches reference rates published since the newest stored date. It works even when automatic sync is turned off.
 * @summary Fetch exchange rates now
 */
export const SyncExchangeRatesResponse = zod.object({
  added: zod.int(),
  ratesAsOf: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Anonymous. Returns only the installation name, the default language and whether this installation can send email, which is what decides if the sign-in page offers "Forgot password". No host name, no address and no credential is part of the answer.
 * @summary Read the settings the sign-in page needs
 */
export const PublicSettingsResponse = zod.object({
  instanceName: zod.string().nullable(),
  defaultLanguage: zod.string(),
  emailEnabled: zod.boolean(),
});

/**
 * Answers the SMTP host, port, encryption mode, user name, sender address and sender name, plus the enabled switch. The password is never part of the answer; hasPassword says only whether one is stored. Administrators only, unlike GET /api/settings, because these values describe an outside system.
 * @summary Read the mail server of this installation
 */
export const SmtpSettingsResponse = zod.object({
  enabled: zod.boolean(),
  host: zod.string().nullable(),
  port: zod.int(),
  encryption: zod
    .enum(["startTls", "sslOnConnect", "none"])
    .describe(
      "startTls (the default, usually port 587; the server must offer STARTTLS), sslOnConnect (usually port 465) or none, which is only accepted without a user name.",
    ),
  userName: zod.string().nullable(),
  hasPassword: zod.boolean(),
  fromAddress: zod.string().nullable(),
  fromName: zod.string().nullable(),
});

/**
 * Stores the SMTP host, port, encryption mode, optional user name and password, and the sender address and name, on the single installation settings row. The password is encrypted with ASP.NET Data Protection before it is stored and is never returned: the response carries hasPassword instead. Leaving password empty keeps the stored one, but only while the host and the user name stay the same: changing either without a new password answers 400 email.passwordRequired, so a saved password is never sent to another server or account. Clearing the user name clears the stored password with it, because an anonymous relay has nothing to authenticate. A user name needs startTls or sslOnConnect: none with a user name answers 400 email.insecureConnection, because credentials are never sent in plain text. Switching enabled on needs a host and a sender address. Administrators only.
 * @summary Save the mail server of this installation
 */
export const updateSmtpSettingsBodyHostMin = 0;
export const updateSmtpSettingsBodyHostMax = 255;

export const updateSmtpSettingsBodyPortMax = 65535;

export const updateSmtpSettingsBodyUserNameMin = 0;
export const updateSmtpSettingsBodyUserNameMax = 255;

export const updateSmtpSettingsBodyPasswordMin = 0;
export const updateSmtpSettingsBodyPasswordMax = 255;

export const updateSmtpSettingsBodyFromAddressMin = 0;
export const updateSmtpSettingsBodyFromAddressMax = 320;

export const updateSmtpSettingsBodyFromAddressRegExp = new RegExp("^[^@]+@[^@]+$");
export const updateSmtpSettingsBodyFromNameMin = 0;
export const updateSmtpSettingsBodyFromNameMax = 100;

export const UpdateSmtpSettingsBody = zod.object({
  enabled: zod.boolean(),
  host: zod
    .string()
    .min(updateSmtpSettingsBodyHostMin)
    .max(updateSmtpSettingsBodyHostMax)
    .nullable(),
  port: zod.int().min(1).max(updateSmtpSettingsBodyPortMax),
  encryption: zod
    .enum(["startTls", "sslOnConnect", "none"])
    .describe(
      "startTls (the default, usually port 587; the server must offer STARTTLS), sslOnConnect (usually port 465) or none, which is only accepted without a user name.",
    ),
  userName: zod
    .string()
    .min(updateSmtpSettingsBodyUserNameMin)
    .max(updateSmtpSettingsBodyUserNameMax)
    .nullable(),
  password: zod
    .string()
    .min(updateSmtpSettingsBodyPasswordMin)
    .max(updateSmtpSettingsBodyPasswordMax)
    .nullable()
    .describe(
      "Leave empty to keep the stored password; required when the host or user name changes.",
    ),
  fromAddress: zod
    .email()
    .min(updateSmtpSettingsBodyFromAddressMin)
    .max(updateSmtpSettingsBodyFromAddressMax)
    .regex(updateSmtpSettingsBodyFromAddressRegExp)
    .nullable(),
  fromName: zod
    .string()
    .min(updateSmtpSettingsBodyFromNameMin)
    .max(updateSmtpSettingsBodyFromNameMax)
    .nullable(),
});

export const UpdateSmtpSettingsResponse = zod.object({
  enabled: zod.boolean(),
  host: zod.string().nullable(),
  port: zod.int(),
  encryption: zod
    .enum(["startTls", "sslOnConnect", "none"])
    .describe(
      "startTls (the default, usually port 587; the server must offer STARTTLS), sslOnConnect (usually port 465) or none, which is only accepted without a user name.",
    ),
  userName: zod.string().nullable(),
  hasPassword: zod.boolean(),
  fromAddress: zod.string().nullable(),
  fromName: zod.string().nullable(),
});

/**
 * Sends one short message to the calling administrator's own address with the settings that are stored right now, and waits for the mail server to accept it. Nothing is written: the message does not go through the outbox and leaves no row behind, so a failed attempt is not retried. Success answers the address the message went to; a refusal answers 400 with email.sendFailed and the mail server's own words, email.notConfigured when the settings are incomplete or switched off, or email.passwordUnreadable when the stored password cannot be decrypted, which is what a restore into an installation with different data protection keys leaves behind. The attempt gives up after the configured send timeout, so a dead server cannot hold the request open. Save the settings before testing them. Rate limited to 10 calls per five minutes per client.
 * @summary Send a test message
 */
export const SendTestEmailResponse = zod.object({
  sentTo: zod.string(),
});
