/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Every signed-in user can read the settings, because they decide which pages, currencies and defaults the client offers. Only administrators can change them.
 * @summary Read installation settings
 */
export const SettingsResponse = zod.object({
  instanceName: zod.string().nullable(),
  features: zod.object({
    budgets: zod.boolean(),
    goals: zod.boolean(),
    recurringBills: zod.boolean(),
    netWorth: zod.boolean(),
    reports: zod.boolean(),
    import: zod.boolean(),
    households: zod.boolean(),
    multiCurrency: zod.boolean(),
    investments: zod.boolean(),
    categorizationRules: zod.boolean(),
    unusualAmounts: zod.boolean(),
    monthClose: zod.boolean(),
    receiptReading: zod.boolean(),
    apiTokens: zod.boolean(),
    locations: zod.boolean(),
    learnedCategories: zod.boolean(),
    attachments: zod.boolean(),
    payeeNames: zod.boolean(),
    people: zod.boolean(),
    cashFlowForecast: zod.boolean(),
  }),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  enabledCurrencies: zod.array(
    zod.enum([
      "eur",
      "usd",
      "gbp",
      "chf",
      "pln",
      "sek",
      "nok",
      "dkk",
      "czk",
      "huf",
      "ron",
      "isk",
      "try",
      "jpy",
      "cny",
      "hkd",
      "sgd",
      "krw",
      "inr",
      "idr",
      "myr",
      "php",
      "thb",
      "aud",
      "nzd",
      "cad",
      "mxn",
      "brl",
      "ils",
      "zar",
    ]),
  ),
  exchangeRateSyncEnabled: zod.boolean(),
  ratesAsOf: zod.union([zod.null(), zod.iso.date()]),
  defaultLanguage: zod.string(),
  timeZone: zod.string(),
  firstDayOfWeek: zod.enum(["monday", "sunday"]),
  defaultAccountId: zod.uuid().nullable(),
  defaultPageSize: zod.int(),
  supportLinkEnabled: zod.boolean(),
  receiptReadingReady: zod.boolean(),
  setupPending: zod.boolean(),
  demoData: zod.boolean(),
});

/**
 * Administrators only. Replaces every installation-wide setting. A feature that is turned off answers 404 with code feature.disabled on its routes and its background work stops; its data is kept. Changing the reporting currency revalues every stored transaction at the exchange rate for its own date and fails without saving anything if a rate is missing. Budgets, goals, assets, debts, bills and net worth history keep their numbers.
 * @summary Update installation settings
 */
export const updateSettingsBodyInstanceNameMin = 0;
export const updateSettingsBodyInstanceNameMax = 40;

export const UpdateSettingsBody = zod.object({
  instanceName: zod
    .string()
    .min(updateSettingsBodyInstanceNameMin)
    .max(updateSettingsBodyInstanceNameMax)
    .nullable()
    .describe("Shown beside the logo and in the browser tab. Null uses the product name."),
  features: zod.object({
    budgets: zod.boolean(),
    goals: zod.boolean(),
    recurringBills: zod.boolean(),
    netWorth: zod.boolean(),
    reports: zod.boolean(),
    import: zod.boolean(),
    households: zod.boolean(),
    multiCurrency: zod.boolean(),
    investments: zod.boolean(),
    categorizationRules: zod.boolean(),
    unusualAmounts: zod.boolean(),
    monthClose: zod.boolean(),
    receiptReading: zod.boolean(),
    apiTokens: zod.boolean(),
    locations: zod.boolean(),
    learnedCategories: zod.boolean(),
    attachments: zod.boolean(),
    payeeNames: zod.boolean(),
    people: zod.boolean(),
    cashFlowForecast: zod.boolean(),
  }),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  enabledCurrencies: zod
    .array(
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    )
    .describe("Currencies offered when entering data. The reporting currency is always included."),
  exchangeRateSyncEnabled: zod.boolean(),
  defaultLanguage: zod.string(),
  timeZone: zod.string().describe("IANA time zone id that decides what today and this month mean."),
  firstDayOfWeek: zod.enum(["monday", "sunday"]),
  defaultAccountId: zod
    .uuid()
    .nullable()
    .describe("Account preselected when adding a transaction, if the user can see it."),
  defaultPageSize: zod.int(),
  supportLinkEnabled: zod
    .boolean()
    .describe(
      "Shows the Support on Ko-fi link in every user's sidebar. It is a plain external link, so turning it on makes no outbound request.",
    ),
});

export const UpdateSettingsResponse = zod.object({
  instanceName: zod.string().nullable(),
  features: zod.object({
    budgets: zod.boolean(),
    goals: zod.boolean(),
    recurringBills: zod.boolean(),
    netWorth: zod.boolean(),
    reports: zod.boolean(),
    import: zod.boolean(),
    households: zod.boolean(),
    multiCurrency: zod.boolean(),
    investments: zod.boolean(),
    categorizationRules: zod.boolean(),
    unusualAmounts: zod.boolean(),
    monthClose: zod.boolean(),
    receiptReading: zod.boolean(),
    apiTokens: zod.boolean(),
    locations: zod.boolean(),
    learnedCategories: zod.boolean(),
    attachments: zod.boolean(),
    payeeNames: zod.boolean(),
    people: zod.boolean(),
    cashFlowForecast: zod.boolean(),
  }),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  enabledCurrencies: zod.array(
    zod.enum([
      "eur",
      "usd",
      "gbp",
      "chf",
      "pln",
      "sek",
      "nok",
      "dkk",
      "czk",
      "huf",
      "ron",
      "isk",
      "try",
      "jpy",
      "cny",
      "hkd",
      "sgd",
      "krw",
      "inr",
      "idr",
      "myr",
      "php",
      "thb",
      "aud",
      "nzd",
      "cad",
      "mxn",
      "brl",
      "ils",
      "zar",
    ]),
  ),
  exchangeRateSyncEnabled: zod.boolean(),
  ratesAsOf: zod.union([zod.null(), zod.iso.date()]),
  defaultLanguage: zod.string(),
  timeZone: zod.string(),
  firstDayOfWeek: zod.enum(["monday", "sunday"]),
  defaultAccountId: zod.uuid().nullable(),
  defaultPageSize: zod.int(),
  supportLinkEnabled: zod.boolean(),
  receiptReadingReady: zod.boolean(),
  setupPending: zod.boolean(),
  demoData: zod.boolean(),
});

/**
 * Answers whether Discord is switched on, whether a webhook is saved, when a message last reached it and the last error. The webhook URL is never part of the answer, because anyone holding it can post to the channel. disabledByDiscord is true after Discord answered that the webhook no longer exists; unreadable is true when the stored URL cannot be decrypted, which a restore into an installation with other data protection keys leaves behind. Administrators only.
 * @summary Read the installation's Discord channel
 */
export const DiscordSettingsResponse = zod.object({
  enabled: zod.boolean(),
  hasWebhook: zod.boolean(),
  lastDeliveredAt: zod.iso.datetime({ offset: true }).nullable(),
  lastError: zod.string().nullable(),
  disabledByDiscord: zod.boolean(),
  unreadable: zod.boolean(),
});

/**
 * Stores the webhook of the one Discord channel this installation posts to and switches outbound Discord traffic on or off for everyone. Members then choose on their profile which of their notifications are posted there, with their name in front. Only webhook URLs on discord.com, discordapp.com, ptb.discord.com or canary.discord.com of the form https://discord.com/api/webhooks/{id}/{token} are accepted; anything else answers 400 discord.invalidWebhook, as does switching Discord on before a webhook is saved. The URL is encrypted before it is stored and never returned. Leaving webhookUrl empty keeps the stored one; a new URL also clears the mark Discord left on a webhook it no longer knows. While Discord is off nothing is queued or sent; messages that were already queued are not sent late but pruned after seven days. Administrators only.
 * @summary Save the installation's Discord channel
 */
export const UpdateDiscordSettingsBody = zod.object({
  enabled: zod.boolean(),
  webhookUrl: zod.string().nullable().describe("Leave empty to keep the stored webhook."),
});

export const UpdateDiscordSettingsResponse = zod.object({
  enabled: zod.boolean(),
  hasWebhook: zod.boolean(),
  lastDeliveredAt: zod.iso.datetime({ offset: true }).nullable(),
  lastError: zod.string().nullable(),
  disabledByDiscord: zod.boolean(),
  unreadable: zod.boolean(),
});

/**
 * Posts one short message to the saved webhook right away and waits for Discord's answer, even while Discord is switched off, so the channel can be checked before members use it. Nothing is queued, so a failure is not retried. A refusal answers 400 with Discord's own words: discord.webhookGone when Discord no longer knows the webhook (which also marks it), discord.rateLimited, discord.rejected or discord.sendFailed. discord.webhookUnreadable means the stored URL cannot be decrypted any more. Rate limited to 10 calls per five minutes per client. Administrators only.
 * @summary Send a test message to the Discord channel
 */
export const SendTestDiscordResponse = zod.void();

/**
 * Administrators only. Returns the rates of one currency in units per euro, newest first: every rate synced from the ECB in the last 30 days and every rate an administrator entered by hand, whatever its date. A date with both shows the hand-entered rate, which wins, with the synced one beside it.
 * @summary List the stored exchange rates of a currency
 */
export const exchangeRateEntriesResponseRateRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const exchangeRateEntriesResponseSyncedRateRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ExchangeRateEntriesResponseItem = zod.object({
  date: zod.iso.date(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  rate: zod.stringFormat("decimal", exchangeRateEntriesResponseRateRegExp),
  source: zod.enum(["ecb", "manual"]),
  syncedRate: zod.stringFormat("decimal", exchangeRateEntriesResponseSyncedRateRegExp).nullable(),
});
export const ExchangeRateEntriesResponse = zod.array(ExchangeRateEntriesResponseItem);

/**
 * Administrators only. Fetches reference rates published since the newest stored date. It works even when automatic sync is turned off.
 * @summary Fetch exchange rates now
 */
export const SyncExchangeRatesResponse = zod.object({
  added: zod.int(),
  ratesAsOf: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Administrators only. Removes the rate entered by hand for a currency and date, so the synced ECB rate of that date, or else the newest stored rate before it, applies again. The rows that depended on it are valued again in the same way as when the rate was entered; when one of them would be left without a rate nothing is deleted. Synced rates cannot be deleted.
 * @summary Delete an exchange rate entered by hand
 */
export const DeleteExchangeRateResponse = zod.void();

/**
 * Administrators only. Stores the rate of a currency for one date, in units per euro, replacing one entered for the same date before. A rate entered by hand wins over the synced ECB rate of the same date and, like any rate, applies until the next stored rate of that currency. In the same database transaction every transaction and investment entry dated from that date up to the day before the next stored rate, and not after today, whose reporting value depends on the currency is valued again; when one of them cannot be valued nothing is saved.
 * @summary Enter an exchange rate by hand
 */
export const setExchangeRateBodyRateRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const SetExchangeRateBody = zod.object({
  rate: zod.stringFormat("decimal", setExchangeRateBodyRateRegExp),
});

export const setExchangeRateResponseRateRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const setExchangeRateResponseSyncedRateRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const SetExchangeRateResponse = zod.object({
  date: zod.iso.date(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  rate: zod.stringFormat("decimal", setExchangeRateResponseRateRegExp),
  source: zod.enum(["ecb", "manual"]),
  syncedRate: zod.stringFormat("decimal", setExchangeRateResponseSyncedRateRegExp).nullable(),
});

/**
 * Answers whether closing prices are fetched daily, whether an EODHD API key is saved (never the key itself), when the last fetch ran, how many EODHD calls are left today, and the securities whose last fetch failed with the reason. Administrators only.
 * @summary Read the market price settings of this installation
 */
export const MarketPriceSettingsResponse = zod.object({
  enabled: zod.boolean(),
  hasKey: zod.boolean(),
  lastRunAt: zod.iso.datetime({ offset: true }).nullable(),
  callsLeft: zod.int(),
  failures: zod.array(
    zod.object({
      securityId: zod.uuid(),
      symbol: zod.string(),
      name: zod.string(),
      reason: zod.string(),
      at: zod.iso.datetime({ offset: true }),
    }),
  ),
});

/**
 * Switches the daily fetch of closing prices on or off and saves, keeps or removes the EODHD API key. The key is encrypted with ASP.NET Data Protection before it is stored and is never returned: the response carries hasKey instead. While the switch is off the server makes no request to a price provider on its own. Administrators only.
 * @summary Save the market price settings of this installation
 */
export const updateMarketPriceSettingsBodyEodhdApiKeyMin = 0;
export const updateMarketPriceSettingsBodyEodhdApiKeyMax = 200;

export const UpdateMarketPriceSettingsBody = zod.object({
  enabled: zod.boolean(),
  eodhdApiKey: zod
    .string()
    .min(updateMarketPriceSettingsBodyEodhdApiKeyMin)
    .max(updateMarketPriceSettingsBodyEodhdApiKeyMax)
    .nullish()
    .describe("Null keeps the saved key, an empty string removes it, anything else replaces it."),
});

export const UpdateMarketPriceSettingsResponse = zod.object({
  enabled: zod.boolean(),
  hasKey: zod.boolean(),
  lastRunAt: zod.iso.datetime({ offset: true }).nullable(),
  callsLeft: zod.int(),
  failures: zod.array(
    zod.object({
      securityId: zod.uuid(),
      symbol: zod.string(),
      name: zod.string(),
      reason: zod.string(),
      at: zod.iso.datetime({ offset: true }),
    }),
  ),
});

/**
 * Fetches the missing closing prices of every held security that has a price source, as the daily run does, including securities whose last fetch failed less than a day ago. Works whether or not the daily fetch is switched on. EODHD calls count against the daily limit. Administrators only.
 * @summary Fetch closing prices now
 */
export const SyncMarketPricesResponse = zod.object({
  checked: zod.int(),
  written: zod.int(),
  failed: zod.int(),
  callsLeft: zod.int(),
});

/**
 * Anonymous. Returns only the installation name, the default language, whether this installation can send email, which is what decides if the sign-in page offers "Forgot password", and whether the installation's Discord channel and Telegram group are set up, which decide the profile's notification columns, and whether passkeys can work here, which is false when the configured site address is plain HTTP or an IP address. No host name, no address and no credential is part of the answer.
 * @summary Read the settings the sign-in page needs
 */
export const PublicSettingsResponse = zod.object({
  instanceName: zod.string().nullable(),
  defaultLanguage: zod.string(),
  emailEnabled: zod.boolean(),
  discordEnabled: zod.boolean(),
  telegramEnabled: zod.boolean(),
  passkeysAvailable: zod.boolean(),
});

/**
 * Answers the SMTP host, port, encryption mode, user name, sender address and sender name, plus the enabled switch. The password is never part of the answer; hasPassword says only whether one is stored. Administrators only, unlike GET /api/settings, because these values describe an outside system.
 * @summary Read the mail server of this installation
 */
export const SmtpSettingsResponse = zod.object({
  enabled: zod.boolean(),
  host: zod.string().nullable(),
  port: zod.int(),
  encryption: zod
    .enum(["startTls", "sslOnConnect", "none"])
    .describe(
      "startTls (the default, usually port 587; the server must offer STARTTLS), sslOnConnect (usually port 465) or none, which is only accepted without a user name.",
    ),
  userName: zod.string().nullable(),
  hasPassword: zod.boolean(),
  fromAddress: zod.string().nullable(),
  fromName: zod.string().nullable(),
});

/**
 * Stores the SMTP host, port, encryption mode, optional user name and password, and the sender address and name, on the single installation settings row. The password is encrypted with ASP.NET Data Protection before it is stored and is never returned: the response carries hasPassword instead. Leaving password empty keeps the stored one, but only while the host and the user name stay the same: changing either without a new password answers 400 email.passwordRequired, so a saved password is never sent to another server or account. Clearing the user name clears the stored password with it, because an anonymous relay has nothing to authenticate. A user name needs startTls or sslOnConnect: none with a user name answers 400 email.insecureConnection, because credentials are never sent in plain text. Switching enabled on needs a host and a sender address. Administrators only.
 * @summary Save the mail server of this installation
 */
export const updateSmtpSettingsBodyHostMin = 0;
export const updateSmtpSettingsBodyHostMax = 255;

export const updateSmtpSettingsBodyPortMax = 65535;

export const updateSmtpSettingsBodyUserNameMin = 0;
export const updateSmtpSettingsBodyUserNameMax = 255;

export const updateSmtpSettingsBodyPasswordMin = 0;
export const updateSmtpSettingsBodyPasswordMax = 255;

export const updateSmtpSettingsBodyFromAddressMin = 0;
export const updateSmtpSettingsBodyFromAddressMax = 320;

export const updateSmtpSettingsBodyFromAddressRegExp = new RegExp("^[^@]+@[^@]+$");
export const updateSmtpSettingsBodyFromNameMin = 0;
export const updateSmtpSettingsBodyFromNameMax = 100;

export const UpdateSmtpSettingsBody = zod.object({
  enabled: zod.boolean(),
  host: zod
    .string()
    .min(updateSmtpSettingsBodyHostMin)
    .max(updateSmtpSettingsBodyHostMax)
    .nullable(),
  port: zod.int().min(1).max(updateSmtpSettingsBodyPortMax),
  encryption: zod
    .enum(["startTls", "sslOnConnect", "none"])
    .describe(
      "startTls (the default, usually port 587; the server must offer STARTTLS), sslOnConnect (usually port 465) or none, which is only accepted without a user name.",
    ),
  userName: zod
    .string()
    .min(updateSmtpSettingsBodyUserNameMin)
    .max(updateSmtpSettingsBodyUserNameMax)
    .nullable(),
  password: zod
    .string()
    .min(updateSmtpSettingsBodyPasswordMin)
    .max(updateSmtpSettingsBodyPasswordMax)
    .nullable()
    .describe(
      "Leave empty to keep the stored password; required when the host or user name changes.",
    ),
  fromAddress: zod
    .email()
    .min(updateSmtpSettingsBodyFromAddressMin)
    .max(updateSmtpSettingsBodyFromAddressMax)
    .regex(updateSmtpSettingsBodyFromAddressRegExp)
    .nullable(),
  fromName: zod
    .string()
    .min(updateSmtpSettingsBodyFromNameMin)
    .max(updateSmtpSettingsBodyFromNameMax)
    .nullable(),
});

export const UpdateSmtpSettingsResponse = zod.object({
  enabled: zod.boolean(),
  host: zod.string().nullable(),
  port: zod.int(),
  encryption: zod
    .enum(["startTls", "sslOnConnect", "none"])
    .describe(
      "startTls (the default, usually port 587; the server must offer STARTTLS), sslOnConnect (usually port 465) or none, which is only accepted without a user name.",
    ),
  userName: zod.string().nullable(),
  hasPassword: zod.boolean(),
  fromAddress: zod.string().nullable(),
  fromName: zod.string().nullable(),
});

/**
 * Sends one short message to the calling administrator's own address with the settings that are stored right now, and waits for the mail server to accept it. Nothing is written: the message does not go through the outbox and leaves no row behind, so a failed attempt is not retried. Success answers the address the message went to; a refusal answers 400 with email.sendFailed and the mail server's own words, email.notConfigured when the settings are incomplete or switched off, or email.passwordUnreadable when the stored password cannot be decrypted, which is what a restore into an installation with different data protection keys leaves behind. The attempt gives up after the configured send timeout, so a dead server cannot hold the request open. Save the settings before testing them. Rate limited to 10 calls per five minutes per client.
 * @summary Send a test message
 */
export const SendTestEmailResponse = zod.object({
  sentTo: zod.string(),
});

/**
 * Answers whether Telegram is switched on, whether a bot token is saved, the group's chat id, when a message last reached it and the last error. The bot token is never part of the answer, because anyone holding it controls the bot. disabledByTelegram is true after Telegram answered that the bot was removed from the group or its token was revoked; unreadable is true when the stored token cannot be decrypted, which a restore into an installation with other data protection keys leaves behind. Administrators only.
 * @summary Read the installation's Telegram group
 */
export const TelegramSettingsResponse = zod.object({
  enabled: zod.boolean(),
  hasToken: zod.boolean(),
  chatId: zod.int().nullable(),
  lastDeliveredAt: zod.iso.datetime({ offset: true }).nullable(),
  lastError: zod.string().nullable(),
  disabledByTelegram: zod.boolean(),
  unreadable: zod.boolean(),
});

/**
 * Stores the bot token and the id of the one Telegram group this installation posts to, and switches outbound Telegram traffic on or off for everyone. Members then choose on their profile which of their notifications are posted there, with their name in front. The token must be the one @BotFather gave, of the form 123456789:AAE…, or the answer is 400 telegram.invalidToken; the chat id is a whole number, negative for a group, and 0 answers telegram.invalidChat. Switching Telegram on without a saved token answers telegram.invalidToken and without a chat id telegram.invalidChat. The token is encrypted before it is stored and never returned. Leaving botToken empty keeps the stored one; a new token or a new chat id clears the mark Telegram left on a bot it refused. While Telegram is off nothing is queued or sent; messages that were already queued are not sent late but pruned after seven days. Administrators only.
 * @summary Save the installation's Telegram group
 */
export const UpdateTelegramSettingsBody = zod.object({
  enabled: zod.boolean(),
  botToken: zod.string().nullable().describe("Leave empty to keep the stored token."),
  chatId: zod.int().nullable().describe("The group's id; null removes it."),
});

export const UpdateTelegramSettingsResponse = zod.object({
  enabled: zod.boolean(),
  hasToken: zod.boolean(),
  chatId: zod.int().nullable(),
  lastDeliveredAt: zod.iso.datetime({ offset: true }).nullable(),
  lastError: zod.string().nullable(),
  disabledByTelegram: zod.boolean(),
  unreadable: zod.boolean(),
});

/**
 * Posts one short message to the saved group right away and waits for Telegram's answer, even while Telegram is switched off, so the group can be checked before members use it. Nothing is queued, so a failure is not retried. When Telegram says the group became a supergroup with a new id, the new id is saved and the message sent again. A refusal answers 400 with Telegram's own words: telegram.botRemoved when the bot was removed from the group or its token revoked (which also marks it), telegram.rateLimited, telegram.rejected or telegram.sendFailed. telegram.tokenUnreadable means the stored token cannot be decrypted any more. Rate limited to 10 calls per five minutes per client. Administrators only.
 * @summary Send a test message to the Telegram group
 */
export const SendTestTelegramResponse = zod.void();
