/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Returns expenses for one month grouped by category, ordered by amount, for the dashboard pie chart. Split transactions contribute to each of their lines separately. While the investments feature is on, withholding tax and standalone fees from the investment ledger arrive as one entry with categoryId null and syntheticGroup investmentTaxesAndFees; localize its name and do not link it to a category. Every other entry has syntheticGroup null.
 * @summary Get spending split by category
 */
export const categoryBreakdownResponseItemsItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const categoryBreakdownResponseItemsItemComparisonAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const CategoryBreakdownResponse = zod.object({
  items: zod.array(
    zod.object({
      categoryId: zod.uuid().nullable(),
      categoryName: zod.string(),
      categoryIcon: zod.string().nullable(),
      amount: zod.stringFormat("decimal", categoryBreakdownResponseItemsItemAmountRegExp),
      syntheticGroup: zod
        .union([zod.null(), zod.enum(["investmentIncome", "investmentTaxesAndFees"])])
        .optional(),
      comparisonAmount: zod
        .stringFormat("decimal", categoryBreakdownResponseItemsItemComparisonAmountRegExp)
        .nullish(),
    }),
  ),
  periodStart: zod.iso.date(),
  periodEnd: zod.iso.date(),
});

/**
 * Returns income and expense totals per month, oldest first, ending with the current month. Months with no activity are still present with zero totals so the chart keeps an even x-axis. While the investments feature is on, the totals include investment dividends and interest as income and withholding tax and standalone fees as expense.
 * @summary Get the monthly income and expense trend
 */
export const monthlyTrendResponseItemsItemIncomeRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const monthlyTrendResponseItemsItemExpenseRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const MonthlyTrendResponse = zod.object({
  items: zod.array(
    zod.object({
      year: zod.int(),
      month: zod.int(),
      income: zod.stringFormat("decimal", monthlyTrendResponseItemsItemIncomeRegExp),
      expense: zod.stringFormat("decimal", monthlyTrendResponseItemsItemExpenseRegExp),
    }),
  ),
});

/**
 * Returns the headline figures for the current month: total balance across all visible accounts, income and expenses so far, and the resulting net flow. The month is resolved in the instance time zone, not the caller's. While the investments feature is on, income includes dividends and interest from the investment ledger and expenses include withholding tax and standalone fees, exactly as in the report summary.
 * @summary Get the dashboard summary
 */
export const dashboardSummaryResponseTotalBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const dashboardSummaryResponseMonthIncomeRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const dashboardSummaryResponseMonthExpenseRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const DashboardSummaryResponse = zod.object({
  totalBalance: zod.stringFormat("decimal", dashboardSummaryResponseTotalBalanceRegExp),
  monthIncome: zod.stringFormat("decimal", dashboardSummaryResponseMonthIncomeRegExp),
  monthExpense: zod.stringFormat("decimal", dashboardSummaryResponseMonthExpenseRegExp),
  monthStart: zod.iso.date(),
  monthEnd: zod.iso.date(),
});
