/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Returns expenses for one month grouped by category, ordered by amount, for the dashboard pie chart. Split transactions contribute to each of their lines separately.
 * @summary Get spending split by category
 */
export const GetCategoryBreakdownQueryParams = zod.object({
  month: zod
    .string()
    .nullish()
    .describe("Month to report on as YYYY-MM. Defaults to the current month."),
});

export const GetCategoryBreakdownResponse = zod.object({
  items: zod.array(
    zod.object({
      categoryId: zod.uuid().nullable(),
      categoryName: zod.string(),
      categoryIcon: zod.string().nullable(),
      amount: zod.string(),
    }),
  ),
  periodStart: zod.iso.date(),
  periodEnd: zod.iso.date(),
});

/**
 * Returns income and expense totals per month, oldest first, ending with the current month. Months with no activity are still present with zero totals so the chart keeps an even x-axis.
 * @summary Get the monthly income and expense trend
 */
export const GetMonthlyTrendQueryParams = zod.object({
  months: zod
    .int()
    .describe("How many months to include, counting back from the current one. Defaults to 6."),
});

export const GetMonthlyTrendResponse = zod.object({
  items: zod.array(
    zod.object({
      year: zod.int(),
      month: zod.int(),
      income: zod.string(),
      expense: zod.string(),
    }),
  ),
});

/**
 * Returns the headline figures for the current month: total balance across all visible accounts, income and expenses so far, and the resulting net flow. The month is resolved in the instance time zone, not the caller's.
 * @summary Get the dashboard summary
 */
export const GetDashboardSummaryResponse = zod.object({
  totalBalance: zod.string(),
  monthIncome: zod.string(),
  monthExpense: zod.string(),
  monthStart: zod.iso.date(),
  monthEnd: zod.iso.date(),
});
