import { readFileSync, writeFileSync } from "node:fs";
import { defineConfig } from "orval";

const input = "./openapi.json";
const format = "oxfmt";
const decimalFieldsFile = "./src/api/generated/decimal-fields.ts";

interface SchemaNode {
  $ref?: string;
  format?: string;
  properties?: Record<string, SchemaNode>;
  items?: SchemaNode;
  oneOf?: SchemaNode[];
}

interface Operation {
  requestBody?: { content?: Record<string, { schema?: SchemaNode }> };
}

interface SpecDocument {
  paths: Record<string, Record<string, Operation>>;
  components: { schemas: Record<string, SchemaNode> };
}

function writeDecimalFields() {
  const document = JSON.parse(readFileSync(input, "utf8")) as SpecDocument;
  const names = new Set<string>();
  const visited = new Set<string>();

  function collect(node: SchemaNode | undefined) {
    if (!node) {
      return;
    }
    if (node.$ref) {
      const name = node.$ref.split("/").at(-1) ?? "";
      if (!visited.has(name)) {
        visited.add(name);
        collect(document.components.schemas[name]);
      }
      return;
    }
    for (const [name, property] of Object.entries(node.properties ?? {})) {
      if (property.format === "decimal") {
        names.add(name);
      }
      collect(property);
    }
    collect(node.items);
    for (const variant of node.oneOf ?? []) {
      collect(variant);
    }
  }

  for (const operations of Object.values(document.paths)) {
    for (const operation of Object.values(operations)) {
      for (const media of Object.values(operation.requestBody?.content ?? {})) {
        collect(media.schema);
      }
    }
  }

  const lines = [...names].toSorted().map((name) => `  "${name}",`);
  writeFileSync(
    decimalFieldsFile,
    [
      "/**",
      " * Generated by orval.config.ts from every `format: decimal` request body property in the OpenAPI spec.",
      " * Do not edit manually.",
      " */",
      "export const decimalFields: ReadonlySet<string> = new Set([",
      ...lines,
      "]);",
      "",
    ].join("\n"),
  );
}

const plainQueryOperations = [
  "GetCurrencies",
  "GetExchangeRate",
  "GetPublicSettings",
  "GetSecurities",
  "GetSettings",
  "GetTransfers",
  "Me",
];

function operationName(operation: { operationId?: string }, _route: string, verb: string) {
  const id = operation.operationId ?? "";
  const name = verb === "get" && /^Get[A-Z]/.test(id) ? id.slice(3) : id;
  return name.charAt(0).toLowerCase() + name.slice(1);
}

const decimalPattern = "^-?\\d+(\\.\\d{1,8})?$";

function describeDecimals(node: unknown) {
  if (Array.isArray(node)) {
    for (const item of node) {
      describeDecimals(item);
    }
    return;
  }
  if (typeof node !== "object" || node === null) {
    return;
  }
  const schema = node as Record<string, unknown>;
  if (schema.format === "decimal" && schema.pattern === undefined) {
    schema.pattern = decimalPattern;
  }
  for (const value of Object.values(schema)) {
    describeDecimals(value);
  }
}

function forValidation<TDocument extends { paths?: object; components?: object }>(
  document: TDocument,
): TDocument {
  const spec = structuredClone(document);
  describeDecimals(spec.components);
  spec.paths = {
    ...spec.paths,
    "/__contract/problem-details": {
      get: {
        operationId: "GetProblemDetails",
        tags: ["Problems"],
        responses: {
          "200": {
            description: "Shape of every application/problem+json failure body.",
            content: {
              "application/json": { schema: { $ref: "#/components/schemas/ProblemDetails" } },
            },
          },
        },
      },
    },
  };
  return spec;
}

export default defineConfig({
  api: {
    input,
    output: {
      mode: "tags-split",
      client: "react-query",
      clean: true,
      target: "./src/api/generated",
      schemas: "./src/api/generated/model",
      mock: {
        generators: [{ type: "msw", baseUrl: "*", delay: false, operationResponses: false }],
      },
      override: {
        operationName,
        query: {
          useQuery: false,
          useSuspenseQuery: true,
          signal: true,
        },
        operations: Object.fromEntries(
          plainQueryOperations.map((id) => [id, { query: { useQuery: true } }]),
        ),
        mutator: {
          path: "./src/api/client.ts",
          name: "customFetch",
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
      },
    },
    hooks: {
      afterAllFilesWrite: [writeDecimalFields, format],
    },
  },
  zod: {
    input: { target: input, override: { transformer: forValidation } },
    output: {
      mode: "tags-split",
      client: "zod",
      clean: true,
      target: "./src/api/schemas",
      fileExtension: ".zod.ts",
      override: {
        operationName,
        zod: {
          generate: { param: false, query: false, header: false, body: true, response: true },
        },
      },
    },
    hooks: {
      afterAllFilesWrite: format,
    },
  },
});
