/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Schedules a bill or a recurring income. Nothing is posted to the ledger on a schedule: the background job raises a reminder before the due date, and a transaction is only written once the occurrence is confirmed.
 * @summary Create a recurring bill
 */
export const createRecurringBillBodyNameMin = 0;
export const createRecurringBillBodyNameMax = 100;

export const createRecurringBillBodyRemindDaysBeforeMin = 0;
export const createRecurringBillBodyRemindDaysBeforeMax = 365;

export const CreateRecurringBillBody = zod.object({
  name: zod.string().min(createRecurringBillBodyNameMin).max(createRecurringBillBodyNameMax),
  kind: zod
    .enum(["fixed", "variable"])
    .describe("Fixed when the amount is always the same; Variable when it changes each time."),
  amount: zod
    .string()
    .nullable()
    .describe("Expected amount. Required for a Fixed bill, optional for a Variable one."),
  categoryId: zod.uuid().nullable(),
  accountId: zod.uuid().nullable(),
  cadence: zod
    .enum(["weekly", "monthly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly."),
  nextDueDate: zod.iso.date(),
  remindDaysBefore: zod
    .int()
    .min(createRecurringBillBodyRemindDaysBeforeMin)
    .max(createRecurringBillBodyRemindDaysBeforeMax)
    .describe("How many days ahead of the due date to raise a notification."),
});

export const CreateRecurringBillResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  kind: zod
    .enum(["fixed", "variable"])
    .describe("Fixed when the amount is always the same; Variable when it changes each time."),
  amount: zod.string().nullable(),
  categoryId: zod.uuid().nullable(),
  accountId: zod.uuid().nullable(),
  cadence: zod
    .enum(["weekly", "monthly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly."),
  nextDueDate: zod.iso.date(),
  remindDaysBefore: zod.int(),
  isActive: zod.boolean(),
});

/**
 * Returns your scheduled bills and income, each with its cadence and the date it next falls due. Inactive schedules are included so they can be reactivated.
 * @summary List recurring bills
 */
export const GetRecurringBillsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  kind: zod
    .enum(["fixed", "variable"])
    .describe("Fixed when the amount is always the same; Variable when it changes each time."),
  amount: zod.string().nullable(),
  categoryId: zod.uuid().nullable(),
  accountId: zod.uuid().nullable(),
  cadence: zod
    .enum(["weekly", "monthly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly."),
  nextDueDate: zod.iso.date(),
  remindDaysBefore: zod.int(),
  isActive: zod.boolean(),
});
export const GetRecurringBillsResponse = zod.array(GetRecurringBillsResponseItem);

/**
 * Removes the schedule and its reminders. Transactions already posted from it stay in the ledger.
 * @summary Delete a recurring bill
 */
export const DeleteRecurringBillParams = zod.object({
  id: zod.string().describe("The recurring bill id."),
});

export const DeleteRecurringBillResponse = zod.void();

/**
 * Returns a single schedule with its cadence, reminder lead time, and next due date.
 * @summary Get one recurring bill
 */
export const GetRecurringBillParams = zod.object({
  id: zod.string().describe("The recurring bill id."),
});

export const GetRecurringBillResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  kind: zod
    .enum(["fixed", "variable"])
    .describe("Fixed when the amount is always the same; Variable when it changes each time."),
  amount: zod.string().nullable(),
  categoryId: zod.uuid().nullable(),
  accountId: zod.uuid().nullable(),
  cadence: zod
    .enum(["weekly", "monthly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly."),
  nextDueDate: zod.iso.date(),
  remindDaysBefore: zod.int(),
  isActive: zod.boolean(),
});

/**
 * Changes the schedule, the expected amount, or the reminder lead time. Setting isActive to false stops reminders without losing the schedule or the transactions already posted from it.
 * @summary Update a recurring bill
 */
export const UpdateRecurringBillParams = zod.object({
  id: zod.uuid().describe("The recurring bill id. Takes precedence over the id in the body."),
});

export const updateRecurringBillBodyNameMin = 0;
export const updateRecurringBillBodyNameMax = 100;

export const updateRecurringBillBodyRemindDaysBeforeMin = 0;
export const updateRecurringBillBodyRemindDaysBeforeMax = 365;

export const UpdateRecurringBillBody = zod.object({
  name: zod.string().min(updateRecurringBillBodyNameMin).max(updateRecurringBillBodyNameMax),
  kind: zod
    .enum(["fixed", "variable"])
    .describe("Fixed when the amount is always the same; Variable when it changes each time."),
  amount: zod.string().nullable(),
  categoryId: zod.uuid().nullable(),
  accountId: zod.uuid().nullable(),
  cadence: zod
    .enum(["weekly", "monthly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly."),
  nextDueDate: zod.iso.date(),
  remindDaysBefore: zod
    .int()
    .min(updateRecurringBillBodyRemindDaysBeforeMin)
    .max(updateRecurringBillBodyRemindDaysBeforeMax),
  isActive: zod.boolean(),
});

export const UpdateRecurringBillResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  kind: zod
    .enum(["fixed", "variable"])
    .describe("Fixed when the amount is always the same; Variable when it changes each time."),
  amount: zod.string().nullable(),
  categoryId: zod.uuid().nullable(),
  accountId: zod.uuid().nullable(),
  cadence: zod
    .enum(["weekly", "monthly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly."),
  nextDueDate: zod.iso.date(),
  remindDaysBefore: zod.int(),
  isActive: zod.boolean(),
});

/**
 * Posts the transaction for one occurrence of the schedule and rolls the next due date forward by the cadence. expectedDueDate identifies which occurrence is being confirmed, so a retry or a double click cannot post the same bill twice.
 * @summary Confirm a due occurrence
 */
export const ConfirmRecurringBillParams = zod.object({
  id: zod.uuid().describe("The recurring bill id. Takes precedence over the id in the body."),
});

export const ConfirmRecurringBillBody = zod.object({
  amount: zod
    .string()
    .nullable()
    .describe(
      "Actual amount. Required for a Variable bill; defaults to the scheduled amount for a Fixed one.",
    ),
  accountId: zod
    .uuid()
    .nullable()
    .describe("Account to post to. Defaults to the account on the schedule."),
  expectedDueDate: zod.iso.date(),
});

export const ConfirmRecurringBillResponse = zod.object({
  bill: zod.object({
    id: zod.uuid(),
    name: zod.string(),
    kind: zod
      .enum(["fixed", "variable"])
      .describe("Fixed when the amount is always the same; Variable when it changes each time."),
    amount: zod.string().nullable(),
    categoryId: zod.uuid().nullable(),
    accountId: zod.uuid().nullable(),
    cadence: zod
      .enum(["weekly", "monthly", "quarterly", "yearly"])
      .describe("Weekly, Monthly, Quarterly, or Yearly."),
    nextDueDate: zod.iso.date(),
    remindDaysBefore: zod.int(),
    isActive: zod.boolean(),
  }),
  transactionId: zod.uuid(),
});
