/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Starts tracking something of value that is not an account balance. Its value counts towards net worth from the as-of date onwards. The asset is kept in the reporting currency of the day it is created, and later edits keep that currency. The value and date become its first valuation.
 * @summary Add an asset
 */
export const createAssetBodyNameMin = 0;
export const createAssetBodyNameMax = 100;

export const createAssetBodyCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createAssetBodyDepreciationTwoStartValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createAssetBodyDepreciationTwoResidualValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const CreateAssetBody = zod.object({
  name: zod.string().min(createAssetBodyNameMin).max(createAssetBodyNameMax),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod
    .stringFormat("decimal", createAssetBodyCurrentValueRegExp)
    .describe("Decimal string with at most two decimal places."),
  asOf: zod.iso.date(),
  depreciation: zod
    .union([
      zod.null(),
      zod.object({
        startDate: zod.union([zod.null(), zod.iso.date()]),
        startValue: zod
          .stringFormat("decimal", createAssetBodyDepreciationTwoStartValueRegExp)
          .nullable(),
        lifeMonths: zod.int().nullable(),
        residualValue: zod
          .stringFormat("decimal", createAssetBodyDepreciationTwoResidualValueRegExp)
          .nullable(),
      }),
    ])
    .optional()
    .describe(
      "Optional straight-line depreciation: startDate (not in the future), startValue, lifeMonths (1 to 600) and residualValue (0 or more, below the start value). Give all four or leave it out (asset.depreciationIncomplete). The value falls by (startValue - residualValue) / lifeMonths, rounded up to the cent, on the start date's day of each month and never below the residual value.",
    ),
  scope: zod.enum(["personal", "shared"]).optional(),
  householdId: zod.uuid().nullish(),
});

export const createAssetResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createAssetResponseValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createAssetResponseDepreciationTwoStartValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const createAssetResponseDepreciationTwoResidualValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const createAssetResponseMonthlyDepreciationRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateAssetResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", createAssetResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  value: zod.stringFormat("decimal", createAssetResponseValueRegExp),
  depreciation: zod.union([
    zod.null(),
    zod.object({
      startDate: zod.iso.date(),
      startValue: zod.stringFormat("decimal", createAssetResponseDepreciationTwoStartValueRegExp),
      lifeMonths: zod.int(),
      residualValue: zod.stringFormat(
        "decimal",
        createAssetResponseDepreciationTwoResidualValueRegExp,
      ),
    }),
  ]),
  monthlyDepreciation: zod
    .stringFormat("decimal", createAssetResponseMonthlyDepreciationRegExp)
    .nullable(),
  fullyDepreciatedOn: zod.union([zod.null(), zod.iso.date()]),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Returns the assets you track outside the ledger, such as property or vehicles, each with its latest valuation, the date that valuation is as of, and its value today, which is lower than the latest valuation when the asset depreciates.
 * @summary List assets
 */
export const assetsResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const assetsResponseValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const assetsResponseDepreciationTwoStartValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const assetsResponseDepreciationTwoResidualValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const assetsResponseMonthlyDepreciationRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const AssetsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", assetsResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  value: zod.stringFormat("decimal", assetsResponseValueRegExp),
  depreciation: zod.union([
    zod.null(),
    zod.object({
      startDate: zod.iso.date(),
      startValue: zod.stringFormat("decimal", assetsResponseDepreciationTwoStartValueRegExp),
      lifeMonths: zod.int(),
      residualValue: zod.stringFormat("decimal", assetsResponseDepreciationTwoResidualValueRegExp),
    }),
  ]),
  monthlyDepreciation: zod
    .stringFormat("decimal", assetsResponseMonthlyDepreciationRegExp)
    .nullable(),
  fullyDepreciatedOn: zod.union([zod.null(), zod.iso.date()]),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});
export const AssetsResponse = zod.array(AssetsResponseItem);

/**
 * Stops tracking the asset. Snapshots already recorded keep the value it had.
 * @summary Delete an asset
 */
export const DeleteAssetResponse = zod.void();

/**
 * Revalues, renames or sets the depreciation of an asset. A changed value or date records a valuation for that date instead of overwriting the history. Net worth uses the new value from the next read onwards; snapshots already taken keep the value that was current when they were written.
 * @summary Update an asset
 */
export const updateAssetBodyNameMin = 0;
export const updateAssetBodyNameMax = 100;

export const updateAssetBodyCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateAssetBodyDepreciationTwoStartValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateAssetBodyDepreciationTwoResidualValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const UpdateAssetBody = zod.object({
  name: zod.string().min(updateAssetBodyNameMin).max(updateAssetBodyNameMax),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", updateAssetBodyCurrentValueRegExp),
  asOf: zod.iso.date(),
  depreciation: zod
    .union([
      zod.null(),
      zod.object({
        startDate: zod.union([zod.null(), zod.iso.date()]),
        startValue: zod
          .stringFormat("decimal", updateAssetBodyDepreciationTwoStartValueRegExp)
          .nullable(),
        lifeMonths: zod.int().nullable(),
        residualValue: zod
          .stringFormat("decimal", updateAssetBodyDepreciationTwoResidualValueRegExp)
          .nullable(),
      }),
    ])
    .optional()
    .describe(
      "Optional straight-line depreciation: startDate (not in the future), startValue, lifeMonths (1 to 600) and residualValue (0 or more, below the start value). Give all four or leave it out (asset.depreciationIncomplete). The value falls by (startValue - residualValue) / lifeMonths, rounded up to the cent, on the start date's day of each month and never below the residual value.",
    ),
  scope: zod.enum(["personal", "shared"]).optional(),
  householdId: zod.uuid().nullish(),
});

export const updateAssetResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateAssetResponseValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateAssetResponseDepreciationTwoStartValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const updateAssetResponseDepreciationTwoResidualValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const updateAssetResponseMonthlyDepreciationRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateAssetResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", updateAssetResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  value: zod.stringFormat("decimal", updateAssetResponseValueRegExp),
  depreciation: zod.union([
    zod.null(),
    zod.object({
      startDate: zod.iso.date(),
      startValue: zod.stringFormat("decimal", updateAssetResponseDepreciationTwoStartValueRegExp),
      lifeMonths: zod.int(),
      residualValue: zod.stringFormat(
        "decimal",
        updateAssetResponseDepreciationTwoResidualValueRegExp,
      ),
    }),
  ]),
  monthlyDepreciation: zod
    .stringFormat("decimal", updateAssetResponseMonthlyDepreciationRegExp)
    .nullable(),
  fullyDepreciatedOn: zod.union([zod.null(), zod.iso.date()]),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Returns the dated valuations of an asset, newest first. Each is a value set by hand for one date, in the currency of the asset. Depreciation writes no valuations: it is computed from them on every read.
 * @summary List the valuations of an asset
 */
export const assetValuationsResponseValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const AssetValuationsResponseItem = zod.object({
  date: zod.iso.date(),
  value: zod.stringFormat("decimal", assetValuationsResponseValueRegExp),
  note: zod.string().nullable(),
});
export const AssetValuationsResponse = zod.array(AssetValuationsResponseItem);

/**
 * Removes the valuation recorded for one date for good; it does not go to the trash. The current value of the asset becomes the newest remaining valuation. The last valuation cannot be deleted.
 * @summary Delete a valuation of an asset
 */
export const DeleteAssetValuationResponse = zod.void();

/**
 * Records what the asset was worth on one date, replacing a valuation already recorded for that date. The current value and as-of date of the asset follow the newest valuation, so a valuation for an earlier date only adds history. On a depreciating asset a valuation on or after the start date restarts the decline from that value at the same monthly amount. Net worth snapshots already taken are not rewritten.
 * @summary Record a valuation of an asset
 */
export const setAssetValuationBodyValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const setAssetValuationBodyNoteMin = 0;
export const setAssetValuationBodyNoteMax = 200;

export const SetAssetValuationBody = zod.object({
  value: zod
    .stringFormat("decimal", setAssetValuationBodyValueRegExp)
    .describe("Decimal string with at most two decimal places, in the currency of the asset."),
  note: zod
    .string()
    .min(setAssetValuationBodyNoteMin)
    .max(setAssetValuationBodyNoteMax)
    .nullish()
    .describe('Optional, up to 200 characters, such as "dealer quote".'),
});

export const setAssetValuationResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const setAssetValuationResponseValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const setAssetValuationResponseDepreciationTwoStartValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const setAssetValuationResponseDepreciationTwoResidualValueRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const setAssetValuationResponseMonthlyDepreciationRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const SetAssetValuationResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", setAssetValuationResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  value: zod.stringFormat("decimal", setAssetValuationResponseValueRegExp),
  depreciation: zod.union([
    zod.null(),
    zod.object({
      startDate: zod.iso.date(),
      startValue: zod.stringFormat(
        "decimal",
        setAssetValuationResponseDepreciationTwoStartValueRegExp,
      ),
      lifeMonths: zod.int(),
      residualValue: zod.stringFormat(
        "decimal",
        setAssetValuationResponseDepreciationTwoResidualValueRegExp,
      ),
    }),
  ]),
  monthlyDepreciation: zod
    .stringFormat("decimal", setAssetValuationResponseMonthlyDepreciationRegExp)
    .nullable(),
  fullyDepreciatedOn: zod.union([zod.null(), zod.iso.date()]),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Returns the value of an asset for a series of dates, in its own currency. Nothing is stored: each value is the latest valuation on or before the date, less the straight-line depreciation since then when the asset depreciates. The series is daily for ranges up to about three months, weekly up to two years and monthly beyond, always ends on the last date of the range, and also holds every valuation date in the range, marked with isValuation. Dates before the first valuation have no point.
 * @summary Get the value of an asset over time
 */
export const assetValueHistoryResponsePointsItemValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const AssetValueHistoryResponse = zod.object({
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  points: zod.array(
    zod.object({
      date: zod.iso.date(),
      value: zod.stringFormat("decimal", assetValueHistoryResponsePointsItemValueRegExp),
      isValuation: zod.boolean(),
    }),
  ),
});

/**
 * Starts tracking money owed. The outstanding amount is subtracted from net worth from the as-of date onwards. The repayment terms are optional; with a loan amount, an interest rate, a first payment date and a term or a monthly payment the debt gets a repayment schedule and a payoff date. The debt and its terms are kept in the reporting currency of the day it is created, and later edits keep that currency.
 * @summary Add a debt
 */
export const createDebtBodyNameMin = 0;
export const createDebtBodyNameMax = 100;

export const createDebtBodyOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtBodyInterestRateMin = 0;
export const createDebtBodyInterestRateMax = 100;

export const createDebtBodyLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtBodyTermMonthsMax = 600;

export const createDebtBodyMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtBodyTracksPaymentsDefault = false;

export const CreateDebtBody = zod.object({
  name: zod.string().min(createDebtBodyNameMin).max(createDebtBodyNameMax),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod
    .stringFormat("decimal", createDebtBodyOutstandingAmountRegExp)
    .describe("Decimal string with at most two decimal places."),
  interestRate: zod
    .number()
    .min(createDebtBodyInterestRateMin)
    .max(createDebtBodyInterestRateMax)
    .nullable()
    .describe("Optional annual rate as a percentage, for example 2.4."),
  asOf: zod.iso.date(),
  loanAmount: zod
    .stringFormat("decimal", createDebtBodyLoanAmountRegExp)
    .nullish()
    .describe("Optional principal borrowed at the start, a positive decimal string."),
  firstPaymentDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe(
      "Optional date of the first monthly payment; later payments fall on the same day of the month.",
    ),
  termMonths: zod
    .int()
    .min(1)
    .max(createDebtBodyTermMonthsMax)
    .nullish()
    .describe(
      "Optional number of monthly payments, 1 to 600. Leave monthlyPayment empty when it is set.",
    ),
  monthlyPayment: zod
    .stringFormat("decimal", createDebtBodyMonthlyPaymentRegExp)
    .nullish()
    .describe(
      "Optional fixed monthly payment of an annuity, a positive decimal string; the term is derived from it. It must repay the debt within 600 payments (debt.paymentTooSmall).",
    ),
  amortizationType: zod
    .union([zod.null(), zod.enum(["annuity", "linear"])])
    .optional()
    .describe(
      "annuity (level payment, the default) or linear (equal principal, needs termMonths).",
    ),
  tracksPayments: zod
    .boolean()
    .default(createDebtBodyTracksPaymentsDefault)
    .describe(
      "When true, the balance is outstandingAmount on asOf minus the principal of the payments linked after asOf. Editing outstandingAmount or asOf sets a new starting point.",
    ),
  scope: zod.enum(["personal", "shared"]).optional(),
  householdId: zod.uuid().nullish(),
});

export const createDebtResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtResponseTrackedBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateDebtResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", createDebtResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", createDebtResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod.stringFormat("decimal", createDebtResponseMonthlyPaymentRegExp).nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  tracksPayments: zod.boolean(),
  trackedBalance: zod.stringFormat("decimal", createDebtResponseTrackedBalanceRegExp).nullable(),
  trackedIncomplete: zod.boolean(),
  unavailablePayments: zod.int(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Returns the debts you track, each with its outstanding amount, optional interest rate, the date those figures are as of, the repayment terms when set, and payoffDate, the date of the last scheduled payment when the terms are complete.
 * @summary List debts
 */
export const debtsResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtsResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtsResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtsResponseTrackedBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const DebtsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", debtsResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", debtsResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod.stringFormat("decimal", debtsResponseMonthlyPaymentRegExp).nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  tracksPayments: zod.boolean(),
  trackedBalance: zod.stringFormat("decimal", debtsResponseTrackedBalanceRegExp).nullable(),
  trackedIncomplete: zod.boolean(),
  unavailablePayments: zod.int(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});
export const DebtsResponse = zod.array(DebtsResponseItem);

/**
 * Stops tracking the debt, for instance once it is settled. Snapshots already recorded keep the balance it had.
 * @summary Delete a debt
 */
export const DeleteDebtResponse = zod.void();

/**
 * Records a new outstanding balance, rate, name or repayment terms. This is how repayment progress is tracked: lower outstandingAmount as the debt is paid down. The request replaces the debt, so repayment terms left out are cleared.
 * @summary Update a debt
 */
export const updateDebtBodyNameMin = 0;
export const updateDebtBodyNameMax = 100;

export const updateDebtBodyOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtBodyInterestRateMin = 0;
export const updateDebtBodyInterestRateMax = 100;

export const updateDebtBodyLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtBodyTermMonthsMax = 600;

export const updateDebtBodyMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtBodyTracksPaymentsDefault = false;

export const UpdateDebtBody = zod.object({
  name: zod.string().min(updateDebtBodyNameMin).max(updateDebtBodyNameMax),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", updateDebtBodyOutstandingAmountRegExp),
  interestRate: zod
    .number()
    .min(updateDebtBodyInterestRateMin)
    .max(updateDebtBodyInterestRateMax)
    .nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod
    .stringFormat("decimal", updateDebtBodyLoanAmountRegExp)
    .nullish()
    .describe("Optional principal borrowed at the start, a positive decimal string."),
  firstPaymentDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe(
      "Optional date of the first monthly payment; later payments fall on the same day of the month.",
    ),
  termMonths: zod
    .int()
    .min(1)
    .max(updateDebtBodyTermMonthsMax)
    .nullish()
    .describe(
      "Optional number of monthly payments, 1 to 600. Leave monthlyPayment empty when it is set.",
    ),
  monthlyPayment: zod
    .stringFormat("decimal", updateDebtBodyMonthlyPaymentRegExp)
    .nullish()
    .describe(
      "Optional fixed monthly payment of an annuity, a positive decimal string; the term is derived from it. It must repay the debt within 600 payments (debt.paymentTooSmall).",
    ),
  amortizationType: zod
    .union([zod.null(), zod.enum(["annuity", "linear"])])
    .optional()
    .describe(
      "annuity (level payment, the default) or linear (equal principal, needs termMonths).",
    ),
  tracksPayments: zod
    .boolean()
    .default(updateDebtBodyTracksPaymentsDefault)
    .describe(
      "When true, the balance is outstandingAmount on asOf minus the principal of the payments linked after asOf. Editing outstandingAmount or asOf sets a new starting point.",
    ),
  scope: zod.enum(["personal", "shared"]).optional(),
  householdId: zod.uuid().nullish(),
});

export const updateDebtResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtResponseTrackedBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateDebtResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", updateDebtResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", updateDebtResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod.stringFormat("decimal", updateDebtResponseMonthlyPaymentRegExp).nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  tracksPayments: zod.boolean(),
  trackedBalance: zod.stringFormat("decimal", updateDebtResponseTrackedBalanceRegExp).nullable(),
  trackedIncomplete: zod.boolean(),
  unavailablePayments: zod.int(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Lists up to 50 expense transactions that are not split and not linked to any of the signed-in user's debts, best matches first. A description equal to the name of a recurring entry that pays this debt, or to the description of a payment already linked, counts most; an amount within 5% of the schedule's regular payment counts next. Ties go to the newest.
 * @summary Suggest transactions to link to a debt
 */
export const debtPaymentCandidatesResponseAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtPaymentCandidatesResponseLinesItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtPaymentCandidatesResponseReportingAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtPaymentCandidatesResponseUnusualTwoTypicalAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtPaymentCandidatesResponseRefundedAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtPaymentCandidatesResponseSharedExpenseTwoSharesItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtPaymentCandidatesResponseSharedExpenseTwoMyShareRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const DebtPaymentCandidatesResponseItem = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  type: zod.enum(["income", "expense"]),
  amount: zod.stringFormat("decimal", debtPaymentCandidatesResponseAmountRegExp),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  source: zod.enum(["manual", "imported"]),
  isSplit: zod.boolean(),
  createdAt: zod.iso.datetime({ offset: true }),
  lines: zod
    .array(
      zod.object({
        id: zod.uuid(),
        categoryId: zod.uuid().nullable(),
        amount: zod.stringFormat("decimal", debtPaymentCandidatesResponseLinesItemAmountRegExp),
        description: zod.string().nullable(),
      }),
    )
    .nullable(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  reportingAmount: zod.stringFormat("decimal", debtPaymentCandidatesResponseReportingAmountRegExp),
  tagIds: zod.array(zod.uuid()),
  attachmentCount: zod.int(),
  unusual: zod.union([
    zod.null(),
    zod.object({
      basis: zod.enum(["payee", "category"]),
      typicalAmount: zod.stringFormat(
        "decimal",
        debtPaymentCandidatesResponseUnusualTwoTypicalAmountRegExp,
      ),
      factor: zod.number(),
      sampleSize: zod.int(),
    }),
  ]),
  unusualDismissed: zod.boolean(),
  debtPayment: zod
    .union([
      zod.null(),
      zod.object({
        id: zod.uuid(),
        debtId: zod.uuid(),
        debtName: zod.string(),
      }),
    ])
    .optional(),
  refundOf: zod
    .union([
      zod.null(),
      zod.object({
        id: zod.uuid(),
        date: zod.iso.date(),
        description: zod.string().nullable(),
      }),
    ])
    .optional(),
  refundedAmount: zod
    .stringFormat("decimal", debtPaymentCandidatesResponseRefundedAmountRegExp)
    .nullish(),
  sharedExpense: zod
    .union([
      zod.null(),
      zod.object({
        id: zod.uuid(),
        householdId: zod.uuid(),
        householdName: zod.string(),
        method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
        shares: zod.array(
          zod.object({
            userId: zod.uuid(),
            name: zod.string(),
            weight: zod.int().nullable(),
            amount: zod.stringFormat(
              "decimal",
              debtPaymentCandidatesResponseSharedExpenseTwoSharesItemAmountRegExp,
            ),
          }),
        ),
        myShare: zod.stringFormat(
          "decimal",
          debtPaymentCandidatesResponseSharedExpenseTwoMyShareRegExp,
        ),
        amountDiffers: zod.boolean(),
      }),
    ])
    .optional(),
  note: zod.string().nullish(),
  payeeName: zod.string().nullish(),
  spreadMonths: zod.int().nullish(),
  spreadUntil: zod.union([zod.null(), zod.iso.date()]).optional(),
});
export const DebtPaymentCandidatesResponse = zod.array(DebtPaymentCandidatesResponseItem);

/**
 * Returns the linked payments dated after the as-of date of a debt that tracks its payments, oldest first. Each row splits the payment, in the currency of the debt, into interest and principal and carries the balance after it. A regular payment pays a month of interest at the debt's rate first, an extra payment is all principal, and a principal typed on the link wins over both. Payments whose transaction was deleted or is no longer visible, and payments without an exchange rate, are left out; the debt counts them in unavailablePayments and trackedIncomplete. A debt that does not track payments has none.
 * @summary List the payments of a debt
 */
export const debtPaymentsResponseAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtPaymentsResponseInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtPaymentsResponsePrincipalRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtPaymentsResponseOverpaidRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtPaymentsResponseBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const DebtPaymentsResponseItem = zod.object({
  id: zod.uuid(),
  transactionId: zod.uuid(),
  date: zod.iso.date(),
  accountId: zod.uuid(),
  description: zod.string().nullable(),
  amount: zod.stringFormat("decimal", debtPaymentsResponseAmountRegExp),
  kind: zod
    .enum(["regular", "extra"])
    .describe("regular (a month of interest first) or extra (all principal)."),
  interest: zod.stringFormat("decimal", debtPaymentsResponseInterestRegExp),
  principal: zod.stringFormat("decimal", debtPaymentsResponsePrincipalRegExp),
  principalTyped: zod.boolean(),
  overpaid: zod.stringFormat("decimal", debtPaymentsResponseOverpaidRegExp),
  balance: zod.stringFormat("decimal", debtPaymentsResponseBalanceRegExp),
});
export const DebtPaymentsResponse = zod.array(DebtPaymentsResponseItem);

/**
 * Marks an expense transaction as a payment of a debt that tracks its payments, lowering the tracked balance by its principal. The transaction stays an ordinary expense in reports and budgets. A transaction pays at most one debt. The link is private to the owner of the debt, even on a shared account.
 * @summary Link a payment to a debt
 */

export const linkDebtPaymentBodyPrincipalRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const LinkDebtPaymentBody = zod.object({
  transactionId: zod
    .uuid()
    .min(1)
    .describe("An expense transaction the signed-in user can see, not split."),
  kind: zod
    .union([
      zod.null(),
      zod
        .enum(["regular", "extra"])
        .describe("regular (a month of interest first) or extra (all principal)."),
    ])
    .optional()
    .describe(
      "regular or extra. Left out, it is regular unless a regular payment is already linked in the same calendar month.",
    ),
  principal: zod
    .stringFormat("decimal", linkDebtPaymentBodyPrincipalRegExp)
    .nullish()
    .describe(
      "Optional principal from the bank statement, a positive decimal string in the currency of the debt. It replaces the calculated split.",
    ),
});

export const linkDebtPaymentResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const linkDebtPaymentResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const linkDebtPaymentResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const linkDebtPaymentResponseTrackedBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const LinkDebtPaymentResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", linkDebtPaymentResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", linkDebtPaymentResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod
    .stringFormat("decimal", linkDebtPaymentResponseMonthlyPaymentRegExp)
    .nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  tracksPayments: zod.boolean(),
  trackedBalance: zod
    .stringFormat("decimal", linkDebtPaymentResponseTrackedBalanceRegExp)
    .nullable(),
  trackedIncomplete: zod.boolean(),
  unavailablePayments: zod.int(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Removes the link for good; it does not go to the trash. The transaction itself is not touched.
 * @summary Unlink a payment from a debt
 */
export const UnlinkDebtPaymentResponse = zod.void();

/**
 * Sets the kind of a linked payment and the principal typed from the bank statement. Leaving the principal out goes back to the calculated split.
 * @summary Change how a payment counts against a debt
 */
export const updateDebtPaymentBodyPrincipalRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateDebtPaymentBody = zod.object({
  kind: zod
    .enum(["regular", "extra"])
    .describe("regular (a month of interest first) or extra (all principal)."),
  principal: zod
    .stringFormat("decimal", updateDebtPaymentBodyPrincipalRegExp)
    .nullish()
    .describe("Optional principal, a positive decimal string in the currency of the debt."),
});

export const updateDebtPaymentResponseOutstandingAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const updateDebtPaymentResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtPaymentResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtPaymentResponseTrackedBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateDebtPaymentResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", updateDebtPaymentResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", updateDebtPaymentResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod
    .stringFormat("decimal", updateDebtPaymentResponseMonthlyPaymentRegExp)
    .nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  tracksPayments: zod.boolean(),
  trackedBalance: zod
    .stringFormat("decimal", updateDebtPaymentResponseTrackedBalanceRegExp)
    .nullable(),
  trackedIncomplete: zod.boolean(),
  unavailablePayments: zod.int(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Computes the monthly amortization schedule of a debt from its loan amount, annual interest rate, first payment date and either its term or its fixed monthly payment. Every row splits the payment into interest and principal, amounts are rounded to cents and the last payment absorbs the rounding. The schedule is computed on every request and never stored. With extraMonthly or lumpSum the response also carries withExtra, the same debt repaid with those overpayments, and what they save.
 * @summary Get the repayment schedule of a debt
 */
export const debtScheduleResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseRegularPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseScheduledBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanTotalPaidRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanTotalInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanTotalExtraRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemPrincipalRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemExtraRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseWithExtraTwoTotalPaidRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseWithExtraTwoTotalInterestRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoTotalExtraRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemPaymentRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemInterestRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemPrincipalRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemExtraRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemBalanceRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseInterestSavedRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const DebtScheduleResponse = zod.object({
  debtId: zod.uuid(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", debtScheduleResponseLoanAmountRegExp),
  interestRate: zod.number(),
  amortizationType: zod.enum(["annuity", "linear"]),
  regularPayment: zod.stringFormat("decimal", debtScheduleResponseRegularPaymentRegExp),
  scheduledBalance: zod.stringFormat("decimal", debtScheduleResponseScheduledBalanceRegExp),
  paymentsMade: zod.int(),
  plan: zod.object({
    payoffDate: zod.iso.date(),
    payments: zod.int(),
    totalPaid: zod.stringFormat("decimal", debtScheduleResponsePlanTotalPaidRegExp),
    totalInterest: zod.stringFormat("decimal", debtScheduleResponsePlanTotalInterestRegExp),
    totalExtra: zod.stringFormat("decimal", debtScheduleResponsePlanTotalExtraRegExp),
    rows: zod.array(
      zod.object({
        number: zod.int(),
        date: zod.iso.date(),
        payment: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemPaymentRegExp),
        interest: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemInterestRegExp),
        principal: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemPrincipalRegExp),
        extra: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemExtraRegExp),
        balance: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemBalanceRegExp),
      }),
    ),
  }),
  withExtra: zod.union([
    zod.null(),
    zod.object({
      payoffDate: zod.iso.date(),
      payments: zod.int(),
      totalPaid: zod.stringFormat("decimal", debtScheduleResponseWithExtraTwoTotalPaidRegExp),
      totalInterest: zod.stringFormat(
        "decimal",
        debtScheduleResponseWithExtraTwoTotalInterestRegExp,
      ),
      totalExtra: zod.stringFormat("decimal", debtScheduleResponseWithExtraTwoTotalExtraRegExp),
      rows: zod.array(
        zod.object({
          number: zod.int(),
          date: zod.iso.date(),
          payment: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemPaymentRegExp,
          ),
          interest: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemInterestRegExp,
          ),
          principal: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemPrincipalRegExp,
          ),
          extra: zod.stringFormat("decimal", debtScheduleResponseWithExtraTwoRowsItemExtraRegExp),
          balance: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemBalanceRegExp,
          ),
        }),
      ),
    }),
  ]),
  interestSaved: zod.stringFormat("decimal", debtScheduleResponseInterestSavedRegExp).nullable(),
  paymentsSaved: zod.int().nullable(),
});

/**
 * Returns assets, debts, and the difference between them as of now. Account balances count towards assets, so cash in the ledger and tracked assets are not double counted against each other. Every total is in the reporting currency; assets and debts are converted from their own currency at today's rate. IsComplete is false when a balance, holding, asset or debt could not be valued and was left out, and no snapshot is taken then.
 * @summary Get current net worth
 */
export const netWorthResponseAccountsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthResponseAssetsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthResponseDebtsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthResponseNetWorthRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const NetWorthResponse = zod.object({
  accounts: zod.stringFormat("decimal", netWorthResponseAccountsRegExp),
  assets: zod.stringFormat("decimal", netWorthResponseAssetsRegExp),
  debts: zod.stringFormat("decimal", netWorthResponseDebtsRegExp),
  netWorth: zod.stringFormat("decimal", netWorthResponseNetWorthRegExp),
  isComplete: zod.boolean(),
});

/**
 * Returns the snapshots taken by the nightly background job, oldest first. Snapshots are only written while the job runs, so a freshly seeded instance can answer with an empty series. A snapshot taken in an earlier reporting currency is converted at the rate of its date, and left out when no rate is known.
 * @summary Get the net worth history
 */
export const netWorthHistoryResponseItemsItemAccountsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthHistoryResponseItemsItemAssetsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthHistoryResponseItemsItemDebtsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthHistoryResponseItemsItemNetWorthRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const NetWorthHistoryResponse = zod.object({
  items: zod.array(
    zod.object({
      date: zod.iso.date(),
      accounts: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemAccountsRegExp),
      assets: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemAssetsRegExp),
      debts: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemDebtsRegExp),
      netWorth: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemNetWorthRegExp),
    }),
  ),
});
