/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Starts tracking something of value that is not an account balance. Its value counts towards net worth from the as-of date onwards.
 * @summary Add an asset
 */
export const createAssetBodyNameMin = 0;
export const createAssetBodyNameMax = 100;

export const createAssetBodyCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateAssetBody = zod.object({
  name: zod.string().min(createAssetBodyNameMin).max(createAssetBodyNameMax),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod
    .stringFormat("decimal", createAssetBodyCurrentValueRegExp)
    .describe("Decimal string with at most two decimal places."),
  asOf: zod.iso.date(),
});

export const createAssetResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateAssetResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", createAssetResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
});

/**
 * Returns the assets you track outside the ledger, such as property or vehicles, each with its latest valuation and the date that valuation is as of.
 * @summary List assets
 */
export const assetsResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const AssetsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", assetsResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
});
export const AssetsResponse = zod.array(AssetsResponseItem);

/**
 * Stops tracking the asset. Snapshots already recorded keep the value it had.
 * @summary Delete an asset
 */
export const DeleteAssetResponse = zod.void();

/**
 * Revalues or renames an asset. Net worth uses the new value from the next read onwards; snapshots already taken keep the value that was current when they were written.
 * @summary Update an asset
 */
export const updateAssetBodyNameMin = 0;
export const updateAssetBodyNameMax = 100;

export const updateAssetBodyCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateAssetBody = zod.object({
  name: zod.string().min(updateAssetBodyNameMin).max(updateAssetBodyNameMax),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", updateAssetBodyCurrentValueRegExp),
  asOf: zod.iso.date(),
});

export const updateAssetResponseCurrentValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateAssetResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod
    .enum(["property", "vehicle", "investment", "valuable", "other"])
    .describe("Property, Vehicle, Investment, Valuable, or Other."),
  currentValue: zod.stringFormat("decimal", updateAssetResponseCurrentValueRegExp),
  asOf: zod.iso.date(),
});

/**
 * Starts tracking money owed. The outstanding amount is subtracted from net worth from the as-of date onwards. The repayment terms are optional; with a loan amount, an interest rate, a first payment date and a term or a monthly payment the debt gets a repayment schedule and a payoff date.
 * @summary Add a debt
 */
export const createDebtBodyNameMin = 0;
export const createDebtBodyNameMax = 100;

export const createDebtBodyOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtBodyInterestRateMin = 0;
export const createDebtBodyInterestRateMax = 100;

export const createDebtBodyLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtBodyTermMonthsMax = 600;

export const createDebtBodyMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateDebtBody = zod.object({
  name: zod.string().min(createDebtBodyNameMin).max(createDebtBodyNameMax),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod
    .stringFormat("decimal", createDebtBodyOutstandingAmountRegExp)
    .describe("Decimal string with at most two decimal places."),
  interestRate: zod
    .number()
    .min(createDebtBodyInterestRateMin)
    .max(createDebtBodyInterestRateMax)
    .nullable()
    .describe("Optional annual rate as a percentage, for example 2.4."),
  asOf: zod.iso.date(),
  loanAmount: zod
    .stringFormat("decimal", createDebtBodyLoanAmountRegExp)
    .nullish()
    .describe("Optional principal borrowed at the start, a positive decimal string."),
  firstPaymentDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe(
      "Optional date of the first monthly payment; later payments fall on the same day of the month.",
    ),
  termMonths: zod
    .int()
    .min(1)
    .max(createDebtBodyTermMonthsMax)
    .nullish()
    .describe(
      "Optional number of monthly payments, 1 to 600. Leave monthlyPayment empty when it is set.",
    ),
  monthlyPayment: zod
    .stringFormat("decimal", createDebtBodyMonthlyPaymentRegExp)
    .nullish()
    .describe(
      "Optional fixed monthly payment of an annuity, a positive decimal string; the term is derived from it. It must repay the debt within 600 payments (debt.paymentTooSmall).",
    ),
  amortizationType: zod
    .union([zod.null(), zod.enum(["annuity", "linear"])])
    .optional()
    .describe(
      "annuity (level payment, the default) or linear (equal principal, needs termMonths).",
    ),
});

export const createDebtResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createDebtResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateDebtResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", createDebtResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", createDebtResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod.stringFormat("decimal", createDebtResponseMonthlyPaymentRegExp).nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Returns the debts you track, each with its outstanding amount, optional interest rate, the date those figures are as of, the repayment terms when set, and payoffDate, the date of the last scheduled payment when the terms are complete.
 * @summary List debts
 */
export const debtsResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtsResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtsResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const DebtsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", debtsResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", debtsResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod.stringFormat("decimal", debtsResponseMonthlyPaymentRegExp).nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
});
export const DebtsResponse = zod.array(DebtsResponseItem);

/**
 * Stops tracking the debt, for instance once it is settled. Snapshots already recorded keep the balance it had.
 * @summary Delete a debt
 */
export const DeleteDebtResponse = zod.void();

/**
 * Records a new outstanding balance, rate, name or repayment terms. This is how repayment progress is tracked: lower outstandingAmount as the debt is paid down. The request replaces the debt, so repayment terms left out are cleared.
 * @summary Update a debt
 */
export const updateDebtBodyNameMin = 0;
export const updateDebtBodyNameMax = 100;

export const updateDebtBodyOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtBodyInterestRateMin = 0;
export const updateDebtBodyInterestRateMax = 100;

export const updateDebtBodyLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtBodyTermMonthsMax = 600;

export const updateDebtBodyMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateDebtBody = zod.object({
  name: zod.string().min(updateDebtBodyNameMin).max(updateDebtBodyNameMax),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", updateDebtBodyOutstandingAmountRegExp),
  interestRate: zod
    .number()
    .min(updateDebtBodyInterestRateMin)
    .max(updateDebtBodyInterestRateMax)
    .nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod
    .stringFormat("decimal", updateDebtBodyLoanAmountRegExp)
    .nullish()
    .describe("Optional principal borrowed at the start, a positive decimal string."),
  firstPaymentDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe(
      "Optional date of the first monthly payment; later payments fall on the same day of the month.",
    ),
  termMonths: zod
    .int()
    .min(1)
    .max(updateDebtBodyTermMonthsMax)
    .nullish()
    .describe(
      "Optional number of monthly payments, 1 to 600. Leave monthlyPayment empty when it is set.",
    ),
  monthlyPayment: zod
    .stringFormat("decimal", updateDebtBodyMonthlyPaymentRegExp)
    .nullish()
    .describe(
      "Optional fixed monthly payment of an annuity, a positive decimal string; the term is derived from it. It must repay the debt within 600 payments (debt.paymentTooSmall).",
    ),
  amortizationType: zod
    .union([zod.null(), zod.enum(["annuity", "linear"])])
    .optional()
    .describe(
      "annuity (level payment, the default) or linear (equal principal, needs termMonths).",
    ),
});

export const updateDebtResponseOutstandingAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateDebtResponseMonthlyPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateDebtResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  type: zod.enum(["mortgage", "loan", "other"]).describe("Mortgage, Loan, or Other."),
  outstandingAmount: zod.stringFormat("decimal", updateDebtResponseOutstandingAmountRegExp),
  interestRate: zod.number().nullable(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", updateDebtResponseLoanAmountRegExp).nullable(),
  firstPaymentDate: zod.union([zod.null(), zod.iso.date()]),
  termMonths: zod.int().nullable(),
  monthlyPayment: zod.stringFormat("decimal", updateDebtResponseMonthlyPaymentRegExp).nullable(),
  amortizationType: zod.enum(["annuity", "linear"]),
  payoffDate: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Computes the monthly amortization schedule of a debt from its loan amount, annual interest rate, first payment date and either its term or its fixed monthly payment. Every row splits the payment into interest and principal, amounts are rounded to cents and the last payment absorbs the rounding. The schedule is computed on every request and never stored. With extraMonthly or lumpSum the response also carries withExtra, the same debt repaid with those overpayments, and what they save.
 * @summary Get the repayment schedule of a debt
 */
export const debtScheduleResponseLoanAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseRegularPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseScheduledBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanTotalPaidRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanTotalInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanTotalExtraRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemPaymentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemPrincipalRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemExtraRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponsePlanRowsItemBalanceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseWithExtraTwoTotalPaidRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const debtScheduleResponseWithExtraTwoTotalInterestRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoTotalExtraRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemPaymentRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemInterestRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemPrincipalRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemExtraRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseWithExtraTwoRowsItemBalanceRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const debtScheduleResponseInterestSavedRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const DebtScheduleResponse = zod.object({
  debtId: zod.uuid(),
  asOf: zod.iso.date(),
  loanAmount: zod.stringFormat("decimal", debtScheduleResponseLoanAmountRegExp),
  interestRate: zod.number(),
  amortizationType: zod.enum(["annuity", "linear"]),
  regularPayment: zod.stringFormat("decimal", debtScheduleResponseRegularPaymentRegExp),
  scheduledBalance: zod.stringFormat("decimal", debtScheduleResponseScheduledBalanceRegExp),
  paymentsMade: zod.int(),
  plan: zod.object({
    payoffDate: zod.iso.date(),
    payments: zod.int(),
    totalPaid: zod.stringFormat("decimal", debtScheduleResponsePlanTotalPaidRegExp),
    totalInterest: zod.stringFormat("decimal", debtScheduleResponsePlanTotalInterestRegExp),
    totalExtra: zod.stringFormat("decimal", debtScheduleResponsePlanTotalExtraRegExp),
    rows: zod.array(
      zod.object({
        number: zod.int(),
        date: zod.iso.date(),
        payment: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemPaymentRegExp),
        interest: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemInterestRegExp),
        principal: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemPrincipalRegExp),
        extra: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemExtraRegExp),
        balance: zod.stringFormat("decimal", debtScheduleResponsePlanRowsItemBalanceRegExp),
      }),
    ),
  }),
  withExtra: zod.union([
    zod.null(),
    zod.object({
      payoffDate: zod.iso.date(),
      payments: zod.int(),
      totalPaid: zod.stringFormat("decimal", debtScheduleResponseWithExtraTwoTotalPaidRegExp),
      totalInterest: zod.stringFormat(
        "decimal",
        debtScheduleResponseWithExtraTwoTotalInterestRegExp,
      ),
      totalExtra: zod.stringFormat("decimal", debtScheduleResponseWithExtraTwoTotalExtraRegExp),
      rows: zod.array(
        zod.object({
          number: zod.int(),
          date: zod.iso.date(),
          payment: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemPaymentRegExp,
          ),
          interest: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemInterestRegExp,
          ),
          principal: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemPrincipalRegExp,
          ),
          extra: zod.stringFormat("decimal", debtScheduleResponseWithExtraTwoRowsItemExtraRegExp),
          balance: zod.stringFormat(
            "decimal",
            debtScheduleResponseWithExtraTwoRowsItemBalanceRegExp,
          ),
        }),
      ),
    }),
  ]),
  interestSaved: zod.stringFormat("decimal", debtScheduleResponseInterestSavedRegExp).nullable(),
  paymentsSaved: zod.int().nullable(),
});

/**
 * Returns assets, debts, and the difference between them as of now. Account balances count towards assets, so cash in the ledger and tracked assets are not double counted against each other.
 * @summary Get current net worth
 */
export const netWorthResponseAccountsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthResponseAssetsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthResponseDebtsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthResponseNetWorthRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const NetWorthResponse = zod.object({
  accounts: zod.stringFormat("decimal", netWorthResponseAccountsRegExp),
  assets: zod.stringFormat("decimal", netWorthResponseAssetsRegExp),
  debts: zod.stringFormat("decimal", netWorthResponseDebtsRegExp),
  netWorth: zod.stringFormat("decimal", netWorthResponseNetWorthRegExp),
});

/**
 * Returns the snapshots taken by the nightly background job, oldest first. Snapshots are only written while the job runs, so a freshly seeded instance can answer with an empty series.
 * @summary Get the net worth history
 */
export const netWorthHistoryResponseItemsItemAccountsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthHistoryResponseItemsItemAssetsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthHistoryResponseItemsItemDebtsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const netWorthHistoryResponseItemsItemNetWorthRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const NetWorthHistoryResponse = zod.object({
  items: zod.array(
    zod.object({
      date: zod.iso.date(),
      accounts: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemAccountsRegExp),
      assets: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemAssetsRegExp),
      debts: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemDebtsRegExp),
      netWorth: zod.stringFormat("decimal", netWorthHistoryResponseItemsItemNetWorthRegExp),
    }),
  ),
});
