/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Posts income or an expense to an account. Leave lines empty for an ordinary transaction. To split one payment across several categories, send the lines instead: they must add up to the transaction amount, and the top-level categoryId is then ignored.
 * @summary Record a transaction
 */

export const createTransactionBodyDescriptionMin = 0;
export const createTransactionBodyDescriptionMax = 500;

export const CreateTransactionBody = zod.object({
  accountId: zod.uuid().min(1).describe("The account the money moved on; must be visible to you."),
  categoryId: zod.uuid().nullable().describe("Optional category. Ignored when lines are supplied."),
  type: zod.enum(["income", "expense"]),
  amount: zod
    .string()
    .describe("Decimal string with at most two decimal places, greater than zero."),
  date: zod.iso.date(),
  description: zod
    .string()
    .min(createTransactionBodyDescriptionMin)
    .max(createTransactionBodyDescriptionMax)
    .nullable(),
  lines: zod
    .union([
      zod.null(),
      zod.array(
        zod.object({
          categoryId: zod.uuid().nullable(),
          amount: zod.string(),
          description: zod.string().nullable(),
        }),
      ),
    ])
    .describe("Optional split lines. Their amounts must sum to the transaction amount."),
  currency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional(),
});

export const CreateTransactionResponse = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  type: zod.enum(["income", "expense"]),
  amount: zod.string(),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  source: zod.enum(["manual", "imported"]),
  isSplit: zod.boolean(),
  createdAt: zod.iso.datetime({ offset: true }),
  lines: zod
    .array(
      zod.object({
        id: zod.uuid(),
        categoryId: zod.uuid().nullable(),
        amount: zod.string(),
        description: zod.string().nullable(),
      }),
    )
    .nullable(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  reportingAmount: zod.string(),
});

/**
 * Returns a page of the ledger, newest first, restricted to what you can see: your own transactions plus those on the shared accounts of your households. Every filter is optional and they combine with AND.
 * @summary List transactions
 */
export const GetTransactionsQueryParams = zod.object({
  page: zod.int().describe("One-based page number. Defaults to 1."),
  pageSize: zod.int().describe("Rows per page. Defaults to 20."),
  accountId: zod.uuid().nullish().describe("Keep only transactions on this account."),
  categoryId: zod
    .uuid()
    .nullish()
    .describe("Keep only transactions in this category, including split lines filed under it."),
  type: zod.enum(["income", "expense"]).optional().describe("Income or Expense."),
  search: zod.string().nullish().describe("Case-insensitive match against the description."),
  dateFrom: zod.iso.date().nullish().describe("Inclusive start date as YYYY-MM-DD."),
  dateTo: zod.iso.date().nullish().describe("Inclusive end date as YYYY-MM-DD."),
  sort: zod.enum(["date", "description", "category", "account", "amount"]).optional(),
  direction: zod.enum(["asc", "desc"]).optional(),
});

export const GetTransactionsResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.uuid(),
      accountId: zod.uuid(),
      categoryId: zod.uuid().nullable(),
      type: zod.enum(["income", "expense"]),
      amount: zod.string(),
      date: zod.iso.date(),
      description: zod.string().nullable(),
      source: zod.enum(["manual", "imported"]),
      isSplit: zod.boolean(),
      createdAt: zod.iso.datetime({ offset: true }),
      lines: zod
        .array(
          zod.object({
            id: zod.uuid(),
            categoryId: zod.uuid().nullable(),
            amount: zod.string(),
            description: zod.string().nullable(),
          }),
        )
        .nullable(),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      reportingAmount: zod.string(),
    }),
  ),
  page: zod.int(),
  pageSize: zod.int(),
  total: zod.int(),
});

/**
 * Files every listed transaction under one category, or clears their category when categoryId is null. The request is all-or-nothing: if any id is not visible to you, is a split transaction, or has a type the category does not match, nothing changes. Repeated ids count once.
 * @summary Set the category of several transactions
 */

export const BulkCategorizeTransactionsBody = zod.object({
  transactionIds: zod.array(zod.uuid()).min(1).describe("Between 1 and 200 transaction ids."),
  categoryId: zod
    .uuid()
    .nullable()
    .describe("The category to file them under, or null to clear it."),
});

export const BulkCategorizeTransactionsResponse = zod.object({
  updated: zod.int(),
});

/**
 * Returns the filtered ledger as a UTF-8 CSV attachment named transactions.csv, with account and category names resolved. It takes the same filters as the list endpoint but ignores paging: every matching row is included, so narrow the date range before exporting a large ledger.
 * @summary Export transactions as CSV
 */
export const ExportTransactionsQueryParams = zod.object({
  page: zod.int(),
  pageSize: zod.int(),
  accountId: zod.uuid().nullish().describe("Keep only transactions on this account."),
  categoryId: zod.uuid().nullish().describe("Keep only transactions in this category."),
  type: zod.enum(["income", "expense"]).optional().describe("Income or Expense."),
  search: zod.string().nullish().describe("Case-insensitive match against the description."),
  dateFrom: zod.iso.date().nullish().describe("Inclusive start date as YYYY-MM-DD."),
  dateTo: zod.iso.date().nullish().describe("Inclusive end date as YYYY-MM-DD."),
  sort: zod.enum(["date", "description", "category", "account", "amount"]).optional(),
  direction: zod.enum(["asc", "desc"]).optional(),
});

export const ExportTransactionsResponse = zod.unknown();

/**
 * Renders the filtered ledger as a printable PDF, attached as transactions.pdf. It takes the same filters as the list endpoint but ignores paging: every matching row is included, so narrow the date range before exporting a large ledger.
 * @summary Export transactions as PDF
 */
export const ExportTransactionsPdfQueryParams = zod.object({
  page: zod.int(),
  pageSize: zod.int(),
  accountId: zod.uuid().nullish().describe("Keep only transactions on this account."),
  categoryId: zod.uuid().nullish().describe("Keep only transactions in this category."),
  type: zod.enum(["income", "expense"]).optional().describe("Income or Expense."),
  search: zod.string().nullish().describe("Case-insensitive match against the description."),
  dateFrom: zod.iso
    .date()
    .nullish()
    .describe("Inclusive start date as YYYY-MM-DD; also printed in the header."),
  dateTo: zod.iso
    .date()
    .nullish()
    .describe("Inclusive end date as YYYY-MM-DD; also printed in the header."),
  sort: zod.enum(["date", "description", "category", "account", "amount"]).optional(),
  direction: zod.enum(["asc", "desc"]).optional(),
});

export const ExportTransactionsPdfResponse = zod.unknown();

/**
 * Returns the row count and the income and expense totals of every transaction the list endpoint would return for the same filters, across all pages. Transfers are not transactions and are never counted.
 * @summary Total the filtered transactions
 */
export const GetTransactionsSummaryQueryParams = zod.object({
  accountId: zod.uuid().nullish().describe("Keep only transactions on this account."),
  categoryId: zod
    .uuid()
    .nullish()
    .describe("Keep only transactions in this category, including split lines filed under it."),
  type: zod.enum(["income", "expense"]).optional().describe("Income or Expense."),
  search: zod.string().nullish().describe("Case-insensitive match against the description."),
  dateFrom: zod.iso.date().nullish().describe("Inclusive start date as YYYY-MM-DD."),
  dateTo: zod.iso.date().nullish().describe("Inclusive end date as YYYY-MM-DD."),
});

export const GetTransactionsSummaryResponse = zod.object({
  count: zod.int(),
  totalIncome: zod.string(),
  totalExpense: zod.string(),
});

/**
 * Removes the transaction and any split lines, and adjusts the account balance accordingly.
 * @summary Delete a transaction
 */
export const DeleteTransactionParams = zod.object({
  id: zod.string().describe("The transaction id."),
});

export const DeleteTransactionResponse = zod.void();

/**
 * Returns a single transaction, including its split lines when it has any. A transaction you cannot see is reported as missing rather than forbidden.
 * @summary Get one transaction
 */
export const GetTransactionParams = zod.object({
  id: zod.string().describe("The transaction id."),
});

export const GetTransactionResponse = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  type: zod.enum(["income", "expense"]),
  amount: zod.string(),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  source: zod.enum(["manual", "imported"]),
  isSplit: zod.boolean(),
  createdAt: zod.iso.datetime({ offset: true }),
  lines: zod
    .array(
      zod.object({
        id: zod.uuid(),
        categoryId: zod.uuid().nullable(),
        amount: zod.string(),
        description: zod.string().nullable(),
      }),
    )
    .nullable(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  reportingAmount: zod.string(),
});

/**
 * Replaces the transaction. Split lines are replaced wholesale rather than merged: send the full set you want to keep, or omit lines to turn a split back into a plain transaction. Moving it to another account adjusts both balances.
 * @summary Update a transaction
 */
export const UpdateTransactionParams = zod.object({
  id: zod.uuid().describe("The transaction id. Takes precedence over the id in the body."),
});

export const updateTransactionBodyDescriptionMin = 0;
export const updateTransactionBodyDescriptionMax = 500;

export const UpdateTransactionBody = zod.object({
  accountId: zod.uuid().min(1),
  categoryId: zod.uuid().nullable(),
  type: zod.enum(["income", "expense"]),
  amount: zod.string(),
  date: zod.iso.date(),
  description: zod
    .string()
    .min(updateTransactionBodyDescriptionMin)
    .max(updateTransactionBodyDescriptionMax)
    .nullable(),
  lines: zod.union([
    zod.null(),
    zod.array(
      zod.object({
        categoryId: zod.uuid().nullable(),
        amount: zod.string(),
        description: zod.string().nullable(),
      }),
    ),
  ]),
  currency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional(),
});

export const UpdateTransactionResponse = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  type: zod.enum(["income", "expense"]),
  amount: zod.string(),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  source: zod.enum(["manual", "imported"]),
  isSplit: zod.boolean(),
  createdAt: zod.iso.datetime({ offset: true }),
  lines: zod
    .array(
      zod.object({
        id: zod.uuid(),
        categoryId: zod.uuid().nullable(),
        amount: zod.string(),
        description: zod.string().nullable(),
      }),
    )
    .nullable(),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  reportingAmount: zod.string(),
});
