/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Returns the display names you gave to payees, ordered by name. A payee is the normalized description every transaction stores as its payee key; a name is personal and shows in place of the bank's text wherever that key appears for you.
 * @summary List your payee names
 */
export const PayeeNamesResponseItem = zod.object({
  id: zod.uuid(),
  payeeKey: zod.string(),
  name: zod.string(),
});
export const PayeeNamesResponse = zod.array(PayeeNamesResponseItem);

/**
 * Gives a payee a display name, or renames it. The payee is normalized the way every transaction's payee key is, so a raw bank description such as "MAXIMA LT 1234 VILNIUS" and a payeeKey from the report name the same payee. The name is yours alone and changes no transaction.
 * @summary Name a payee
 */
export const setPayeeNameBodyPayeeMin = 0;
export const setPayeeNameBodyPayeeMax = 500;

export const setPayeeNameBodyNameMin = 0;
export const setPayeeNameBodyNameMax = 100;

export const SetPayeeNameBody = zod.object({
  payee: zod
    .string()
    .min(setPayeeNameBodyPayeeMin)
    .max(setPayeeNameBodyPayeeMax)
    .describe("A bank description or a payee key, at most 500 characters."),
  name: zod
    .string()
    .min(setPayeeNameBodyNameMin)
    .max(setPayeeNameBodyNameMax)
    .describe("The display name, at most 100 characters."),
});

export const SetPayeeNameResponse = zod.object({
  id: zod.uuid(),
  payeeKey: zod.string(),
  name: zod.string(),
});

/**
 * Removes a display name, so the payee reads as the bank's description again. No transaction changes.
 * @summary Remove a payee name
 */
export const DeletePayeeNameResponse = zod.void();
