/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Adds a person outside the household, such as a friend you lend money to or share a dinner with. The person has no login and is visible only to you. Two people may have the same name.
 * @summary Add a person
 */
export const createContactBodyNameMin = 0;
export const createContactBodyNameMax = 100;

export const CreateContactBody = zod.object({
  name: zod
    .string()
    .min(createContactBodyNameMin)
    .max(createContactBodyNameMax)
    .describe("The name, 1 to 100 characters."),
});

export const createContactResponseBalancesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateContactResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  balances: zod.array(
    zod.object({
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      amount: zod.stringFormat("decimal", createContactResponseBalancesItemAmountRegExp),
    }),
  ),
});

/**
 * Returns your people outside the household, by name, each with the open balance per currency. A positive amount is owed to you, a negative one is owed by you. A balance is what the person's shares of your splits add up to, plus the payments you made to them, minus the payments they made to you. A split whose transaction is deleted stops counting until the transaction is restored. Currencies are never converted, and nothing here enters reports, budgets or net worth. People are personal: nobody else sees them.
 * @summary List the people you keep money with
 */
export const contactsResponseBalancesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ContactsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  balances: zod.array(
    zod.object({
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      amount: zod.stringFormat("decimal", contactsResponseBalancesItemAmountRegExp),
    }),
  ),
});
export const ContactsResponse = zod.array(ContactsResponseItem);

/**
 * Removes the payment from the person's balance. It is listed in your trash, from where POST /api/trash/restore brings it back while the person still exists.
 * @summary Delete a payment with a person
 */
export const DeleteContactPaymentResponse = zod.void();

/**
 * Splits an expense you paid from one of your own accounts with people outside the household, the way a household split divides it between members: Equal, Shares by whole weights from 1 to 100, or Exact amounts that add up to the expense, cents left over going to the largest remainders in the order listed with you first. own is your part, or null when you take no part, which records the whole amount as owed, for example money you lent with an ordinary bank payment. The split keeps a copy of the transaction's date, description and amount. A transaction is split once, with a household or with people.
 * @summary Split an expense with people
 */

export const createContactSplitBodyOwnTwoAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createContactSplitBodySharesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateContactSplitBody = zod.object({
  transactionId: zod
    .uuid()
    .min(1)
    .describe("The expense to split. It must be on an account you own."),
  method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
  own: zod
    .union([
      zod.null(),
      zod.object({
        weight: zod.int().nullish(),
        amount: zod.stringFormat("decimal", createContactSplitBodyOwnTwoAmountRegExp).nullish(),
      }),
    ])
    .describe("Your part: a weight for Shares, an amount for Exact; null when you take no part."),
  shares: zod
    .array(
      zod.object({
        contactId: zod.uuid(),
        weight: zod.int().nullish(),
        amount: zod.stringFormat("decimal", createContactSplitBodySharesItemAmountRegExp).nullish(),
      }),
    )
    .describe("One entry per person: a weight for Shares, an amount for Exact."),
});

export const createContactSplitResponseOwnAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createContactSplitResponseSharesItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const CreateContactSplitResponse = zod.object({
  id: zod.uuid(),
  method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
  ownWeight: zod.int().nullable(),
  ownAmount: zod.stringFormat("decimal", createContactSplitResponseOwnAmountRegExp).nullable(),
  shares: zod.array(
    zod.object({
      contactId: zod.uuid(),
      name: zod.string(),
      weight: zod.int().nullable(),
      amount: zod.stringFormat("decimal", createContactSplitResponseSharesItemAmountRegExp),
    }),
  ),
});

/**
 * Removes the split from every person's balance and leaves the transaction as it is. It is listed in your trash, from where POST /api/trash/restore brings it back while its transaction exists and is not split again.
 * @summary Delete a split with people
 */
export const DeleteContactSplitResponse = zod.void();

/**
 * Replaces the method, your part and the people with their amounts. The split first copies the transaction's current amount, date and description, so saving it again follows a corrected transaction.
 * @summary Change a split with people
 */
export const updateContactSplitBodyOwnTwoAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateContactSplitBodySharesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateContactSplitBody = zod.object({
  method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
  own: zod.union([
    zod.null(),
    zod.object({
      weight: zod.int().nullish(),
      amount: zod.stringFormat("decimal", updateContactSplitBodyOwnTwoAmountRegExp).nullish(),
    }),
  ]),
  shares: zod.array(
    zod.object({
      contactId: zod.uuid(),
      weight: zod.int().nullish(),
      amount: zod.stringFormat("decimal", updateContactSplitBodySharesItemAmountRegExp).nullish(),
    }),
  ),
});

export const updateContactSplitResponseOwnAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateContactSplitResponseSharesItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const UpdateContactSplitResponse = zod.object({
  id: zod.uuid(),
  method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
  ownWeight: zod.int().nullable(),
  ownAmount: zod.stringFormat("decimal", updateContactSplitResponseOwnAmountRegExp).nullable(),
  shares: zod.array(
    zod.object({
      contactId: zod.uuid(),
      name: zod.string(),
      weight: zod.int().nullable(),
      amount: zod.stringFormat("decimal", updateContactSplitResponseSharesItemAmountRegExp),
    }),
  ),
});

/**
 * Removes the person, and with them their balances, payments and shares, from every list. Splits they shared with others keep the other people's shares. The person is listed in your trash, from where POST /api/trash/restore brings everything back; after 30 days the person, their payments and their shares are purged, and a split left with nobody else goes with them.
 * @summary Delete a person
 */
export const DeleteContactResponse = zod.void();

/**
 * Changes the name of one of your people. Their splits, payments and balances stay.
 * @summary Rename a person
 */
export const updateContactBodyNameMin = 0;
export const updateContactBodyNameMax = 100;

export const UpdateContactBody = zod.object({
  name: zod
    .string()
    .min(updateContactBodyNameMin)
    .max(updateContactBodyNameMax)
    .describe("The new name, 1 to 100 characters."),
});

export const updateContactResponseBalancesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateContactResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  balances: zod.array(
    zod.object({
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      amount: zod.stringFormat("decimal", updateContactResponseBalancesItemAmountRegExp),
    }),
  ),
});

/**
 * Returns a page of the person's history, newest first: each split with its copied date and description and the person's share as amount, and each payment with its direction and note. counted is false while a split's transaction is deleted; a payment always counts.
 * @summary List what you shared with a person
 */
export const contactEntriesResponseItemsItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ContactEntriesResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.uuid(),
      kind: zod.enum(["split", "payment"]),
      date: zod.iso.date(),
      description: zod.string().nullable(),
      amount: zod.stringFormat("decimal", contactEntriesResponseItemsItemAmountRegExp),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      direction: zod.union([
        zod.null(),
        zod
          .enum(["toContact", "fromContact"])
          .describe("ToContact when you paid them, FromContact when they paid you or for you."),
      ]),
      counted: zod.boolean(),
    }),
  ),
  page: zod.int(),
  pageSize: zod.int(),
  total: zod.int(),
});

/**
 * Records that you paid the person (ToContact), for example a loan or paying back what you owed, or that they paid you or paid for you (FromContact). Your paying raises what they owe you; their paying lowers it. Only the payment is stored: no account changes, and money that left or reached your bank stays the ordinary ledger row it is.
 * @summary Record money between you and a person
 */
export const createContactPaymentBodyAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createContactPaymentBodyNoteMin = 0;
export const createContactPaymentBodyNoteMax = 200;

export const CreateContactPaymentBody = zod.object({
  direction: zod
    .enum(["toContact", "fromContact"])
    .describe("ToContact when you paid them, FromContact when they paid you or for you."),
  amount: zod
    .stringFormat("decimal", createContactPaymentBodyAmountRegExp)
    .describe("Decimal string with at most two decimal places, greater than zero."),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  date: zod.iso.date(),
  note: zod
    .string()
    .min(createContactPaymentBodyNoteMin)
    .max(createContactPaymentBodyNoteMax)
    .nullish(),
});

export const createContactPaymentResponseAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateContactPaymentResponse = zod.object({
  id: zod.uuid(),
  kind: zod.enum(["split", "payment"]),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  amount: zod.stringFormat("decimal", createContactPaymentResponseAmountRegExp),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  direction: zod.union([
    zod.null(),
    zod
      .enum(["toContact", "fromContact"])
      .describe("ToContact when you paid them, FromContact when they paid you or for you."),
  ]),
  counted: zod.boolean(),
});
