/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Moves money from one of your accounts to another. Both balances change and neither side counts as income or expense, so reports and budgets are left alone. The two accounts must differ and both must be visible to you.
 * @summary Create a transfer
 */

export const createTransferBodyAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createTransferBodyDescriptionMin = 0;
export const createTransferBodyDescriptionMax = 500;

export const createTransferBodyReceivedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateTransferBody = zod.object({
  fromAccountId: zod.uuid().min(1),
  toAccountId: zod.uuid().min(1),
  amount: zod
    .stringFormat("decimal", createTransferBodyAmountRegExp)
    .describe("Decimal string with at most two decimal places, greater than zero."),
  date: zod.iso.date(),
  description: zod
    .string()
    .min(createTransferBodyDescriptionMin)
    .max(createTransferBodyDescriptionMax)
    .nullable(),
  currency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional(),
  receivedAmount: zod.stringFormat("decimal", createTransferBodyReceivedAmountRegExp).nullish(),
  receivedCurrency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional(),
});

export const createTransferResponseAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createTransferResponseReceivedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateTransferResponse = zod.object({
  id: zod.uuid(),
  fromAccountId: zod.uuid(),
  toAccountId: zod.uuid(),
  amount: zod.stringFormat("decimal", createTransferResponseAmountRegExp),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  receivedAmount: zod.stringFormat("decimal", createTransferResponseReceivedAmountRegExp),
  receivedCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  fromAccountImported: zod.boolean(),
  toAccountImported: zod.boolean(),
});

/**
 * Returns a page of transfers between your own accounts, newest first. Transfers are kept apart from transactions on purpose: moving money between your accounts is neither income nor an expense and must not distort reports.
 * @summary List transfers
 */
export const transfersResponseItemsItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const transfersResponseItemsItemReceivedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const TransfersResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.uuid(),
      fromAccountId: zod.uuid(),
      toAccountId: zod.uuid(),
      amount: zod.stringFormat("decimal", transfersResponseItemsItemAmountRegExp),
      date: zod.iso.date(),
      description: zod.string().nullable(),
      createdAt: zod.iso.datetime({ offset: true }),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      receivedAmount: zod.stringFormat("decimal", transfersResponseItemsItemReceivedAmountRegExp),
      receivedCurrency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      fromAccountImported: zod.boolean(),
      toAccountImported: zod.boolean(),
    }),
  ),
  page: zod.int(),
  pageSize: zod.int(),
  total: zod.int(),
});

/**
 * Reverses the transfer: both account balances go back to what they were before it.
 * @summary Delete a transfer
 */
export const DeleteTransferResponse = zod.void();

/**
 * Replaces the date, amounts, description and both accounts of a transfer. The amount rules are those of creating one: between two currencies the received amount is required, within one currency it may be left out and must equal the sent amount when given. Send currency and receivedCurrency as the transfer has them; without them they default to the main currency of the chosen accounts. You need access to both accounts the transfer has now and to both accounts it should have afterwards. A transfer that was created or matched by a bank or broker import holds a receipt per imported account, flagged by fromAccountImported and toAccountImported: its date, that account's side of the transfer and the amount on that side are fixed and a change answers value.locked, while the description, the other account and, between currencies, the other amount stay editable.
 * @summary Update a transfer
 */

export const updateTransferBodyAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateTransferBodyDescriptionMin = 0;
export const updateTransferBodyDescriptionMax = 500;

export const updateTransferBodyReceivedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateTransferBody = zod.object({
  fromAccountId: zod.uuid().min(1),
  toAccountId: zod.uuid().min(1),
  amount: zod
    .stringFormat("decimal", updateTransferBodyAmountRegExp)
    .describe("Decimal string with at most two decimal places, greater than zero."),
  date: zod.iso.date(),
  description: zod
    .string()
    .min(updateTransferBodyDescriptionMin)
    .max(updateTransferBodyDescriptionMax)
    .nullable(),
  currency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional(),
  receivedAmount: zod
    .stringFormat("decimal", updateTransferBodyReceivedAmountRegExp)
    .nullish()
    .describe("The amount that arrived. Required when the two currencies differ."),
  receivedCurrency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional(),
});

export const updateTransferResponseAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateTransferResponseReceivedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateTransferResponse = zod.object({
  id: zod.uuid(),
  fromAccountId: zod.uuid(),
  toAccountId: zod.uuid(),
  amount: zod.stringFormat("decimal", updateTransferResponseAmountRegExp),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  receivedAmount: zod.stringFormat("decimal", updateTransferResponseReceivedAmountRegExp),
  receivedCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  fromAccountImported: zod.boolean(),
  toAccountImported: zod.boolean(),
});
