<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints.Testing" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="NetArchTest.eNhancedEdition" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JxFinance.Api\JxFinance.Api.csproj" />
  </ItemGroup>

</Project>
