/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Returns your notifications, newest first. These are raised by background jobs, for example when a recurring bill is about to fall due.
 * @summary List notifications
 */
export const NotificationsResponseItem = zod.object({
  id: zod.uuid(),
  type: zod.enum(["billDue"]),
  title: zod.string(),
  message: zod.string(),
  payload: zod.object({
    dueDate: zod.union([zod.null(), zod.iso.date()]).optional(),
    thresholdPercent: zod.int().nullish(),
    period: zod
      .union([
        zod.null(),
        zod
          .enum(["monthly", "weekly", "quarterly", "yearly"])
          .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
      ])
      .optional(),
    shape: zod
      .union([
        zod.null(),
        zod
          .enum(["expense", "income", "transfer"])
          .describe("Expense, Income, or Transfer. Decides what a confirmation writes."),
      ])
      .optional(),
  }),
  relatedType: zod.string().nullable(),
  relatedId: zod.uuid().nullable(),
  channel: zod.enum(["inApp", "email"]),
  isRead: zod.boolean(),
  createdAt: zod.iso.datetime({ offset: true }),
});
export const NotificationsResponse = zod.array(NotificationsResponseItem);

/**
 * Clears the unread badge by marking all of your notifications read at once.
 * @summary Mark every notification read
 */
export const MarkAllNotificationsReadResponse = zod.void();

/**
 * Marks a single notification as read. Marking an already read notification again changes nothing and still answers 204.
 * @summary Mark one notification read
 */
export const MarkNotificationReadResponse = zod.void();
