/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const problemDetailsResponseTypeDefault = `https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1`;
export const problemDetailsResponseTitleDefault = `One or more validation errors occurred.`;
export const problemDetailsResponseStatusDefault = 400;
export const problemDetailsResponseInstanceDefault = `/api/route`;
export const problemDetailsResponseTraceIdDefault = `0HMPNHL0JHL76:00000001`;
export const problemDetailsResponseErrorsItemNameDefault = `Error or field name`;
export const problemDetailsResponseErrorsItemReasonDefault = `Error reason`;

export const ProblemDetailsResponse = zod
  .object({
    type: zod.string().nullish().default(problemDetailsResponseTypeDefault),
    title: zod.string().nullish().default(problemDetailsResponseTitleDefault),
    status: zod.int().default(problemDetailsResponseStatusDefault),
    instance: zod.string().default(problemDetailsResponseInstanceDefault),
    traceId: zod.string().default(problemDetailsResponseTraceIdDefault),
    detail: zod.string().nullish().describe("the details of the error"),
    errors: zod
      .array(
        zod
          .object({
            name: zod
              .string()
              .default(problemDetailsResponseErrorsItemNameDefault)
              .describe("the name of the error or property of the dto that caused the error"),
            reason: zod
              .string()
              .default(problemDetailsResponseErrorsItemReasonDefault)
              .describe("the reason for the error"),
            code: zod
              .enum([
                "access.forbidden",
                "backup.invalidFile",
                "backup.schemaMismatch",
                "backup.tooLarge",
                "broker.rejected",
                "broker.tokenRequired",
                "broker.unavailable",
                "category.wrongType",
                "collection.invalidSize",
                "conflict.busy",
                "conflict.duplicate",
                "conflict.stale",
                "credentials.invalid",
                "credentials.lockedOut",
                "currency.disabled",
                "decimal.malformed",
                "email.alreadyVerified",
                "email.invalid",
                "email.notConfigured",
                "email.passwordUnreadable",
                "email.sendFailed",
                "email.taken",
                "email.tokenInvalid",
                "enum.invalid",
                "exchangeRate.unavailable",
                "export.tooManyRows",
                "feature.disabled",
                "holding.dependentSales",
                "holding.oversold",
                "household.lastOwner",
                "household.notMember",
                "household.required",
                "iban.invalid",
                "import.invalidFile",
                "import.transferAlreadyMatched",
                "import.transferMismatch",
                "money.invalid",
                "money.nonNegative",
                "money.positive",
                "password.incorrect",
                "password.tooWeak",
                "passwordReset.tokenInvalid",
                "quantity.nonNegative",
                "quantity.positive",
                "range.invalid",
                "recurringBill.inactive",
                "reference.notFound",
                "request.invalid",
                "request.malformed",
                "required",
                "resource.notFound",
                "resource.readOnly",
                "restore.companionDeleted",
                "restore.detailsLost",
                "restore.expired",
                "restore.referenceMissing",
                "restore.slotTaken",
                "security.notHeld",
                "session.current",
                "setup.alreadyCompleted",
                "text.invalidFormat",
                "text.tooLong",
                "text.tooShort",
                "transaction.linesMismatch",
                "transaction.splitNotAllowed",
                "transfer.amountMismatch",
                "transfer.receivedAmountRequired",
                "transfer.sameAccount",
                "twoFactor.invalidCode",
                "user.lastAdministrator",
                "user.selfChange",
                "value.locked",
                "value.mustBeEmpty",
                "value.mustDiffer",
              ])
              .optional()
              .describe("The kind of failure. The name says which field it concerns."),
            severity: zod.string().nullish().describe("the severity of the error"),
          })
          .describe("the error details object"),
      )
      .optional(),
    code: zod
      .enum([
        "access.forbidden",
        "backup.invalidFile",
        "backup.schemaMismatch",
        "backup.tooLarge",
        "broker.rejected",
        "broker.tokenRequired",
        "broker.unavailable",
        "category.wrongType",
        "collection.invalidSize",
        "conflict.busy",
        "conflict.duplicate",
        "conflict.stale",
        "credentials.invalid",
        "credentials.lockedOut",
        "currency.disabled",
        "decimal.malformed",
        "email.alreadyVerified",
        "email.invalid",
        "email.notConfigured",
        "email.passwordUnreadable",
        "email.sendFailed",
        "email.taken",
        "email.tokenInvalid",
        "enum.invalid",
        "exchangeRate.unavailable",
        "export.tooManyRows",
        "feature.disabled",
        "holding.dependentSales",
        "holding.oversold",
        "household.lastOwner",
        "household.notMember",
        "household.required",
        "iban.invalid",
        "import.invalidFile",
        "import.transferAlreadyMatched",
        "import.transferMismatch",
        "money.invalid",
        "money.nonNegative",
        "money.positive",
        "password.incorrect",
        "password.tooWeak",
        "passwordReset.tokenInvalid",
        "quantity.nonNegative",
        "quantity.positive",
        "range.invalid",
        "recurringBill.inactive",
        "reference.notFound",
        "request.invalid",
        "request.malformed",
        "required",
        "resource.notFound",
        "resource.readOnly",
        "restore.companionDeleted",
        "restore.detailsLost",
        "restore.expired",
        "restore.referenceMissing",
        "restore.slotTaken",
        "security.notHeld",
        "session.current",
        "setup.alreadyCompleted",
        "text.invalidFormat",
        "text.tooLong",
        "text.tooShort",
        "transaction.linesMismatch",
        "transaction.splitNotAllowed",
        "transfer.amountMismatch",
        "transfer.receivedAmountRequired",
        "transfer.sameAccount",
        "twoFactor.invalidCode",
        "user.lastAdministrator",
        "user.selfChange",
        "value.locked",
        "value.mustBeEmpty",
        "value.mustDiffer",
      ])
      .optional()
      .describe("Set when the problem has no errors entries, for example feature.disabled."),
  })
  .describe(
    "RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\n```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```",
  );
