/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * One connection per account. The Flex token is write-only and never returned.
 * @summary List your Interactive Brokers connections
 */
export const BrokerConnectionsResponseItem = zod.object({
  accountId: zod.uuid(),
  fundingAccountId: zod.uuid().nullable(),
  queryId: zod.string(),
  isEnabled: zod.boolean(),
  lastSyncAt: zod.iso.datetime({ offset: true }).nullable(),
  lastError: zod.string().nullable(),
});
export const BrokerConnectionsResponse = zod.array(BrokerConnectionsResponseItem);

/**
 * Forgets the token and stops automatic sync. Imported entries stay.
 * @summary Remove an Interactive Brokers connection
 */
export const DeleteBrokerConnectionResponse = zod.void();

/**
 * Stores the Flex Query id and token so the server can download the report once a day and on demand. The token is encrypted at rest. Leave Token empty to keep the stored one.
 * @summary Connect an account to the Interactive Brokers Flex Web Service
 */

export const saveBrokerConnectionBodyQueryIdRegExp = new RegExp("^[0-9]{1,20}$");
export const saveBrokerConnectionBodyTokenRegExp = new RegExp("^[0-9]{6,64}$");
export const saveBrokerConnectionBodyIsEnabledDefault = true;

export const SaveBrokerConnectionBody = zod.object({
  queryId: zod.string().min(1).regex(saveBrokerConnectionBodyQueryIdRegExp),
  token: zod
    .string()
    .regex(saveBrokerConnectionBodyTokenRegExp)
    .nullish()
    .describe("Required the first time; optional afterwards."),
  fundingAccountId: zod.uuid().nullish(),
  isEnabled: zod.boolean().default(saveBrokerConnectionBodyIsEnabledDefault),
});

export const SaveBrokerConnectionResponse = zod.object({
  accountId: zod.uuid(),
  fundingAccountId: zod.uuid().nullable(),
  queryId: zod.string(),
  isEnabled: zod.boolean(),
  lastSyncAt: zod.iso.datetime({ offset: true }).nullable(),
  lastError: zod.string().nullable(),
});

/**
 * Asks Interactive Brokers to run the stored Flex Query, waits for it, and imports it the same way as an uploaded file. Can take up to a minute.
 * @summary Download and import the Flex Query report now
 */
export const syncBrokerConnectionResponsePositionMismatchesItemBrokerQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const syncBrokerConnectionResponsePositionMismatchesItemReplayedQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const SyncBrokerConnectionResponse = zod.object({
  trades: zod.int(),
  cashEntries: zod.int(),
  conversions: zod.int(),
  transfers: zod.int(),
  duplicates: zod.int(),
  skipped: zod.int(),
  securitiesCreated: zod.int(),
  pricesUpdated: zod.int(),
  splits: zod.int(),
  skippedCorporateActions: zod.array(
    zod.object({
      type: zod.string(),
      count: zod.int(),
    }),
  ),
  positionMismatches: zod
    .array(
      zod.object({
        symbol: zod.string(),
        brokerQuantity: zod.stringFormat(
          "decimal",
          syncBrokerConnectionResponsePositionMismatchesItemBrokerQuantityRegExp,
        ),
        replayedQuantity: zod.stringFormat(
          "decimal",
          syncBrokerConnectionResponsePositionMismatchesItemReplayedQuantityRegExp,
        ),
      }),
    )
    .nullable(),
});

/**
 * Reads the Trades, Cash Transactions, Corporate Actions and Open Positions sections of a Flex Query XML report. Stock, ETF and fund trades become buys and sells; currency trades become in-account conversions; dividends, withholding tax, interest and fees become cash entries; forward and reverse splits become split entries with the ratio as new shares per old share; open positions update last prices. Deposits and withdrawals become transfers when a funding account is given and are skipped otherwise. Every entry is matched by its broker id, so importing overlapping periods never duplicates. The import is all or nothing. Other corporate actions (mergers, spin-offs, stock dividends, symbol changes) are not booked: they are counted in skipped and listed per type in skippedCorporateActions. When the report has an Open Positions section, positionMismatches lists every security whose quantity replayed from the entries differs from the quantity the broker reports, which is how an action that was not booked becomes visible; it is null when the report has no Open Positions section.
 * @summary Import an Interactive Brokers Flex Query report
 */
export const ImportBrokerReportBody = zod.object({
  file: zod.instanceof(Blob).optional(),
  accountId: zod.uuid().optional().describe("The account that mirrors the broker account."),
  fundingAccountId: zod
    .uuid()
    .nullish()
    .describe("Optional bank account that deposits come from and withdrawals go to."),
});

export const importBrokerReportResponsePositionMismatchesItemBrokerQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const importBrokerReportResponsePositionMismatchesItemReplayedQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const ImportBrokerReportResponse = zod.object({
  trades: zod.int(),
  cashEntries: zod.int(),
  conversions: zod.int(),
  transfers: zod.int(),
  duplicates: zod.int(),
  skipped: zod.int(),
  securitiesCreated: zod.int(),
  pricesUpdated: zod.int(),
  splits: zod.int(),
  skippedCorporateActions: zod.array(
    zod.object({
      type: zod.string(),
      count: zod.int(),
    }),
  ),
  positionMismatches: zod
    .array(
      zod.object({
        symbol: zod.string(),
        brokerQuantity: zod.stringFormat(
          "decimal",
          importBrokerReportResponsePositionMismatchesItemBrokerQuantityRegExp,
        ),
        replayedQuantity: zod.stringFormat(
          "decimal",
          importBrokerReportResponsePositionMismatchesItemReplayedQuantityRegExp,
        ),
      }),
    )
    .nullable(),
});

/**
 * Returns open holdings with first-in-first-out cost basis, market value at the last known price, unrealised gain and dividends in each security's own currency, a dividend paid in another currency converted at the rate on its date. Totals and the per-year income table are in the reporting currency: market value at the newest exchange rate, cost at the rate on each purchase's date, and realised gains, dividends, tax and fees at the rate on each transaction's date. IsComplete is false when a holding has no price or no exchange rate, in which case totals leave it out.
 * @summary Get the investment portfolio
 */
export const portfolioResponseMarketValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseCostBasisRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseUnrealizedGainRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseRealizedGainRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseDividendsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseWithholdingTaxRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseFeesRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseHoldingsItemSecurityLastPriceRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const portfolioResponseHoldingsItemQuantityRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseHoldingsItemAverageCostRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseHoldingsItemCostBasisRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseHoldingsItemMarketValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseHoldingsItemUnrealizedGainRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const portfolioResponseHoldingsItemUnrealizedPercentRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const portfolioResponseHoldingsItemMarketValueReportingRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const portfolioResponseHoldingsItemRealizedGainRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseHoldingsItemDividendsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseYearsItemDividendsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseYearsItemWithholdingTaxRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseYearsItemInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseYearsItemFeesRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const portfolioResponseYearsItemRealizedGainRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const PortfolioResponse = zod.object({
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  marketValue: zod.stringFormat("decimal", portfolioResponseMarketValueRegExp),
  costBasis: zod.stringFormat("decimal", portfolioResponseCostBasisRegExp),
  unrealizedGain: zod.stringFormat("decimal", portfolioResponseUnrealizedGainRegExp),
  realizedGain: zod.stringFormat("decimal", portfolioResponseRealizedGainRegExp),
  dividends: zod.stringFormat("decimal", portfolioResponseDividendsRegExp),
  withholdingTax: zod.stringFormat("decimal", portfolioResponseWithholdingTaxRegExp),
  fees: zod.stringFormat("decimal", portfolioResponseFeesRegExp),
  isComplete: zod.boolean(),
  holdings: zod.array(
    zod.object({
      accountId: zod.uuid(),
      security: zod.object({
        id: zod.uuid(),
        symbol: zod.string(),
        name: zod.string(),
        isin: zod.string().nullable(),
        exchange: zod.string().nullable(),
        type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
        currency: zod.enum([
          "eur",
          "usd",
          "gbp",
          "chf",
          "pln",
          "sek",
          "nok",
          "dkk",
          "czk",
          "huf",
          "ron",
          "isk",
          "try",
          "jpy",
          "cny",
          "hkd",
          "sgd",
          "krw",
          "inr",
          "idr",
          "myr",
          "php",
          "thb",
          "aud",
          "nzd",
          "cad",
          "mxn",
          "brl",
          "ils",
          "zar",
        ]),
        lastPrice: zod
          .stringFormat("decimal", portfolioResponseHoldingsItemSecurityLastPriceRegExp)
          .nullable(),
        lastPriceDate: zod.union([zod.null(), zod.iso.date()]),
      }),
      quantity: zod.stringFormat("decimal", portfolioResponseHoldingsItemQuantityRegExp),
      averageCost: zod.stringFormat("decimal", portfolioResponseHoldingsItemAverageCostRegExp),
      costBasis: zod.stringFormat("decimal", portfolioResponseHoldingsItemCostBasisRegExp),
      marketValue: zod
        .stringFormat("decimal", portfolioResponseHoldingsItemMarketValueRegExp)
        .nullable(),
      unrealizedGain: zod
        .stringFormat("decimal", portfolioResponseHoldingsItemUnrealizedGainRegExp)
        .nullable(),
      unrealizedPercent: zod
        .stringFormat("decimal", portfolioResponseHoldingsItemUnrealizedPercentRegExp)
        .nullable(),
      marketValueReporting: zod
        .stringFormat("decimal", portfolioResponseHoldingsItemMarketValueReportingRegExp)
        .nullable(),
      realizedGain: zod.stringFormat("decimal", portfolioResponseHoldingsItemRealizedGainRegExp),
      dividends: zod.stringFormat("decimal", portfolioResponseHoldingsItemDividendsRegExp),
    }),
  ),
  years: zod.array(
    zod.object({
      year: zod.int(),
      dividends: zod.stringFormat("decimal", portfolioResponseYearsItemDividendsRegExp),
      withholdingTax: zod.stringFormat("decimal", portfolioResponseYearsItemWithholdingTaxRegExp),
      interest: zod.stringFormat("decimal", portfolioResponseYearsItemInterestRegExp),
      fees: zod.stringFormat("decimal", portfolioResponseYearsItemFeesRegExp),
      realizedGain: zod.stringFormat("decimal", portfolioResponseYearsItemRealizedGainRegExp),
    }),
  ),
});

/**
 * Securities are shared by everyone on the installation, because a price is the same for all holders.
 * @summary List securities
 */
export const securitiesResponseLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const SecuritiesResponseItem = zod.object({
  id: zod.uuid(),
  symbol: zod.string(),
  name: zod.string(),
  isin: zod.string().nullable(),
  exchange: zod.string().nullable(),
  type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  lastPrice: zod.stringFormat("decimal", securitiesResponseLastPriceRegExp).nullable(),
  lastPriceDate: zod.union([zod.null(), zod.iso.date()]),
});
export const SecuritiesResponse = zod.array(SecuritiesResponseItem);

/**
 * Adds a stock, ETF, fund, bond or other instrument that trades can refer to. Open to every signed-in user, because recording a first trade needs it. Symbol and currency together must be unique; the operation only ever adds, it never changes an existing security.
 * @summary Add a security
 */
export const createSecurityBodySymbolMin = 0;
export const createSecurityBodySymbolMax = 32;

export const createSecurityBodyNameMin = 0;
export const createSecurityBodyNameMax = 200;

export const createSecurityBodyIsinRegExp = new RegExp("^[A-Za-z]{2}[A-Za-z0-9]{9}[0-9]$");
export const createSecurityBodyExchangeMin = 0;
export const createSecurityBodyExchangeMax = 32;

export const createSecurityBodyLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateSecurityBody = zod.object({
  symbol: zod.string().min(createSecurityBodySymbolMin).max(createSecurityBodySymbolMax),
  name: zod.string().min(createSecurityBodyNameMin).max(createSecurityBodyNameMax),
  type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  isin: zod.string().regex(createSecurityBodyIsinRegExp).nullish(),
  exchange: zod
    .string()
    .min(createSecurityBodyExchangeMin)
    .max(createSecurityBodyExchangeMax)
    .nullish(),
  lastPrice: zod.stringFormat("decimal", createSecurityBodyLastPriceRegExp).nullish(),
  lastPriceDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe(
      "Defaults to today when a price is given without a date. Not in the future. The price is recorded in the price history; one dated before the last known price leaves the last known price alone.",
    ),
});

export const createSecurityResponseLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateSecurityResponse = zod.object({
  id: zod.uuid(),
  symbol: zod.string(),
  name: zod.string(),
  isin: zod.string().nullable(),
  exchange: zod.string().nullable(),
  type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  lastPrice: zod.stringFormat("decimal", createSecurityResponseLastPriceRegExp).nullable(),
  lastPriceDate: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Changes symbol, name, ISIN, exchange, type or currency, and optionally the price. Securities are shared by every user of the installation, so only an administrator may change them; anyone who holds the security sets its price through the price operation instead. The currency cannot change once the security has transactions.
 * @summary Update the details of a security
 */
export const updateSecurityBodySymbolMin = 0;
export const updateSecurityBodySymbolMax = 32;

export const updateSecurityBodyNameMin = 0;
export const updateSecurityBodyNameMax = 200;

export const updateSecurityBodyIsinRegExp = new RegExp("^[A-Za-z]{2}[A-Za-z0-9]{9}[0-9]$");
export const updateSecurityBodyExchangeMin = 0;
export const updateSecurityBodyExchangeMax = 32;

export const updateSecurityBodyLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateSecurityBody = zod.object({
  symbol: zod.string().min(updateSecurityBodySymbolMin).max(updateSecurityBodySymbolMax),
  name: zod.string().min(updateSecurityBodyNameMin).max(updateSecurityBodyNameMax),
  type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  isin: zod.string().regex(updateSecurityBodyIsinRegExp).nullish(),
  exchange: zod
    .string()
    .min(updateSecurityBodyExchangeMin)
    .max(updateSecurityBodyExchangeMax)
    .nullish(),
  lastPrice: zod.stringFormat("decimal", updateSecurityBodyLastPriceRegExp).nullish(),
  lastPriceDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe(
      "Defaults to today when a price is given without a date. Not in the future. The price is recorded in the price history; one dated before the last known price leaves the last known price alone.",
    ),
});

export const updateSecurityResponseLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateSecurityResponse = zod.object({
  id: zod.uuid(),
  symbol: zod.string(),
  name: zod.string(),
  isin: zod.string().nullable(),
  exchange: zod.string().nullable(),
  type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  lastPrice: zod.stringFormat("decimal", updateSecurityResponseLastPriceRegExp).nullable(),
  lastPriceDate: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Records the price for one date by hand, replacing a price already recorded for that date. Securities are shared by every user of the installation, so this is open only to a user who currently holds the security on an account they can see, and to administrators. The last known price of the security follows the newest date: a price for an earlier date adds a history point and leaves the last known price alone. A broker import records the mark price of its report date the same way.
 * @summary Record a price of a security
 */
export const setSecurityPriceBodyLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const SetSecurityPriceBody = zod.object({
  lastPrice: zod.stringFormat("decimal", setSecurityPriceBodyLastPriceRegExp),
  lastPriceDate: zod
    .union([zod.null(), zod.iso.date()])
    .optional()
    .describe("Defaults to today in the installation time zone. Not in the future."),
});

export const setSecurityPriceResponseLastPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const SetSecurityPriceResponse = zod.object({
  id: zod.uuid(),
  symbol: zod.string(),
  name: zod.string(),
  isin: zod.string().nullable(),
  exchange: zod.string().nullable(),
  type: zod.enum(["stock", "etf", "fund", "bond", "crypto", "other"]),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  lastPrice: zod.stringFormat("decimal", setSecurityPriceResponseLastPriceRegExp).nullable(),
  lastPriceDate: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Returns the recorded prices of a security, one per date, newest first. A point is written whenever a price is set by hand, a security is saved with a price, or a broker import carries a mark price for an open position. There is no market data feed, so dates between points have no row. Like securities themselves, the history is shared by every user of the installation.
 * @summary List the price history of a security
 */
export const securityPricesResponsePriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const SecurityPricesResponseItem = zod.object({
  date: zod.iso.date(),
  price: zod.stringFormat("decimal", securityPricesResponsePriceRegExp),
});
export const SecurityPricesResponse = zod.array(SecurityPricesResponseItem);

/**
 * Removes the price recorded for one date. The same rule as setting a price applies: open to a user who currently holds the security on an account they can see, and to administrators. The last known price of the security becomes the newest remaining point, or empty when none is left.
 * @summary Delete a point of a security's price history
 */
export const DeleteSecurityPriceResponse = zod.void();

/**
 * Returns one calendar year of recorded investment activity on the accounts the caller can see: every disposal with its proceeds, first-in-first-out cost basis, gain or loss and the acquisition date, quantity and cost of each lot it consumed, and every dividend, interest, withholding tax and standalone fee of that year. Every amount is given both in the currency it was recorded in and in the reporting currency at the rate frozen on the entry's date; withholding tax and fees are reported as positive amounts paid. AvailableYears lists the years that hold anything, newest first, and Year falls back to the newest of them, or to the current year when nothing is recorded. A year with nothing recorded answers an empty summary rather than an error. This is a summary of recorded data, not tax advice: no tax, allowance or rate is applied.
 * @summary Get the yearly investment tax summary
 */
export const taxSummaryResponseTotalsProceedsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsCostBasisRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsGainsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsLossesRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsRealizedGainRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsDividendsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsInterestRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsWithholdingTaxRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseTotalsFeesRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseDisposalsItemQuantityRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseDisposalsItemProceedsRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseDisposalsItemCostBasisRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseDisposalsItemGainRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseDisposalsItemReportingProceedsRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const taxSummaryResponseDisposalsItemReportingCostBasisRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const taxSummaryResponseDisposalsItemReportingGainRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const taxSummaryResponseDisposalsItemLotsItemQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const taxSummaryResponseDisposalsItemLotsItemCostRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const taxSummaryResponseDisposalsItemLotsItemReportingCostRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const taxSummaryResponseCashEntriesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const taxSummaryResponseCashEntriesItemReportingAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const TaxSummaryResponse = zod.object({
  year: zod.int(),
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  availableYears: zod.array(zod.int()),
  accounts: zod.array(
    zod.object({
      id: zod.uuid(),
      name: zod.string(),
    }),
  ),
  totals: zod.object({
    proceeds: zod.stringFormat("decimal", taxSummaryResponseTotalsProceedsRegExp),
    costBasis: zod.stringFormat("decimal", taxSummaryResponseTotalsCostBasisRegExp),
    gains: zod.stringFormat("decimal", taxSummaryResponseTotalsGainsRegExp),
    losses: zod.stringFormat("decimal", taxSummaryResponseTotalsLossesRegExp),
    realizedGain: zod.stringFormat("decimal", taxSummaryResponseTotalsRealizedGainRegExp),
    dividends: zod.stringFormat("decimal", taxSummaryResponseTotalsDividendsRegExp),
    interest: zod.stringFormat("decimal", taxSummaryResponseTotalsInterestRegExp),
    withholdingTax: zod.stringFormat("decimal", taxSummaryResponseTotalsWithholdingTaxRegExp),
    fees: zod.stringFormat("decimal", taxSummaryResponseTotalsFeesRegExp),
  }),
  disposals: zod.array(
    zod.object({
      id: zod.uuid(),
      date: zod.iso.date(),
      accountId: zod.uuid(),
      securityId: zod.uuid(),
      symbol: zod.string(),
      name: zod.string(),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      quantity: zod.stringFormat("decimal", taxSummaryResponseDisposalsItemQuantityRegExp),
      proceeds: zod.stringFormat("decimal", taxSummaryResponseDisposalsItemProceedsRegExp),
      costBasis: zod.stringFormat("decimal", taxSummaryResponseDisposalsItemCostBasisRegExp),
      gain: zod.stringFormat("decimal", taxSummaryResponseDisposalsItemGainRegExp),
      reportingProceeds: zod.stringFormat(
        "decimal",
        taxSummaryResponseDisposalsItemReportingProceedsRegExp,
      ),
      reportingCostBasis: zod.stringFormat(
        "decimal",
        taxSummaryResponseDisposalsItemReportingCostBasisRegExp,
      ),
      reportingGain: zod.stringFormat(
        "decimal",
        taxSummaryResponseDisposalsItemReportingGainRegExp,
      ),
      lots: zod.array(
        zod.object({
          acquiredOn: zod.iso.date(),
          quantity: zod.stringFormat(
            "decimal",
            taxSummaryResponseDisposalsItemLotsItemQuantityRegExp,
          ),
          cost: zod.stringFormat("decimal", taxSummaryResponseDisposalsItemLotsItemCostRegExp),
          reportingCost: zod.stringFormat(
            "decimal",
            taxSummaryResponseDisposalsItemLotsItemReportingCostRegExp,
          ),
        }),
      ),
    }),
  ),
  cashEntries: zod.array(
    zod.object({
      id: zod.uuid(),
      date: zod.iso.date(),
      accountId: zod.uuid(),
      type: zod.enum(["buy", "sell", "dividend", "withholdingTax", "interest", "fee", "split"]),
      symbol: zod.string().nullable(),
      description: zod.string().nullable(),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      amount: zod.stringFormat("decimal", taxSummaryResponseCashEntriesItemAmountRegExp),
      reportingAmount: zod.stringFormat(
        "decimal",
        taxSummaryResponseCashEntriesItemReportingAmountRegExp,
      ),
    }),
  ),
  isComplete: zod.boolean(),
});

/**
 * Answers the same year as GET /api/investments/tax-summary as a CSV attachment named investment-tax-summary-<year>.csv. Rows are written to the response as they are produced, so the answer carries no Content-Length. The Section column says what a row is: a Disposal row, one Lot row per lot that disposal consumed, and one Dividend, Interest, WithholdingTax or Fee row per cash entry. Every row carries the amount in the currency it was recorded in and again in the reporting currency at the frozen rate. There are no total rows: every row is a recorded entry. This is a summary of recorded data, not tax advice.
 * @summary Export the yearly investment tax summary as CSV
 */
export const ExportTaxSummaryResponse = zod.unknown();

/**
 * Buys and sells need a security, quantity and price, and move quantity times price plus or minus the fee in the security's currency. Dividends, withholding tax, interest and fees need an amount. A split needs a security and a ratio in Quantity and moves no cash. The cash effect lands on the account's balance in that currency and never counts as income or expense in reports or budgets.
 * @summary Record an investment transaction
 */

export const createInvestmentTransactionBodyQuantityRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createInvestmentTransactionBodyPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createInvestmentTransactionBodyAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createInvestmentTransactionBodyFeeRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createInvestmentTransactionBodyDescriptionMin = 0;
export const createInvestmentTransactionBodyDescriptionMax = 500;

export const CreateInvestmentTransactionBody = zod.object({
  accountId: zod.uuid().min(1),
  type: zod.enum(["buy", "sell", "dividend", "withholdingTax", "interest", "fee", "split"]),
  date: zod.iso.date(),
  securityId: zod.uuid().nullish(),
  quantity: zod
    .stringFormat("decimal", createInvestmentTransactionBodyQuantityRegExp)
    .nullish()
    .describe("Shares for a buy or sell; new shares per old share for a split."),
  price: zod.stringFormat("decimal", createInvestmentTransactionBodyPriceRegExp).nullish(),
  amount: zod
    .stringFormat("decimal", createInvestmentTransactionBodyAmountRegExp)
    .nullish()
    .describe("Cash amount for dividend, withholding tax, interest and fee entries."),
  fee: zod.stringFormat("decimal", createInvestmentTransactionBodyFeeRegExp).nullish(),
  currency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional()
    .describe(
      "Currency for entries without a security. Defaults to the security's currency, then the account's.",
    ),
  description: zod
    .string()
    .min(createInvestmentTransactionBodyDescriptionMin)
    .max(createInvestmentTransactionBodyDescriptionMax)
    .nullish(),
});

export const createInvestmentTransactionResponseQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const createInvestmentTransactionResponsePriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createInvestmentTransactionResponseFeeRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createInvestmentTransactionResponseCashAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const CreateInvestmentTransactionResponse = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  securityId: zod.uuid().nullable(),
  symbol: zod.string().nullable(),
  type: zod.enum(["buy", "sell", "dividend", "withholdingTax", "interest", "fee", "split"]),
  date: zod.iso.date(),
  quantity: zod.stringFormat("decimal", createInvestmentTransactionResponseQuantityRegExp),
  price: zod.stringFormat("decimal", createInvestmentTransactionResponsePriceRegExp),
  fee: zod.stringFormat("decimal", createInvestmentTransactionResponseFeeRegExp),
  cashAmount: zod.stringFormat("decimal", createInvestmentTransactionResponseCashAmountRegExp),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  description: zod.string().nullable(),
  source: zod.enum(["manual", "interactiveBrokers"]),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * Pages through trades, dividends, withholding tax, interest, fees and splits on accounts visible to you, newest first. CashAmount is signed: negative when cash left the account.
 * @summary List investment transactions
 */
export const investmentTransactionsResponseItemsItemQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const investmentTransactionsResponseItemsItemPriceRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const investmentTransactionsResponseItemsItemFeeRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const investmentTransactionsResponseItemsItemCashAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const InvestmentTransactionsResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.uuid(),
      accountId: zod.uuid(),
      securityId: zod.uuid().nullable(),
      symbol: zod.string().nullable(),
      type: zod.enum(["buy", "sell", "dividend", "withholdingTax", "interest", "fee", "split"]),
      date: zod.iso.date(),
      quantity: zod.stringFormat("decimal", investmentTransactionsResponseItemsItemQuantityRegExp),
      price: zod.stringFormat("decimal", investmentTransactionsResponseItemsItemPriceRegExp),
      fee: zod.stringFormat("decimal", investmentTransactionsResponseItemsItemFeeRegExp),
      cashAmount: zod.stringFormat(
        "decimal",
        investmentTransactionsResponseItemsItemCashAmountRegExp,
      ),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      description: zod.string().nullable(),
      source: zod.enum(["manual", "interactiveBrokers"]),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  ),
  page: zod.int(),
  pageSize: zod.int(),
  total: zod.int(),
});

/**
 * Removes the entry and its cash effect and records it in the trash, so POST /api/trash/restore can bring it back for 30 days. A later broker import will not bring a deleted imported entry back. A buy or split that later sales depend on is refused.
 * @summary Delete an investment transaction
 */
export const DeleteInvestmentTransactionResponse = zod.void();

/**
 * Replaces every field of an entry that was recorded by hand, under the same rules as recording one. Entries imported from a broker are corrected at the broker and imported again. A correction that would leave a later sale without enough shares is refused.
 * @summary Correct an investment transaction
 */

export const updateInvestmentTransactionBodyQuantityRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateInvestmentTransactionBodyPriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateInvestmentTransactionBodyAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateInvestmentTransactionBodyFeeRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateInvestmentTransactionBodyDescriptionMin = 0;
export const updateInvestmentTransactionBodyDescriptionMax = 500;

export const UpdateInvestmentTransactionBody = zod.object({
  accountId: zod.uuid().min(1),
  type: zod.enum(["buy", "sell", "dividend", "withholdingTax", "interest", "fee", "split"]),
  date: zod.iso.date(),
  securityId: zod.uuid().nullish(),
  quantity: zod
    .stringFormat("decimal", updateInvestmentTransactionBodyQuantityRegExp)
    .nullish()
    .describe("Shares for a buy or sell; new shares per old share for a split."),
  price: zod.stringFormat("decimal", updateInvestmentTransactionBodyPriceRegExp).nullish(),
  amount: zod
    .stringFormat("decimal", updateInvestmentTransactionBodyAmountRegExp)
    .nullish()
    .describe("Cash amount for dividend, withholding tax, interest and fee entries."),
  fee: zod.stringFormat("decimal", updateInvestmentTransactionBodyFeeRegExp).nullish(),
  currency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional()
    .describe(
      "Currency for entries without a security. Defaults to the security's currency, then the account's.",
    ),
  description: zod
    .string()
    .min(updateInvestmentTransactionBodyDescriptionMin)
    .max(updateInvestmentTransactionBodyDescriptionMax)
    .nullish(),
});

export const updateInvestmentTransactionResponseQuantityRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const updateInvestmentTransactionResponsePriceRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateInvestmentTransactionResponseFeeRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateInvestmentTransactionResponseCashAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const UpdateInvestmentTransactionResponse = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  securityId: zod.uuid().nullable(),
  symbol: zod.string().nullable(),
  type: zod.enum(["buy", "sell", "dividend", "withholdingTax", "interest", "fee", "split"]),
  date: zod.iso.date(),
  quantity: zod.stringFormat("decimal", updateInvestmentTransactionResponseQuantityRegExp),
  price: zod.stringFormat("decimal", updateInvestmentTransactionResponsePriceRegExp),
  fee: zod.stringFormat("decimal", updateInvestmentTransactionResponseFeeRegExp),
  cashAmount: zod.stringFormat("decimal", updateInvestmentTransactionResponseCashAmountRegExp),
  currency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  description: zod.string().nullable(),
  source: zod.enum(["manual", "interactiveBrokers"]),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * Returns the market value and the invested cost of the caller's open positions for a series of dates, in the reporting currency. Nothing is stored: for every date the buys, sells and splits up to that date are replayed first in, first out, each open position is valued at the latest recorded price on or before the date and converted at the exchange rate on or before the date, and the cost is what the remaining lots cost at the rate of their purchase. The series is daily for ranges up to about three months, weekly up to two years and monthly beyond, always ends on the last date of the range, and starts no earlier than the first trade. A point is partial when a position had no price or no exchange rate yet, or an imported history sold more than it bought; such a position is left out of both figures.
 * @summary Get the portfolio value over time
 */
export const valueHistoryResponsePointsItemMarketValueRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const valueHistoryResponsePointsItemCostBasisRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ValueHistoryResponse = zod.object({
  reportingCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  points: zod.array(
    zod.object({
      date: zod.iso.date(),
      marketValue: zod.stringFormat("decimal", valueHistoryResponsePointsItemMarketValueRegExp),
      costBasis: zod.stringFormat("decimal", valueHistoryResponsePointsItemCostBasisRegExp),
      isPartial: zod.boolean(),
    }),
  ),
});
