/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Sets a spending limit for one category over a weekly, monthly, quarterly or yearly window. A category can carry one budget per period, so a second budget for the same category and period is rejected; the same category may hold, say, a weekly and a yearly budget at once.
 * @summary Create a budget
 */

export const createBudgetBodyLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateBudgetBody = zod.object({
  categoryId: zod
    .uuid()
    .min(1)
    .describe("The category the limit applies to; must be visible to you."),
  limitAmount: zod
    .stringFormat("decimal", createBudgetBodyLimitAmountRegExp)
    .describe("Decimal string with at most two decimal places, greater than zero."),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod
    .boolean()
    .describe(
      "When true, what is left of the previous window raises this window's limit and an overspend lowers it, walking back at most twelve windows or to the budget's creation.",
    ),
});

export const createBudgetResponseLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseCarriedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseEffectiveLimitRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseSpentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseRemainingRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateBudgetResponse = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid(),
  categoryName: zod.string(),
  limitAmount: zod.stringFormat("decimal", createBudgetResponseLimitAmountRegExp),
  carriedAmount: zod.stringFormat("decimal", createBudgetResponseCarriedAmountRegExp),
  effectiveLimit: zod.stringFormat("decimal", createBudgetResponseEffectiveLimitRegExp),
  spent: zod.stringFormat("decimal", createBudgetResponseSpentRegExp),
  remaining: zod.stringFormat("decimal", createBudgetResponseRemainingRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod.boolean(),
  windowStart: zod.iso.date(),
  windowEnd: zod.iso.date(),
});

/**
 * Returns every budget you can see, each with its current window, the amount spent against it inside that window, the base limit, the amount carried over from the previous window and the effective limit the two add up to, so the client can render progress and explain the number without a second call.
 * @summary List budgets
 */
export const budgetsResponseLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseCarriedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseEffectiveLimitRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseSpentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseRemainingRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const BudgetsResponseItem = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid(),
  categoryName: zod.string(),
  limitAmount: zod.stringFormat("decimal", budgetsResponseLimitAmountRegExp),
  carriedAmount: zod.stringFormat("decimal", budgetsResponseCarriedAmountRegExp),
  effectiveLimit: zod.stringFormat("decimal", budgetsResponseEffectiveLimitRegExp),
  spent: zod.stringFormat("decimal", budgetsResponseSpentRegExp),
  remaining: zod.stringFormat("decimal", budgetsResponseRemainingRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod.boolean(),
  windowStart: zod.iso.date(),
  windowEnd: zod.iso.date(),
});
export const BudgetsResponse = zod.array(BudgetsResponseItem);

/**
 * Removes the spending limit. Transactions in the category are untouched.
 * @summary Delete a budget
 */
export const DeleteBudgetResponse = zod.void();

/**
 * Changes the limit, the period or the rollover switch, or moves the budget to a different category. Spending already recorded is re-evaluated against the new window the next time the budget is read.
 * @summary Update a budget
 */

export const updateBudgetBodyLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateBudgetBody = zod.object({
  categoryId: zod.uuid().min(1),
  limitAmount: zod.stringFormat("decimal", updateBudgetBodyLimitAmountRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod
    .boolean()
    .describe("Whether the previous window's remainder adjusts this window's limit."),
});

export const updateBudgetResponseLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseCarriedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseEffectiveLimitRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseSpentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseRemainingRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateBudgetResponse = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid(),
  categoryName: zod.string(),
  limitAmount: zod.stringFormat("decimal", updateBudgetResponseLimitAmountRegExp),
  carriedAmount: zod.stringFormat("decimal", updateBudgetResponseCarriedAmountRegExp),
  effectiveLimit: zod.stringFormat("decimal", updateBudgetResponseEffectiveLimitRegExp),
  spent: zod.stringFormat("decimal", updateBudgetResponseSpentRegExp),
  remaining: zod.stringFormat("decimal", updateBudgetResponseRemainingRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod.boolean(),
  windowStart: zod.iso.date(),
  windowEnd: zod.iso.date(),
});
