/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Sets a spending limit for one category over a weekly, monthly, quarterly or yearly window. A category can carry one budget per period, so a second budget for the same category and period is rejected; the same category may hold, say, a weekly and a yearly budget at once. Send tagId instead of categoryId to limit what is spent on a tag, such as a trip: every expense carrying the tag counts in full, whatever its category, and a refund carrying it lowers the spend.
 * @summary Create a budget
 */
export const createBudgetBodyLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateBudgetBody = zod.object({
  categoryId: zod
    .uuid()
    .nullable()
    .describe(
      "The expense category the limit applies to; must be visible to you. Send it or tagId, not both.",
    ),
  limitAmount: zod
    .stringFormat("decimal", createBudgetBodyLimitAmountRegExp)
    .describe("Decimal string with at most two decimal places, greater than zero."),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod
    .boolean()
    .describe(
      "When true, what is left of the previous window raises this window's limit and an overspend lowers it, walking back at most twelve windows or to the budget's creation.",
    ),
  tagId: zod
    .uuid()
    .nullish()
    .describe(
      "The tag the limit applies to; must be visible to you. Send it or categoryId, not both.",
    ),
  scope: zod.enum(["personal", "shared"]).optional(),
  householdId: zod.uuid().nullish(),
});

export const createBudgetResponseLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseCarriedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseEffectiveLimitRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseSpentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createBudgetResponseRemainingRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateBudgetResponse = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  tagId: zod.uuid().nullable(),
  name: zod.string(),
  limitAmount: zod.stringFormat("decimal", createBudgetResponseLimitAmountRegExp),
  carriedAmount: zod.stringFormat("decimal", createBudgetResponseCarriedAmountRegExp),
  effectiveLimit: zod.stringFormat("decimal", createBudgetResponseEffectiveLimitRegExp),
  spent: zod.stringFormat("decimal", createBudgetResponseSpentRegExp),
  remaining: zod.stringFormat("decimal", createBudgetResponseRemainingRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod.boolean(),
  windowStart: zod.iso.date(),
  windowEnd: zod.iso.date(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});

/**
 * Returns every budget you can see, each with its current window, the amount spent against it inside that window, the base limit, the amount carried over from the previous window and the effective limit the two add up to, so the client can render progress and explain the number without a second call. With asOf, each budget shows the window that contains that date instead of today's, with its spending and carry-over computed for that window; the limit is the budget's limit today, because changes to a limit are not kept by date.
 * @summary List budgets
 */
export const budgetsResponseLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseCarriedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseEffectiveLimitRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseSpentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const budgetsResponseRemainingRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const BudgetsResponseItem = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  tagId: zod.uuid().nullable(),
  name: zod.string(),
  limitAmount: zod.stringFormat("decimal", budgetsResponseLimitAmountRegExp),
  carriedAmount: zod.stringFormat("decimal", budgetsResponseCarriedAmountRegExp),
  effectiveLimit: zod.stringFormat("decimal", budgetsResponseEffectiveLimitRegExp),
  spent: zod.stringFormat("decimal", budgetsResponseSpentRegExp),
  remaining: zod.stringFormat("decimal", budgetsResponseRemainingRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod.boolean(),
  windowStart: zod.iso.date(),
  windowEnd: zod.iso.date(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});
export const BudgetsResponse = zod.array(BudgetsResponseItem);

/**
 * For every expense category you can see that had spending lately, returns what it cost in each of the last six complete windows of the period, oldest first. The window that holds today is left out because it is partial, and so is every window that ends before your earliest transaction. Spend is attributed as on the budgets page, split lines by their share. With at least three windows left the item carries their median, zero windows included, and a suggested limit: the median rounded up to a whole unit of the reporting currency, or null when the median is zero. isSteady is true when all six windows had spending, the median is at least 20 and the robust spread (median absolute deviation times 1.4826) is at most a quarter of the median. hasBudget tells whether you already have a budget of this period on the category. Nothing is written.
 * @summary Suggest budget limits from past spending
 */
export const budgetSuggestionsResponseCategoriesItemWindowsItemSpentRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const budgetSuggestionsResponseCategoriesItemMedianRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const budgetSuggestionsResponseCategoriesItemSuggestedLimitRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const BudgetSuggestionsResponse = zod.object({
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  categories: zod.array(
    zod.object({
      categoryId: zod.uuid(),
      categoryName: zod.string(),
      windows: zod.array(
        zod.object({
          start: zod.iso.date(),
          end: zod.iso.date(),
          spent: zod.stringFormat(
            "decimal",
            budgetSuggestionsResponseCategoriesItemWindowsItemSpentRegExp,
          ),
        }),
      ),
      median: zod
        .stringFormat("decimal", budgetSuggestionsResponseCategoriesItemMedianRegExp)
        .nullable(),
      suggestedLimit: zod
        .stringFormat("decimal", budgetSuggestionsResponseCategoriesItemSuggestedLimitRegExp)
        .nullable(),
      isSteady: zod.boolean(),
      hasBudget: zod.boolean(),
    }),
  ),
});

/**
 * Removes the spending limit. Transactions in the category are untouched.
 * @summary Delete a budget
 */
export const DeleteBudgetResponse = zod.void();

/**
 * Changes the limit, the period or the rollover switch, or moves the budget to a different category. Spending already recorded is re-evaluated against the new window the next time the budget is read.
 * @summary Update a budget
 */
export const updateBudgetBodyLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateBudgetBody = zod.object({
  categoryId: zod.uuid().nullable(),
  limitAmount: zod.stringFormat("decimal", updateBudgetBodyLimitAmountRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod
    .boolean()
    .describe("Whether the previous window's remainder adjusts this window's limit."),
  tagId: zod.uuid().nullish(),
  scope: zod.enum(["personal", "shared"]).optional(),
  householdId: zod.uuid().nullish(),
});

export const updateBudgetResponseLimitAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseCarriedAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseEffectiveLimitRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseSpentRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const updateBudgetResponseRemainingRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const UpdateBudgetResponse = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid().nullable(),
  tagId: zod.uuid().nullable(),
  name: zod.string(),
  limitAmount: zod.stringFormat("decimal", updateBudgetResponseLimitAmountRegExp),
  carriedAmount: zod.stringFormat("decimal", updateBudgetResponseCarriedAmountRegExp),
  effectiveLimit: zod.stringFormat("decimal", updateBudgetResponseEffectiveLimitRegExp),
  spent: zod.stringFormat("decimal", updateBudgetResponseSpentRegExp),
  remaining: zod.stringFormat("decimal", updateBudgetResponseRemainingRegExp),
  period: zod
    .enum(["monthly", "weekly", "quarterly", "yearly"])
    .describe("Weekly, Monthly, Quarterly, or Yearly. Defaults to Monthly."),
  rolloverEnabled: zod.boolean(),
  windowStart: zod.iso.date(),
  windowEnd: zod.iso.date(),
  scope: zod.enum(["personal", "shared"]),
  householdId: zod.uuid().nullable(),
});
