/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Sets a spending limit for one category. A category can carry a single budget, so creating a second one for the same category is rejected.
 * @summary Create a budget
 */

export const CreateBudgetBody = zod.object({
  categoryId: zod
    .uuid()
    .min(1)
    .describe("The category the limit applies to; must be visible to you."),
  limitAmount: zod
    .string()
    .describe("Decimal string with at most two decimal places, greater than zero."),
});

export const CreateBudgetResponse = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid(),
  categoryName: zod.string(),
  limitAmount: zod.string(),
  spent: zod.string(),
  remaining: zod.string(),
  period: zod.string(),
});

/**
 * Returns every budget you can see, each with the amount spent against it so far in the current period, so the client can render progress without a second call.
 * @summary List budgets
 */
export const BudgetsResponseItem = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid(),
  categoryName: zod.string(),
  limitAmount: zod.string(),
  spent: zod.string(),
  remaining: zod.string(),
  period: zod.string(),
});
export const BudgetsResponse = zod.array(BudgetsResponseItem);

/**
 * Removes the spending limit. Transactions in the category are untouched.
 * @summary Delete a budget
 */
export const DeleteBudgetResponse = zod.void();

/**
 * Changes the limit, or moves the budget to a different category. Spending already recorded is re-evaluated against the new limit the next time the budget is read.
 * @summary Update a budget
 */

export const UpdateBudgetBody = zod.object({
  categoryId: zod.uuid().min(1),
  limitAmount: zod.string(),
});

export const UpdateBudgetResponse = zod.object({
  id: zod.uuid(),
  categoryId: zod.uuid(),
  categoryName: zod.string(),
  limitAmount: zod.string(),
  spent: zod.string(),
  remaining: zod.string(),
  period: zod.string(),
});
