/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Creates a personal group, such as "Trip to Riga", and puts the listed transactions in it, so that GET /api/transactions/ledger folds them into one item. Grouping changes only how the ledger reads: every member keeps its own date, category and amount in reports, budgets, balances, the month close and the exports, and the member's last-updated time is left as it was. Every transaction must be one you entered, and none may already be in another group; remove it from that group first. Names need not be unique. The ledger offers grouping for two or more selected rows, while a row's own actions start a group with that row alone. Only a browser session can group; a personal API token cannot.
 * @summary Group transactions
 */
export const createTransactionGroupBodyNameMin = 0;
export const createTransactionGroupBodyNameMax = 120;

export const CreateTransactionGroupBody = zod.object({
  name: zod
    .string()
    .min(createTransactionGroupBodyNameMin)
    .max(createTransactionGroupBodyNameMax)
    .describe("The group's name, 1 to 120 characters."),
  transactionIds: zod.array(zod.uuid()).min(1).describe("The transactions to group, 1 to 200."),
});

export const CreateTransactionGroupResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  memberCount: zod.int(),
  firstDate: zod.iso.date(),
  lastDate: zod.iso.date(),
});

/**
 * Returns your own transaction groups that still hold at least one live transaction you can see, the one with the newest member first, each with its member count and the dates of its first and last member. Groups are personal: a housemate never sees them.
 * @summary List your transaction groups
 */
export const TransactionGroupsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  memberCount: zod.int(),
  firstDate: zod.iso.date(),
  lastDate: zod.iso.date(),
});
export const TransactionGroupsResponse = zod.array(TransactionGroupsResponseItem);

/**
 * Changes the name of one of your groups. Its members are untouched.
 * @summary Rename a transaction group
 */
export const renameTransactionGroupBodyNameMin = 0;
export const renameTransactionGroupBodyNameMax = 120;

export const RenameTransactionGroupBody = zod.object({
  name: zod
    .string()
    .min(renameTransactionGroupBodyNameMin)
    .max(renameTransactionGroupBodyNameMax)
    .describe("The new name, 1 to 120 characters."),
});

export const RenameTransactionGroupResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  memberCount: zod.int(),
  firstDate: zod.iso.date(),
  lastDate: zod.iso.date(),
});

/**
 * Removes one of your groups and keeps every member as an ordinary transaction. The group goes to the trash with the members it held, and POST /api/trash/restore with kind transactionGroup puts back the name and the members that are still live and in no other group.
 * @summary Ungroup
 */
export const UngroupTransactionGroupResponse = zod.void();

/**
 * Puts the listed transactions in one of your groups; split transactions are accepted. Every transaction must be one you entered and in no other group; a transaction already in this group is left as it is. Nothing is written when one of them is refused.
 * @summary Add transactions to a group
 */

export const AddToTransactionGroupBody = zod.object({
  transactionIds: zod.array(zod.uuid()).min(1).describe("The transactions to add, 1 to 200."),
});

export const AddToTransactionGroupResponse = zod.void();

/**
 * Returns the members of one of your groups that match the same filters as the ledger, newest first, so an expanded group row shows exactly the members that made it appear. The list is not paged: at most 200 members are returned, and truncated says whether more matched.
 * @summary List the members of a group
 */
export const transactionGroupMembersResponseItemsItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemLinesItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemReportingAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemUnusualTwoTypicalAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemRefundedAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemSharedExpenseTwoSharesItemAmountRegExp =
  new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const transactionGroupMembersResponseItemsItemSharedExpenseTwoMyShareRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemEnteredByMeDefault = false;
export const transactionGroupMembersResponseItemsItemContactSplitTwoOwnAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const transactionGroupMembersResponseItemsItemContactSplitTwoSharesItemAmountRegExp =
  new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const TransactionGroupMembersResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.uuid(),
      accountId: zod.uuid(),
      categoryId: zod.uuid().nullable(),
      type: zod.enum(["income", "expense"]),
      amount: zod.stringFormat("decimal", transactionGroupMembersResponseItemsItemAmountRegExp),
      date: zod.iso.date(),
      description: zod.string().nullable(),
      source: zod.enum(["manual", "imported", "api"]),
      isSplit: zod.boolean(),
      createdAt: zod.iso.datetime({ offset: true }),
      lines: zod
        .array(
          zod.object({
            id: zod.uuid(),
            categoryId: zod.uuid().nullable(),
            amount: zod.stringFormat(
              "decimal",
              transactionGroupMembersResponseItemsItemLinesItemAmountRegExp,
            ),
            description: zod.string().nullable(),
          }),
        )
        .nullable(),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      reportingAmount: zod.stringFormat(
        "decimal",
        transactionGroupMembersResponseItemsItemReportingAmountRegExp,
      ),
      tagIds: zod.array(zod.uuid()),
      attachmentCount: zod.int(),
      unusual: zod.union([
        zod.null(),
        zod.object({
          basis: zod.enum(["payee", "category"]),
          typicalAmount: zod.stringFormat(
            "decimal",
            transactionGroupMembersResponseItemsItemUnusualTwoTypicalAmountRegExp,
          ),
          factor: zod.number(),
          sampleSize: zod.int(),
        }),
      ]),
      unusualDismissed: zod.boolean(),
      debtPayment: zod
        .union([
          zod.null(),
          zod.object({
            id: zod.uuid(),
            debtId: zod.uuid(),
            debtName: zod.string(),
          }),
        ])
        .optional(),
      refundOf: zod
        .union([
          zod.null(),
          zod.object({
            id: zod.uuid(),
            date: zod.iso.date(),
            description: zod.string().nullable(),
          }),
        ])
        .optional(),
      refundedAmount: zod
        .stringFormat("decimal", transactionGroupMembersResponseItemsItemRefundedAmountRegExp)
        .nullish(),
      sharedExpense: zod
        .union([
          zod.null(),
          zod.object({
            id: zod.uuid(),
            householdId: zod.uuid(),
            householdName: zod.string(),
            method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
            shares: zod.array(
              zod.object({
                userId: zod.uuid(),
                name: zod.string(),
                weight: zod.int().nullable(),
                amount: zod.stringFormat(
                  "decimal",
                  transactionGroupMembersResponseItemsItemSharedExpenseTwoSharesItemAmountRegExp,
                ),
              }),
            ),
            myShare: zod.stringFormat(
              "decimal",
              transactionGroupMembersResponseItemsItemSharedExpenseTwoMyShareRegExp,
            ),
            amountDiffers: zod.boolean(),
          }),
        ])
        .optional(),
      note: zod.string().nullish(),
      payeeName: zod.string().nullish(),
      spreadMonths: zod.int().nullish(),
      spreadUntil: zod.union([zod.null(), zod.iso.date()]).optional(),
      place: zod.string().nullish(),
      latitude: zod.number().nullish(),
      longitude: zod.number().nullish(),
      groupId: zod.uuid().nullish(),
      enteredByMe: zod
        .boolean()
        .default(transactionGroupMembersResponseItemsItemEnteredByMeDefault),
      receiptItem: zod
        .union([
          zod.null(),
          zod.object({
            name: zod.string(),
            warrantyUntil: zod.union([zod.null(), zod.iso.date()]),
          }),
        ])
        .optional(),
      contactSplit: zod
        .union([
          zod.null(),
          zod.object({
            id: zod.uuid(),
            method: zod.enum(["equal", "shares", "exact"]).describe("Equal, Shares or Exact."),
            ownWeight: zod.int().nullable(),
            ownAmount: zod
              .stringFormat(
                "decimal",
                transactionGroupMembersResponseItemsItemContactSplitTwoOwnAmountRegExp,
              )
              .nullable(),
            shares: zod.array(
              zod.object({
                contactId: zod.uuid(),
                name: zod.string(),
                weight: zod.int().nullable(),
                amount: zod.stringFormat(
                  "decimal",
                  transactionGroupMembersResponseItemsItemContactSplitTwoSharesItemAmountRegExp,
                ),
              }),
            ),
          }),
        ])
        .optional(),
      payee: zod.string().nullish(),
    }),
  ),
  truncated: zod.boolean(),
});

/**
 * Takes one transaction out of one of your groups, so the ledger shows it as an ordinary row again. The group stays, even with a single member left.
 * @summary Remove a transaction from a group
 */
export const RemoveFromTransactionGroupResponse = zod.void();
