/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Sends one receipt photo or PDF to Anthropic, whose Claude model reads the items and picks one of the caller's visible expense categories for each, and answers the reading for review. Nothing in the ledger changes. Send multipart/form-data with exactly one of attachmentId, a file already attached to a transaction the caller can see, or file, a new JPEG, PNG, WebP, HEIC or PDF of at most 10 MB that is read but never stored. Photos are turned upright, stripped of their location and camera details and shrunk before they are sent; only the first 3 pages of a PDF are sent. The request waits for the answer, which takes 5 to 60 seconds. A reading is kept per user and file content: reading the same file again answers the stored reading with cached true and costs nothing, unless force is true, which reads it again and counts as another read. An item whose name the caller filed before gets the remembered category. For an uploaded file, candidates lists up to three visible unsplit expenses with the receipt's total, within three days of its date. Every read counts against the installation's monthly limit before Anthropic is called. Needs the ReceiptReading feature switch, and an administrator must enable reading and store an API key. Rate limited to 30 calls per five minutes per client.
 * @summary Read a receipt and propose its items by category
 */
export const ReadReceiptBody = zod.object({
  attachmentId: zod
    .uuid()
    .nullish()
    .describe("An attached file to read; leave empty when sending file."),
  file: zod
    .union([zod.null(), zod.instanceof(Blob)])
    .optional()
    .describe("A new file to read, at most 10 MB; leave empty when sending attachmentId."),
  force: zod.boolean().optional().describe("Read again even when a stored reading exists."),
});

export const readReceiptResponseResultTotalRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const readReceiptResponseResultItemsItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const readReceiptResponseResultItemsItemDiscountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const readReceiptResponseResultItemsItemDepositRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const readReceiptResponseResultAdjustmentsItemAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const readReceiptResponseCandidatesItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ReadReceiptResponse = zod.object({
  id: zod.uuid(),
  model: zod.string(),
  cached: zod.boolean(),
  result: zod.object({
    merchant: zod.string().nullable(),
    date: zod.union([zod.null(), zod.iso.date()]),
    currency: zod.union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ]),
    total: zod.stringFormat("decimal", readReceiptResponseResultTotalRegExp).nullable(),
    isReturn: zod.boolean(),
    pagesRead: zod.int(),
    pageCount: zod.int(),
    items: zod.array(
      zod.object({
        name: zod.string(),
        quantity: zod.string().nullable(),
        amount: zod.stringFormat("decimal", readReceiptResponseResultItemsItemAmountRegExp),
        discount: zod.stringFormat("decimal", readReceiptResponseResultItemsItemDiscountRegExp),
        deposit: zod.stringFormat("decimal", readReceiptResponseResultItemsItemDepositRegExp),
        categoryId: zod.uuid().nullable(),
        remembered: zod.boolean(),
      }),
    ),
    adjustments: zod.array(
      zod.object({
        kind: zod.enum(["discount", "voucher", "rounding", "other"]),
        label: zod.string(),
        amount: zod.stringFormat("decimal", readReceiptResponseResultAdjustmentsItemAmountRegExp),
      }),
    ),
  }),
  candidates: zod.array(
    zod.object({
      id: zod.uuid(),
      accountId: zod.uuid(),
      date: zod.iso.date(),
      description: zod.string().nullable(),
      amount: zod.stringFormat("decimal", readReceiptResponseCandidatesItemAmountRegExp),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    }),
  ),
});

/**
 * Stores the category the caller chose for each listed item of one of their readings, and remembers it for that item's name, so the next receipt with the same item gets it without asking the model. An item set to no category forgets its name. Names are compared after lowercasing and dropping digits, units and punctuation. Nothing in the ledger changes: the split itself is saved with the transaction. Every category must be an expense category the caller can see.
 * @summary Keep the categories chosen for a receipt's items
 */
export const UpdateReceiptCategoriesBody = zod.object({
  items: zod.array(
    zod.object({
      index: zod.int(),
      categoryId: zod.uuid().nullable(),
    }),
  ),
});

export const UpdateReceiptCategoriesResponse = zod.void();
