using JxFinance.Endpoints.Transactions.Shared;

namespace JxFinance.Endpoints.Transactions.GetUncategorizedSuggestions;

public sealed class GetUncategorizedSuggestionsValidator : TransactionFilterValidator<GetUncategorizedSuggestionsRequest>;
