// @ts-nocheck

// Generated by TanStack Router - do not edit.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CategorizationRulesRouteImport } from './routes/categorization-rules'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HouseholdsRouteImport } from './routes/households'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecurringBillsRouteImport } from './routes/recurring-bills'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as NetWorthDebtsDebtIdRouteImport } from './routes/net-worth_.debts.$debtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorizationRulesRoute = CategorizationRulesRouteImport.update({
  id: '/categorization-rules',
  path: '/categorization-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsRoute = HouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringBillsRoute = RecurringBillsRouteImport.update({
  id: '/recurring-bills',
  path: '/recurring-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthDebtsDebtIdRoute = NetWorthDebtsDebtIdRouteImport.update({
  id: '/net-worth_/debts/$debtId',
  path: '/net-worth/debts/$debtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/categorization-rules': typeof CategorizationRulesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/households': typeof HouseholdsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/net-worth': typeof NetWorthRoute
  '/profile': typeof ProfileRoute
  '/recurring-bills': typeof RecurringBillsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tags': typeof TagsRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/net-worth/debts/$debtId': typeof NetWorthDebtsDebtIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/categorization-rules': typeof CategorizationRulesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/households': typeof HouseholdsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/net-worth': typeof NetWorthRoute
  '/profile': typeof ProfileRoute
  '/recurring-bills': typeof RecurringBillsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tags': typeof TagsRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/net-worth/debts/$debtId': typeof NetWorthDebtsDebtIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/categorization-rules': typeof CategorizationRulesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/households': typeof HouseholdsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/net-worth': typeof NetWorthRoute
  '/profile': typeof ProfileRoute
  '/recurring-bills': typeof RecurringBillsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tags': typeof TagsRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/net-worth_/debts/$debtId': typeof NetWorthDebtsDebtIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/categorization-rules'
    | '/forgot-password'
    | '/goals'
    | '/households'
    | '/investments'
    | '/login'
    | '/net-worth'
    | '/profile'
    | '/recurring-bills'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/tags'
    | '/transactions'
    | '/users'
    | '/verify-email'
    | '/net-worth/debts/$debtId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/categorization-rules'
    | '/forgot-password'
    | '/goals'
    | '/households'
    | '/investments'
    | '/login'
    | '/net-worth'
    | '/profile'
    | '/recurring-bills'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/tags'
    | '/transactions'
    | '/users'
    | '/verify-email'
    | '/net-worth/debts/$debtId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/categorization-rules'
    | '/forgot-password'
    | '/goals'
    | '/households'
    | '/investments'
    | '/login'
    | '/net-worth'
    | '/profile'
    | '/recurring-bills'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/tags'
    | '/transactions'
    | '/users'
    | '/verify-email'
    | '/net-worth_/debts/$debtId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  CategoriesRoute: typeof CategoriesRoute
  CategorizationRulesRoute: typeof CategorizationRulesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  HouseholdsRoute: typeof HouseholdsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  NetWorthRoute: typeof NetWorthRoute
  ProfileRoute: typeof ProfileRoute
  RecurringBillsRoute: typeof RecurringBillsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TagsRoute: typeof TagsRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersRoute: typeof UsersRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  NetWorthDebtsDebtIdRoute: typeof NetWorthDebtsDebtIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorization-rules': {
      id: '/categorization-rules'
      path: '/categorization-rules'
      fullPath: '/categorization-rules'
      preLoaderRoute: typeof CategorizationRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households': {
      id: '/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof HouseholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring-bills': {
      id: '/recurring-bills'
      path: '/recurring-bills'
      fullPath: '/recurring-bills'
      preLoaderRoute: typeof RecurringBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth_/debts/$debtId': {
      id: '/net-worth_/debts/$debtId'
      path: '/net-worth/debts/$debtId'
      fullPath: '/net-worth/debts/$debtId'
      preLoaderRoute: typeof NetWorthDebtsDebtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  CategoriesRoute: CategoriesRoute,
  CategorizationRulesRoute: CategorizationRulesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  HouseholdsRoute: HouseholdsRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  NetWorthRoute: NetWorthRoute,
  ProfileRoute: ProfileRoute,
  RecurringBillsRoute: RecurringBillsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TagsRoute: TagsRoute,
  TransactionsRoute: TransactionsRoute,
  UsersRoute: UsersRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  NetWorthDebtsDebtIdRoute: NetWorthDebtsDebtIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
