/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Writes the rows the user kept from a preview into the ledger. Rows the preview flagged as already present are skipped rather than duplicated, and the response reports how many were imported and how many were skipped. A row's tagIds are written as they arrive, whether a rule suggested them in the preview or the user picked them, so an empty list imports the row with no tags. A row with existingTransactionId adds nothing: the bank entry is linked to that transaction, which keeps its date, category, tags and description and is then treated as imported, so the same entry is a duplicate next time. The audit entry names the format the rows came from.
 * @summary Commit previewed statement rows
 */

export const importConfirmBodyRowsItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ImportConfirmBody = zod.object({
  accountId: zod.uuid().min(1).describe("The account the rows post to; must be the one previewed."),
  rows: zod
    .array(
      zod.object({
        importRef: zod.string(),
        date: zod.iso.date(),
        description: zod.string().nullable(),
        amount: zod.stringFormat("decimal", importConfirmBodyRowsItemAmountRegExp),
        type: zod.enum(["income", "expense"]),
        categoryId: zod.uuid().nullable(),
        transferAccountId: zod.uuid().nullish(),
        existingTransferId: zod.uuid().nullish(),
        currency: zod
          .union([
            zod.null(),
            zod.enum([
              "eur",
              "usd",
              "gbp",
              "chf",
              "pln",
              "sek",
              "nok",
              "dkk",
              "czk",
              "huf",
              "ron",
              "isk",
              "try",
              "jpy",
              "cny",
              "hkd",
              "sgd",
              "krw",
              "inr",
              "idr",
              "myr",
              "php",
              "thb",
              "aud",
              "nzd",
              "cad",
              "mxn",
              "brl",
              "ils",
              "zar",
            ]),
          ])
          .optional(),
        tagIds: zod.array(zod.uuid()).nullish(),
        existingTransactionId: zod.uuid().nullish(),
      }),
    )
    .describe(
      "The rows to import, as returned by preview, with any category and tag corrections applied.",
    ),
  format: zod
    .enum(["swedbankCsv", "camt053"])
    .describe(
      "The statement format: swedbankCsv for a Swedbank CSV export or camt053 for an ISO 20022 camt.053 XML statement.",
    ),
});

export const ImportConfirmResponse = zod.object({
  imported: zod.int(),
  skippedDuplicates: zod.int(),
  linked: zod.int(),
});

/**
 * Parses an exported bank statement and returns the rows it found, each with a flag saying whether a matching transaction already exists in the account. Two formats are read: swedbankCsv, the Swedbank CSV export, and camt053, an ISO 20022 camt.053 XML statement. From a camt.053 file only booked entries are returned; pending and informational entries and entries that could not be read are counted in statement. When the file holds several statements, the one for the account's IBAN is read. A counterparty IBAN that belongs to another of your accounts fills in suggestedTransferAccountId. Your categorization rules are evaluated against each row's description, amount and flow type, and the first rule that matches fills in suggestedCategoryId, suggestedTagIds and matchedRuleName; a row nothing matched carries none of them. The suggestion is a suggestion: confirm sends back whatever the client decided. A row that is not a duplicate and has the same flow type, amount and currency as a transaction entered by hand on the account within three days of it carries that transaction in matchedTransaction, each transaction offered to one row at most, the closest date first. Nothing is written: this call only reads the file. Send the file as multipart/form-data.
 * @summary Preview a bank statement
 */
export const ImportPreviewBody = zod.object({
  file: zod.instanceof(Blob).optional(),
  accountId: zod.uuid().optional().describe("The account the statement belongs to."),
  format: zod
    .enum(["swedbankCsv", "camt053"])
    .optional()
    .describe(
      "The statement format: swedbankCsv for a Swedbank CSV export or camt053 for an ISO 20022 camt.053 XML statement.",
    ),
});

export const importPreviewResponseRowsItemAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const importPreviewResponseRowsItemUnusualTwoTypicalAmountRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const importPreviewResponseStatementClosingBalanceRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);
export const importPreviewResponseStatementLedgerBalanceAtCloseRegExp = new RegExp(
  "^-?\\d+(\\.\\d{1,8})?$",
);

export const ImportPreviewResponse = zod.object({
  rows: zod.array(
    zod.object({
      importRef: zod.string(),
      date: zod.iso.date(),
      payee: zod.string().nullable(),
      description: zod.string().nullable(),
      amount: zod.stringFormat("decimal", importPreviewResponseRowsItemAmountRegExp),
      type: zod.enum(["income", "expense"]),
      isDuplicate: zod.boolean(),
      looksLikeTransfer: zod.boolean(),
      currency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      suggestedCategoryId: zod.uuid().nullable(),
      suggestedTagIds: zod.array(zod.uuid()),
      matchedRuleName: zod.string().nullable(),
      isReversal: zod.boolean(),
      suggestedTransferAccountId: zod.uuid().nullable(),
      unusual: zod
        .union([
          zod.null(),
          zod.object({
            basis: zod.enum(["payee", "category"]),
            typicalAmount: zod.stringFormat(
              "decimal",
              importPreviewResponseRowsItemUnusualTwoTypicalAmountRegExp,
            ),
            factor: zod.number(),
            sampleSize: zod.int(),
          }),
        ])
        .optional(),
      matchedTransaction: zod
        .union([
          zod.null(),
          zod.object({
            id: zod.uuid(),
            date: zod.iso.date(),
            description: zod.string().nullable(),
            categoryId: zod.uuid().nullable(),
          }),
        ])
        .optional(),
    }),
  ),
  statement: zod.object({
    iban: zod.string().nullable(),
    ibanMatchesAccount: zod.boolean(),
    otherAccountId: zod.uuid().nullable(),
    notBooked: zod.int(),
    unreadable: zod.int(),
    closingDate: zod.union([zod.null(), zod.iso.date()]),
    closingBalance: zod
      .stringFormat("decimal", importPreviewResponseStatementClosingBalanceRegExp)
      .nullable(),
    closingCurrency: zod.union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ]),
    ledgerBalanceAtClose: zod
      .stringFormat("decimal", importPreviewResponseStatementLedgerBalanceAtCloseRegExp)
      .nullable(),
  }),
});
