/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Returns income, expense, and net totals for an arbitrary date range, with the per-category split. Unlike the dashboard endpoints, the window is yours to choose rather than being pinned to calendar months.
 * @summary Summarise income and expenses over a range
 */
export const ReportSummaryResponse = zod.object({
  periodStart: zod.iso.date(),
  periodEnd: zod.iso.date(),
  totalIncome: zod.string(),
  totalExpense: zod.string(),
  net: zod.string(),
  expenseByCategory: zod.array(
    zod.object({
      categoryId: zod.uuid().nullable(),
      categoryName: zod.string(),
      categoryIcon: zod.string().nullable(),
      amount: zod.string(),
    }),
  ),
  trend: zod.array(
    zod.object({
      bucketStart: zod.iso.date(),
      income: zod.string(),
      expense: zod.string(),
    }),
  ),
  trendBucket: zod.string(),
});
