/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Starts tracking progress towards a target amount, optionally by a target date. The goal is a standalone tracker: it is not tied to an account, and moving money does not update it by itself.
 * @summary Create a savings goal
 */
export const createGoalBodyNameMin = 0;
export const createGoalBodyNameMax = 100;

export const CreateGoalBody = zod.object({
  name: zod.string().min(createGoalBodyNameMin).max(createGoalBodyNameMax),
  targetAmount: zod
    .string()
    .describe("Decimal string with at most two decimal places, greater than zero."),
  currentAmount: zod
    .string()
    .nullable()
    .describe("Amount already saved. Defaults to zero when omitted."),
  targetDate: zod
    .union([zod.null(), zod.iso.date()])
    .describe("Optional date to reach the target by, as YYYY-MM-DD."),
});

export const CreateGoalResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  targetAmount: zod.string(),
  currentAmount: zod.string(),
  targetDate: zod.union([zod.null(), zod.iso.date()]),
});

/**
 * Returns your savings goals with the amount saved so far against each target.
 * @summary List savings goals
 */
export const GoalsResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  targetAmount: zod.string(),
  currentAmount: zod.string(),
  targetDate: zod.union([zod.null(), zod.iso.date()]),
});
export const GoalsResponse = zod.array(GoalsResponseItem);

/**
 * Removes the goal and its recorded progress. Nothing else in the ledger changes.
 * @summary Delete a savings goal
 */
export const DeleteGoalResponse = zod.void();

/**
 * Changes the name, the target, the target date, or how much has been put aside. This is how progress is recorded: raise currentAmount as money is saved.
 * @summary Update a savings goal
 */
export const updateGoalBodyNameMin = 0;
export const updateGoalBodyNameMax = 100;

export const UpdateGoalBody = zod.object({
  name: zod.string().min(updateGoalBodyNameMin).max(updateGoalBodyNameMax),
  targetAmount: zod.string(),
  currentAmount: zod.string(),
  targetDate: zod.union([zod.null(), zod.iso.date()]),
});

export const UpdateGoalResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  targetAmount: zod.string(),
  currentAmount: zod.string(),
  targetDate: zod.union([zod.null(), zod.iso.date()]),
});
