/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Records an exchange of one currency for another inside a single account, such as selling euros for dollars at a broker. The sold balance drops, the bought balance rises, and neither side counts as income or expense. An optional fee is booked as an ordinary expense transaction on the same account so it shows in reports and budgets.
 * @summary Convert currency inside an account
 */

export const createConversionBodyFromAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createConversionBodyToAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createConversionBodyDescriptionMin = 0;
export const createConversionBodyDescriptionMax = 500;

export const createConversionBodyFeeAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateConversionBody = zod.object({
  accountId: zod.uuid().min(1),
  fromAmount: zod
    .stringFormat("decimal", createConversionBodyFromAmountRegExp)
    .describe("Amount sold, as a decimal string greater than zero."),
  fromCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  toAmount: zod
    .stringFormat("decimal", createConversionBodyToAmountRegExp)
    .describe("Amount bought, as a decimal string greater than zero."),
  toCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  date: zod.iso.date(),
  description: zod
    .string()
    .min(createConversionBodyDescriptionMin)
    .max(createConversionBodyDescriptionMax)
    .nullable(),
  feeAmount: zod
    .stringFormat("decimal", createConversionBodyFeeAmountRegExp)
    .nullish()
    .describe("Optional fee. It is charged on top of the sold or bought amount."),
  feeCurrency: zod
    .union([
      zod.null(),
      zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
    ])
    .optional()
    .describe(
      "Currency of the fee; one of the two converted currencies. Defaults to the sold currency.",
    ),
  feeCategoryId: zod
    .uuid()
    .nullish()
    .describe("Optional expense category for the fee transaction."),
});

export const createConversionResponseFromAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createConversionResponseToAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const createConversionResponseFeeAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const CreateConversionResponse = zod.object({
  id: zod.uuid(),
  accountId: zod.uuid(),
  fromAmount: zod.stringFormat("decimal", createConversionResponseFromAmountRegExp),
  fromCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  toAmount: zod.stringFormat("decimal", createConversionResponseToAmountRegExp),
  toCurrency: zod.enum([
    "eur",
    "usd",
    "gbp",
    "chf",
    "pln",
    "sek",
    "nok",
    "dkk",
    "czk",
    "huf",
    "ron",
    "isk",
    "try",
    "jpy",
    "cny",
    "hkd",
    "sgd",
    "krw",
    "inr",
    "idr",
    "myr",
    "php",
    "thb",
    "aud",
    "nzd",
    "cad",
    "mxn",
    "brl",
    "ils",
    "zar",
  ]),
  rate: zod.string(),
  date: zod.iso.date(),
  description: zod.string().nullable(),
  feeAmount: zod.stringFormat("decimal", createConversionResponseFeeAmountRegExp).nullable(),
  feeCurrency: zod.union([
    zod.null(),
    zod.enum([
      "eur",
      "usd",
      "gbp",
      "chf",
      "pln",
      "sek",
      "nok",
      "dkk",
      "czk",
      "huf",
      "ron",
      "isk",
      "try",
      "jpy",
      "cny",
      "hkd",
      "sgd",
      "krw",
      "inr",
      "idr",
      "myr",
      "php",
      "thb",
      "aud",
      "nzd",
      "cad",
      "mxn",
      "brl",
      "ils",
      "zar",
    ]),
  ]),
  feeTransactionId: zod.uuid().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
});

/**
 * Pages through conversions on accounts visible to you, newest first. Rate is the bought amount divided by the sold amount.
 * @summary List currency conversions
 */
export const conversionsResponseItemsItemFromAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const conversionsResponseItemsItemToAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");
export const conversionsResponseItemsItemFeeAmountRegExp = new RegExp("^-?\\d+(\\.\\d{1,8})?$");

export const ConversionsResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.uuid(),
      accountId: zod.uuid(),
      fromAmount: zod.stringFormat("decimal", conversionsResponseItemsItemFromAmountRegExp),
      fromCurrency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      toAmount: zod.stringFormat("decimal", conversionsResponseItemsItemToAmountRegExp),
      toCurrency: zod.enum([
        "eur",
        "usd",
        "gbp",
        "chf",
        "pln",
        "sek",
        "nok",
        "dkk",
        "czk",
        "huf",
        "ron",
        "isk",
        "try",
        "jpy",
        "cny",
        "hkd",
        "sgd",
        "krw",
        "inr",
        "idr",
        "myr",
        "php",
        "thb",
        "aud",
        "nzd",
        "cad",
        "mxn",
        "brl",
        "ils",
        "zar",
      ]),
      rate: zod.string(),
      date: zod.iso.date(),
      description: zod.string().nullable(),
      feeAmount: zod
        .stringFormat("decimal", conversionsResponseItemsItemFeeAmountRegExp)
        .nullable(),
      feeCurrency: zod.union([
        zod.null(),
        zod.enum([
          "eur",
          "usd",
          "gbp",
          "chf",
          "pln",
          "sek",
          "nok",
          "dkk",
          "czk",
          "huf",
          "ron",
          "isk",
          "try",
          "jpy",
          "cny",
          "hkd",
          "sgd",
          "krw",
          "inr",
          "idr",
          "myr",
          "php",
          "thb",
          "aud",
          "nzd",
          "cad",
          "mxn",
          "brl",
          "ils",
          "zar",
        ]),
      ]),
      feeTransactionId: zod.uuid().nullable(),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  ),
  page: zod.int(),
  pageSize: zod.int(),
  total: zod.int(),
});

/**
 * Removes the conversion and the fee transaction it created, restoring both balances.
 * @summary Delete a currency conversion
 */
export const DeleteConversionResponse = zod.void();
