/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Creates the administrator account on a fresh instance. It works exactly once: once an administrator exists the endpoint answers 409 for good. Rate limited to five attempts per five minutes per client.
 * @summary Provision the first administrator
 */
export const setupBodyEmailMin = 0;
export const setupBodyEmailMax = 256;

export const setupBodyEmailRegExp = new RegExp("^[^@]+@[^@]+$");
export const setupBodyPasswordMin = 8;
export const setupBodyPasswordMax = 100;

export const setupBodyDisplayNameMin = 0;
export const setupBodyDisplayNameMax = 100;

export const SetupBody = zod.object({
  email: zod.email().min(setupBodyEmailMin).max(setupBodyEmailMax).regex(setupBodyEmailRegExp),
  password: zod.string().min(setupBodyPasswordMin).max(setupBodyPasswordMax),
  displayName: zod.string().min(setupBodyDisplayNameMin).max(setupBodyDisplayNameMax),
});

export const SetupResponse = zod.object({
  id: zod.uuid(),
  email: zod.string(),
  displayName: zod.string(),
  role: zod.string(),
  twoFactorEnabled: zod.boolean(),
  isActive: zod.boolean(),
  emailConfirmed: zod.boolean(),
  billReminderEmails: zod.boolean(),
});

/**
 * Reports whether the instance still has no administrator. The client calls this before choosing between the setup screen and the login screen. It stays callable without a session and discloses nothing beyond the single flag.
 * @summary Check whether first-run setup is needed
 */
export const SetupStatusResponse = zod.object({
  needsSetup: zod.boolean(),
});
