/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Jx Finance API
 * Personal and household finance ledger. Every route lives under /api and answers JSON. Money is carried as a decimal string with at most two decimal places so nothing is lost to floating point; dates are YYYY-MM-DD in the instance time zone. Collections that can grow are paged with page and pageSize and answer with items, page, pageSize, and total. Authentication is a session cookie from POST /api/auth/login, so browser clients must send credentials. Failures answer application/problem+json with a machine-readable code per error; see the ProblemDetails schema.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Creates the administrator account on a fresh instance and signs this browser in with a session that is not remembered, then marks the guided setup as pending in the settings. It works exactly once: once an administrator exists the endpoint answers 409 for good. Rate limited to five attempts per five minutes per client.
 * @summary Provision the first administrator
 */
export const setupBodyEmailMin = 0;
export const setupBodyEmailMax = 256;

export const setupBodyEmailRegExp = new RegExp("^[^@]+@[^@]+$");
export const setupBodyPasswordMin = 8;
export const setupBodyPasswordMax = 100;

export const setupBodyDisplayNameMin = 0;
export const setupBodyDisplayNameMax = 100;

export const SetupBody = zod.object({
  email: zod.email().min(setupBodyEmailMin).max(setupBodyEmailMax).regex(setupBodyEmailRegExp),
  password: zod.string().min(setupBodyPasswordMin).max(setupBodyPasswordMax),
  displayName: zod.string().min(setupBodyDisplayNameMin).max(setupBodyDisplayNameMax),
});

export const SetupResponse = zod.object({
  id: zod.uuid(),
  email: zod.string(),
  displayName: zod.string(),
  role: zod.string(),
  twoFactorEnabled: zod.boolean(),
  isActive: zod.boolean(),
  emailConfirmed: zod.boolean(),
  emailNotificationTypes: zod.array(
    zod.enum([
      "billDue",
      "budgetWarning",
      "budgetExceeded",
      "unusualAmount",
      "unusualAmounts",
      "recurringPriceRise",
      "monthReadyToClose",
      "monthlyDigest",
      "lowBalance",
      "warrantyExpiring",
      "importWaiting",
    ]),
  ),
  discordNotificationTypes: zod.array(
    zod.enum([
      "billDue",
      "budgetWarning",
      "budgetExceeded",
      "unusualAmount",
      "unusualAmounts",
      "recurringPriceRise",
      "monthReadyToClose",
      "monthlyDigest",
      "lowBalance",
      "warrantyExpiring",
      "importWaiting",
    ]),
  ),
  telegramNotificationTypes: zod.array(
    zod.enum([
      "billDue",
      "budgetWarning",
      "budgetExceeded",
      "unusualAmount",
      "unusualAmounts",
      "recurringPriceRise",
      "monthReadyToClose",
      "monthlyDigest",
      "lowBalance",
      "warrantyExpiring",
      "importWaiting",
    ]),
  ),
  language: zod.string().nullable(),
  monthlyDigestEverything: zod.boolean(),
  monthlyDigestHouseholdIds: zod.array(zod.uuid()),
});

/**
 * Fills the administrator's empty ledger with six months of sample accounts, transactions, budgets, goals, recurring entries, net worth and a household, in the reporting currency, and sets demoData in the settings. Offered only during the guided setup, so it answers 409 setup.notPending once the setup is finished, and 409 setup.ledgerNotEmpty when the administrator already has an account.
 * @summary Load demo data
 */
export const LoadDemoDataResponse = zod.void();

/**
 * Empties every ledger table, including anything entered since the demo data was loaded, gives the administrator the starter categories again and clears demoData. Users, sign-in data, sessions, settings and exchange rates stay. Allowed only while demoData is set and the administrator is the only user; otherwise it answers 409 setup.demoNotRemovable.
 * @summary Remove the demo data and start for real
 */
export const RemoveDemoDataResponse = zod.void();

/**
 * Clears setupPending in the settings, so the client stops opening the guided setup for administrators. Skipping the setup calls this too. Calling it again changes nothing.
 * @summary Finish the guided setup
 */
export const FinishSetupResponse = zod.void();

/**
 * Tells the guided setup which optional parts are installed where the API runs, whatever the feature switches say: receiptReaderInstalled is true when Tesseract is available for receipt reading.
 * @summary Read what this server can run
 */
export const SetupReadinessResponse = zod.object({
  receiptReaderInstalled: zod.boolean(),
});

/**
 * Reports whether the instance still has no administrator. The client calls this before choosing between the setup screen and the login screen. It stays callable without a session and discloses nothing beyond the single flag.
 * @summary Check whether first-run setup is needed
 */
export const SetupStatusResponse = zod.object({
  needsSetup: zod.boolean(),
});
